/**
 * FactLedger — initialState의 모든 숫자 리프를 출처에 연결한다 (docs/authoring-guide.md 저자 체크리스트 1).
 * tag: VERIFY (2차 출처/미확인, 릴리스 전 재검증) · STYLIZED (선언된 단순화) · CAL (보정 가정, calibration.md)
 * 단위: 조원(KRW 1e12) 외 명시.
 */
export interface FactRow {
  path: string
  value: number
  unit: string
  asOf: string
  knownAt?: string
  sourceId: string
  tag?: 'VERIFY' | 'STYLIZED' | 'CAL'
  note?: string
}

const BRIEF = 'mg-joint-briefing-2023'
const H1 = 'fsc-80662'

export const MG_FACTS: FactRow[] = [
  // ───────── 유동성 ─────────
  {
    path: 'institution.cash',
    value: 30.7,
    unit: '조원',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    tag: 'CAL',
    note: '상환준비금 13.36 + 현금성자산 77.3 중 즉시 가용 현금·예치금 17.3 = 30.66 → 30.7',
  },
  {
    path: 'institution.securities.afs.marketValue',
    value: 40,
    unit: '조원',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    tag: 'CAL',
    note: '현금성자산 77.3 중 국고채·통안채(RP 담보 적격) 배분',
  },
  {
    path: 'institution.securities.afs.bookValue',
    value: 40.8,
    unit: '조원',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    tag: 'STYLIZED',
    note: '미실현손실 2% (2022~23 금리 상승분 근사)',
  },
  {
    path: 'institution.securities.afs.modDuration',
    value: 2.5,
    unit: 'y',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.securities.afs.pledgedShare',
    value: 0,
    unit: 'fraction',
    asOf: '2023-07-04',
    sourceId: 'press-bank-rp-2023-07-11',
    note: 'RP 담보 제공 전',
  },
  {
    path: 'institution.securities.htm.marketValue',
    value: 20,
    unit: '조원',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    tag: 'CAL',
    note: '현금성자산 77.3 중 은행채·기타 채권 배분',
  },
  {
    path: 'institution.securities.htm.bookValue',
    value: 20.6,
    unit: '조원',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    tag: 'STYLIZED',
    note: '미실현손실 3%',
  },
  {
    path: 'institution.securities.htm.modDuration',
    value: 3.0,
    unit: 'y',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.securities.htm.pledgedShare',
    value: 0,
    unit: 'fraction',
    asOf: '2023-07-04',
    sourceId: 'press-bank-rp-2023-07-11',
  },
  // ───────── 대출·자산 ─────────
  {
    path: 'institution.loans.corporate',
    value: 56.4,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: 'press-mg-outflow-2023-07-17',
    tag: 'VERIFY',
    note: '건설·부동산 대출 56.4조(연체 9.23%) — 국회 제출 자료 인용 보도(2차)',
  },
  {
    path: 'institution.loans.sme',
    value: 55,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: H1,
    tag: 'STYLIZED',
    note: '기타 기업대출 배분',
  },
  {
    path: 'institution.loans.retail',
    value: 85,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: H1,
    tag: 'STYLIZED',
    note: '가계대출 배분(총대출 ≈196.4)',
  },
  {
    path: 'institution.loans.fi',
    value: 0,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: H1,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.loans.nonPerforming',
    value: 12.16,
    unit: '조원',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    note: '연체액 12.16조(잠정)',
  },
  {
    path: 'institution.loans.avgDuration',
    value: 2.5,
    unit: 'y',
    asOf: '2023-06-30',
    sourceId: H1,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.otherAssets',
    value: 3.6,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: H1,
    tag: 'STYLIZED',
    note: 'plug: 총자산 290.7 − (30.7 + 60 + 196.4)',
  },
  // ───────── 예금 세그먼트 ─────────
  {
    path: 'institution.deposits.0.balance',
    value: 195,
    unit: '조원',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    tag: 'STYLIZED',
    note: '예수금 259.6 중 5천만원 이하 보호 예금 ≈75%',
  },
  {
    path: 'institution.deposits.1.balance',
    value: 40,
    unit: '조원',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    tag: 'STYLIZED',
    note: '5천만원 초과 개인 예금 ≈15%',
  },
  {
    path: 'institution.deposits.2.balance',
    value: 12,
    unit: '조원',
    asOf: '2023-06-29',
    sourceId: 'mois-special-inspection-2023-07-04',
    tag: 'STYLIZED',
    note: '특별검사 30개·특별점검 70개 대상 금고의 예금',
  },
  {
    path: 'institution.deposits.3.balance',
    value: 12.6,
    unit: '조원',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    tag: 'STYLIZED',
    note: '법인·단체·공공 예금 plug → 합계 259.6',
  },
  {
    path: 'institution.deposits.0.dailyCap',
    value: 0.03,
    unit: 'fraction/day',
    asOf: '2023-07',
    sourceId: 'fsb-depositor-behaviour-2024',
    tag: 'CAL',
    note: '창구·ATM 채널 상한(노던록 줄서기 상한 10%/일의 시스템 평균 완화값)',
  },
  // 세그먼트 유출률 (S0/S1/S2/S3) — calibration.md §1
  ...(
    [
      [
        '0',
        [0.001, 0.0036, 0.0043, 0.02],
        '7/5 S2 합계 ≈1.5조, 7/7 S1×0.8 ≈0.98조, 7/17 S1×0.5 ≈0.61조',
      ],
      ['1', [0.003, 0.0072, 0.0085, 0.08], '5천만원 초과: 보호 예금의 2배 수준'],
      [
        '2',
        [0.005, 0.016, 0.02, 0.2],
        '부실 우려 금고: 표적 인출, S3에서 저축은행 2011 영업정지 금고 수준',
      ],
      ['3', [0.002, 0.0052, 0.007, 0.06], '법인·단체: 운영성 예금'],
    ] as const
  ).flatMap(([i, rates, note]) =>
    rates.map((v, k) => ({
      path: `institution.deposits.${i}.runoffByState.${k}`,
      value: v,
      unit: 'fraction/day',
      asOf: '2023-07',
      sourceId: 'press-mg-outflow-2023-07-17',
      tag: 'CAL' as const,
      note: k === 0 ? note : undefined,
    })),
  ),
  // ───────── 도매·부채·자본 ─────────
  ...['unsecuredShort', 'unsecuredLong', 'repoL1', 'repoL2A', 'repoOther', 'cbAdvances'].map(
    (k) => ({
      path: `institution.wholesale.${k}`,
      value: 0,
      unit: '조원',
      asOf: '2023-06-30',
      sourceId: H1,
      tag: 'STYLIZED' as const,
      note: '중앙회 시장성 차입 없음(합성)',
    }),
  ),
  {
    path: 'institution.wholesale.cbFacilityCapacity',
    value: 0,
    unit: '조원',
    asOf: '2023-07-04',
    sourceId: 'bok-omo-2022-10-27',
    note: '한은 RP 대상기관 아님; 은행 RP 라인은 7/10~11 체결',
  },
  {
    path: 'institution.wholesale.cbFacilityPending',
    value: 0,
    unit: '조원',
    asOf: '2023-07-04',
    sourceId: 'press-bank-rp-2023-07-11',
  },
  {
    path: 'institution.committed.creditToCorporates',
    value: 0,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: H1,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.committed.liquidityToFIs',
    value: 0,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: H1,
    tag: 'STYLIZED',
    note: '중앙회→금고 지원은 합성 기관 내부 거래',
  },
  {
    path: 'institution.otherLiabilities',
    value: 7.0,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: H1,
    note: 'plug: 290.7 − 259.6 − 24.1',
  },
  {
    path: 'institution.capital.cet1',
    value: 24.1,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: H1,
    tag: 'CAL',
    note: '순자본비율 8.29% × 총자산 290.7',
  },
  {
    path: 'institution.capital.at1',
    value: 0,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: H1,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.capital.tier2',
    value: 0,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: H1,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.rwa',
    value: 290.7,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: H1,
    tag: 'STYLIZED',
    note: '순자본비율 = 순자본/총자산 근사 → RWA := 총자산 (CET1 지표 = 8.29%)',
  },
  {
    path: 'institution.leverageExposure',
    value: 290.7,
    unit: '조원',
    asOf: '2023-06-30',
    sourceId: H1,
    note: '총자산 290.7조',
  },
  {
    path: 'institution.fireSaleDiscount',
    value: 0.01,
    unit: 'fraction',
    asOf: '2023-07',
    sourceId: 'press-kfcc-bond-sale-2023-07-06',
    tag: 'CAL',
    note: '국고채 5조 블록 매도 ≈1% (기준 5조)',
  },
  {
    path: 'institution.taxRate',
    value: 0.2,
    unit: 'fraction',
    asOf: '2023',
    sourceId: H1,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.custom.delinquencyRate',
    value: 6.18,
    unit: 'pct',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    note: '잠정; 6말 확정 5.41% [fsc-80662]',
  },
  {
    path: 'institution.custom.depositorProtectionFund',
    value: 2.6,
    unit: '조원',
    asOf: '2023-06-29',
    sourceId: BRIEF,
  },
  {
    path: 'institution.custom.minimumCash',
    value: 0,
    unit: '조원',
    asOf: '2023-07-04',
    sourceId: BRIEF,
    tag: 'STYLIZED',
  },
  // ───────── 시장 ─────────
  {
    path: 'market.policyRateBp',
    value: 350,
    unit: 'bp',
    asOf: '2023-07-04',
    sourceId: 'bok-base-rate-2023',
  },
  {
    path: 'market.govt2yBp',
    value: 365,
    unit: 'bp',
    asOf: '2023-07-04',
    sourceId: 'bok-base-rate-2023',
    tag: 'VERIFY',
    note: '국고 3년 근사(금융투자협회 최종호가수익률 확인 필요)',
  },
  {
    path: 'market.govt10yBp',
    value: 367,
    unit: 'bp',
    asOf: '2023-07-04',
    sourceId: 'bok-base-rate-2023',
    tag: 'VERIFY',
  },
  {
    path: 'market.govt30yBp',
    value: 355,
    unit: 'bp',
    asOf: '2023-07-04',
    sourceId: 'bok-base-rate-2023',
    tag: 'VERIFY',
  },
  {
    path: 'market.creditSpreadIgBp',
    value: 70,
    unit: 'bp',
    asOf: '2023-07-04',
    sourceId: 'bok-base-rate-2023',
    tag: 'VERIFY',
    note: '회사채 AA− 3y 스프레드',
  },
  {
    path: 'market.creditSpreadHyBp',
    value: 400,
    unit: 'bp',
    asOf: '2023-07-04',
    sourceId: 'bok-base-rate-2023',
    tag: 'VERIFY',
    note: '회사채 BBB− 3y 스프레드',
  },
  {
    path: 'market.fundingStressBp',
    value: 15,
    unit: 'bp',
    asOf: '2023-07-04',
    sourceId: 'bok-base-rate-2023',
    tag: 'VERIFY',
    note: 'CD91 − 통안 91일',
  },
  {
    path: 'market.equityIndex',
    value: 100,
    unit: 'index',
    asOf: '2023-07-04',
    sourceId: 'bok-base-rate-2023',
    tag: 'STYLIZED',
    note: 'KOSPI 정규화',
  },
  {
    path: 'market.volIndex',
    value: 14,
    unit: 'index',
    asOf: '2023-07-04',
    sourceId: 'bok-base-rate-2023',
    tag: 'VERIFY',
    note: 'VKOSPI',
  },
  {
    path: 'market.fxUsdLocal',
    value: 1300,
    unit: 'KRW/USD',
    asOf: '2023-07-04',
    sourceId: 'bok-base-rate-2023',
    tag: 'VERIFY',
  },
  {
    path: 'market.ownStock',
    value: 100,
    unit: 'index',
    asOf: '2023-07-04',
    sourceId: H1,
    tag: 'STYLIZED',
    note: '비상장 — 엔진 미사용',
  },
  {
    path: 'market.ownCdsBp',
    value: 0,
    unit: 'bp',
    asOf: '2023-07-04',
    sourceId: H1,
    tag: 'STYLIZED',
  },
  // ───────── 카운터·감독 단계 ─────────
  {
    path: 'counters.startDeposits',
    value: 259.6,
    unit: '조원',
    asOf: '2023-06-29',
    sourceId: BRIEF,
    note: '예수금 259.6조 — 유출률 분모',
  },
  {
    path: 'counters.amplifier',
    value: 1,
    unit: 'x',
    asOf: '2023-07-04',
    sourceId: BRIEF,
    tag: 'CAL',
    note: '증폭 계수 초기값',
  },
  {
    path: 'counters.dampener',
    value: 1,
    unit: 'x',
    asOf: '2023-07-04',
    sourceId: BRIEF,
    tag: 'CAL',
    note: '완화 계수 초기값',
  },
  {
    path: 'counters.useKrLcr',
    value: 1,
    unit: 'flag',
    asOf: '2023-07-04',
    sourceId: H1,
    tag: 'STYLIZED',
    note: '국내 LCR 파라미터(안정 소매 5%) — 참고 지표',
  },
  {
    path: 'regulatorLevel',
    value: 1,
    unit: 'index',
    asOf: '2023-07-04',
    sourceId: 'mois-special-inspection-2023-07-04',
    tag: 'CAL',
    note: 'R1 강화 모니터링 — 행안부 특별점검·특별검사 착수',
  },
  // ───────── 신뢰 ─────────
  {
    path: 'confidence.index',
    value: 58,
    unit: 'index',
    asOf: '2023-07-04',
    sourceId: 'mois-special-inspection-2023-07-04',
    tag: 'CAL',
    note: 'S1 우려: 연체율 6%대 보도·특별점검 발표; 합병 공시(−15) 후 S2가 되도록 설정',
  },
  {
    path: 'confidence.depositors',
    value: 58,
    unit: 'index',
    asOf: '2023-07-04',
    sourceId: 'mois-special-inspection-2023-07-04',
    tag: 'CAL',
  },
  {
    path: 'confidence.counterparties',
    value: 70,
    unit: 'index',
    asOf: '2023-07-04',
    sourceId: 'mois-special-inspection-2023-07-04',
    tag: 'CAL',
  },
  {
    path: 'confidence.regulators',
    value: 50,
    unit: 'index',
    asOf: '2023-07-04',
    sourceId: 'audit-savings-bank-2011',
    tag: 'CAL',
    note: '행안부 단독 감독·감사원 미감사',
  },
  {
    path: 'confidence.investors',
    value: 65,
    unit: 'index',
    asOf: '2023-07-04',
    sourceId: 'mois-special-inspection-2023-07-04',
    tag: 'CAL',
  },
  {
    path: 'confidence.media',
    value: 50,
    unit: 'index',
    asOf: '2023-07-04',
    sourceId: 'mois-special-inspection-2023-07-04',
    tag: 'CAL',
  },
  {
    path: 'confidence.board',
    value: 65,
    unit: 'index',
    asOf: '2023-07-04',
    sourceId: 'mois-special-inspection-2023-07-04',
    tag: 'CAL',
  },
  // ───────── 이벤트·효과 앵커 (초기 상태 외) ─────────
  {
    path: 'event.t2.bondSale',
    value: 1.6,
    unit: '조원',
    asOf: '2023-07-06',
    sourceId: 'press-kfcc-bond-sale-2023-07-06',
    tag: 'VERIFY',
    note: '중앙회 채권 매도(2차 출처)',
  },
  {
    path: 'event.t4.bankRp',
    value: 6.2,
    unit: '조원',
    asOf: '2023-07-11',
    sourceId: 'press-bank-rp-2023-07-11',
    note: '5대 은행 + 산은·기은 RP 매입 6~6.2조(상한값 사용)',
  },
  {
    path: 'checkpoint.t2.dailyOutflow',
    value: 1.8,
    unit: '조원',
    asOf: '2023-07-06',
    sourceId: 'mois-redeposit-2023-07-07',
    tag: 'CAL',
    note: '7/7 "전일比 약 1조 감소"에서 역산한 7/6 피크(1~2조 밴드)',
  },
  {
    path: 'checkpoint.t6.dailyOutflow',
    value: 0.65,
    unit: '조원',
    asOf: '2023-07-17',
    sourceId: 'press-mg-outflow-2023-07-17',
    note: '일 6,000~7,000억',
  },
  {
    path: 'checkpoint.t6.cumulativeOutflow',
    value: 8,
    unit: '조원',
    asOf: '2023-07-17',
    sourceId: 'press-mg-outflow-2023-07-17',
    tag: 'CAL',
    note: '7/5~7/17 누적 6~10조 밴드; "7~8월 17조"는 [VERIFY]',
  },
]
