import type { Source } from '../../engine/types'

/**
 * mg-run-2023 서지. 공유 서지(src/content/sources.ts)와 같은 id는 같은 문서를 가리키며, 시나리오가
 * 단독으로도 무결성 린트를 통과하도록 여기에 다시 적는다. 언론 출처(press)는 사건 시각·인용·2차 수치
 * (채권 매도 1.6조, 은행 RP 6~6.2조, 일 인출 6,000~7,000억)에만 쓰고, 대차대조표 수치의 근거로는 쓰지 않는다.
 */
export const MG_SOURCES: Source[] = [
  // ───────── 1차·규제 출처 (2023.7 사건) ─────────
  {
    id: 'mois-special-inspection-2023-07-04',
    title: '새마을금고 연체율 상위 100개 금고 특별점검 실시 (행정안전부 보도자료)',
    publisher: '행정안전부',
    date: '2023-07-04',
    kind: 'regulatory',
    note: '연체율 상위 100개 금고 특별검사 30개·특별점검 70개, "연말 연체율 4% 이하" 목표. URL 미확인',
  },
  {
    id: 'kfcc-merger-notice-2023-07-05',
    title: '남양주동부새마을금고 · 화도새마을금고 흡수합병 공고',
    publisher: '새마을금고중앙회',
    date: '2023-07-05',
    kind: 'primary',
    note: '600억원대 PF 대출 부실로 남양주동부금고를 화도금고에 흡수합병; 합병 공시가 인출 행렬의 방아쇠. 공고 원문 URL 미확인',
  },
  {
    id: 'mg-joint-briefing-2023',
    title: '새마을금고 건전성 관련 관계부처 합동 브리핑(행안부·기재부·금융위·금감원·한은)',
    publisher: '행정안전부 외 범정부 대응단',
    date: '2023-07-06',
    kind: 'regulatory',
    note: '예수금 259.6조(6/29), 연체액 12.16조, 상환준비금 13.36조, 현금성자산 77.3조, 예금자보호준비금 2.6조; "합병 시에도 5천만원 초과 원리금 지급"; 특별검사 30개·특별점검 70개',
  },
  {
    id: 'mois-redeposit-2023-07-07',
    title: '새마을금고 중도해지 예금 재예치 시 이자·비과세 혜택 복원 (범정부 대응단 발표)',
    publisher: '행정안전부 · 범정부 대응단',
    date: '2023-07-07',
    kind: 'regulatory',
    note: '7/1~7/6 중도해지분을 7/14까지 재예치하면 최초 약정 이율·만기·비과세 복원(전례 없음); 같은 날 브리핑에서 "인출 전일比 약 1조 감소, 재예치 3,000건 이상/일" 언급. URL 미확인',
  },
  {
    id: 'fsc-80363',
    title: '[부처합동] 새마을금고는 안전하며 정부는 이를 충분히 뒷받침할 계획',
    publisher: '금융위원회 (범정부 실무지원단: 행안부·금융위·예보 등)',
    date: '2023-07-10',
    url: 'https://www.fsc.go.kr/no010101/80363',
    kind: 'regulatory',
    note: '부실 우려 금고는 우량금고로 P&A → 5천만원 초과 예금도 전액 보장, 필요시 정부 차입; 범정부 실무지원단(행안부·금융위 공동, 예보 포함)',
  },
  {
    id: 'fsc-80662',
    title: "[부처합동] 새마을금고 '23년 상반기 영업실적(잠정) 발표",
    publisher: '금융위원회 · 행정안전부',
    date: '2023-08-31',
    url: 'https://www.fsc.go.kr/no010101/80662',
    kind: 'regulatory',
    note: '총자산 290.7조, 총수신 259.4조, 연체율 5.41%(확정), 순자본비율 8.29%, 상반기 순손실 1,236억',
  },
  {
    id: 'kfcc-act',
    title: '새마을금고법 (예금자보호준비금 · 예금자보호 한도 · 행정안전부 감독)',
    publisher: '대한민국 법률',
    date: '2023-07',
    kind: 'primary',
    note: '예금자보호는 예금자보호법(예보)이 아닌 새마을금고법상 중앙회 예금자보호준비금으로 1인당 원리금 5천만원(2023.7 당시); 감독은 행정안전부. 조문 번호는 원문 확인 필요',
  },
  {
    id: 'mois-kfcc-supervision-standard',
    title: '새마을금고 감독기준 (행정안전부 고시) — 건설업·부동산업 대출 한도 각 30%, 합산 50%',
    publisher: '행정안전부',
    date: '2023-07',
    kind: 'regulatory',
    note: '신용공여한도 건설·부동산 각 30%/합산 50% (도시에 검증 항목). 고시 번호·시행일은 원문 확인 필요 [VERIFY]',
  },
  {
    id: 'bok-act',
    title:
      '한국은행법 (제65조 금융기관에 대한 긴급여신 · 제68조 공개시장운영 · 제80조 영리기업 여신)',
    publisher: '대한민국 법률 (위키문헌 수록본)',
    date: '2026-09',
    url: 'https://ko.wikisource.org/wiki/한국은행법',
    kind: 'primary',
    note: '65조: 유동성 악화 금융기관에 임시 적격담보로 긴급여신(금통위 4명 이상 찬성, 정부 의견 청취); 80조: 비은행 영리기업 여신(4명 이상)',
  },
  {
    id: 'bok-base-rate-2023',
    title: '통화정책방향 결정 — 기준금리 3.50% (2023.1.13 인상 후 2023.7.13 동결)',
    publisher: '한국은행 금융통화위원회',
    date: '2023-07-13',
    kind: 'regulatory',
    note: '2023.7 기준금리 3.50%. URL 미확인',
  },
  {
    id: 'bok-omo-2022-10-27',
    title: '한국은행 공개시장운영 조치(RP 매입 6조원, 적격담보증권 확대, 담보비율 인상 유예)',
    publisher: '한국은행',
    date: '2022-10-27',
    kind: 'regulatory',
    note: '비은행에 대한 한은 유동성 공급 선례(RP 6조); 새마을금고중앙회는 2023.7 당시 한은 RP 대상기관이 아니었다',
  },
  {
    id: 'fsc-87126',
    title: '「상호금융업감독규정」 개정안 금융위 의결',
    publisher: '금융위원회',
    date: '2026-06-17',
    url: 'https://www.fsc.go.kr/no010101/87126',
    kind: 'regulatory',
    note: '상호금융 PF 총대출 20%, 부동산·건설·PF 합산 50%; 새마을금고 신용공여한도 건설·부동산 각 30%/합산 50%의 비교 기준',
  },
  {
    id: 'korea-kr-deposit-limit-2025',
    title: '오는 9월 1일부터 예금보호 한도 5000만 원→1억 원으로 상향',
    publisher: '대한민국 정책브리핑(korea.kr) · 금융위원회',
    date: '2025-05-15',
    url: 'https://www.korea.kr/news/policyNewsView.do?newsId=148943235',
    kind: 'regulatory',
    note: '2025.9.1 시행, 24년 만 상향; 새마을금고 등 상호금융도 개별법 개정으로 동일 적용. 디브리핑 전용(사후정보)',
  },

  // ───────── 사후 출처 (디브리핑·교훈 전용 — 턴 텍스트에서 인용 금지) ─────────
  {
    id: 'kfcc-innovation-plan-2023-11-14',
    title: '새마을금고 경영혁신안 (경영대표이사 신설, 회장 단임제, 부실금고 합병)',
    publisher: '새마을금고 경영혁신자문위원회 · 행정안전부',
    date: '2023-11-14',
    kind: 'regulatory',
    note: '지배구조 개편(회장 단임제·경영대표이사), 부실금고 2024.1Q까지 합병, 건설·부동산 대출 한도. URL 미확인',
  },
  {
    id: 'mois-fsc-mou-2024-02-05',
    title: '새마을금고 건전성 감독 협력 강화를 위한 행정안전부–금융위원회 업무협약(MOU)',
    publisher: '행정안전부 · 금융위원회',
    date: '2024-02-05',
    kind: 'regulatory',
    note: '금융위·금감원의 검사·감독 협력 제도화. 디브리핑 전용(사후정보)',
  },
  {
    id: 'bok-rp-counterparty-2024-08',
    title: '한국은행 공개시장운영 대상기관 선정 — 새마을금고중앙회 등 비은행 포함',
    publisher: '한국은행',
    date: '2024-08',
    kind: 'regulatory',
    note: '2024.8 새마을금고중앙회의 한은 RP 대상기관 편입(최종대부자 접근 경로 확보). 디브리핑 전용(사후정보). URL 미확인',
  },

  // ───────── 비교 사례·원칙 ─────────
  {
    id: 'fsc-69871',
    title: '부산저축은행·대전저축은행의 영업정지와 관련한 정부 입장',
    publisher: '금융위원회',
    date: '2011-02-17',
    url: 'https://www.fsc.go.kr/no010101/69871',
    kind: 'regulatory',
    note: '"과도한 예금인출 없는 한 상반기 추가 정지 없을 것" 조건부 발언; 2/19 4개 추가 정지로 이틀 만에 붕괴; 유동성 백스톱 6조',
  },
  {
    id: 'fsc-69869',
    title:
      '(부산)부산상호저축은행 및 (대전)대전상호저축은행에 대한 부실금융기관 결정 및 영업정지 조치 부과',
    publisher: '금융위원회',
    date: '2011-02-17',
    url: 'https://www.fsc.go.kr/no010101/69869',
    kind: 'regulatory',
    note: '영업정지 시 5천만원 초과 예금 손실(부산 5,132억·2.3만명)의 원형',
  },
  {
    id: 'fsc-71188',
    title: '저축은행 구조조정 성과 평가 및 향후 정책 방향',
    publisher: '금융위원회',
    date: '2014-07-03',
    url: 'https://www.fsc.go.kr/no010101/71188',
    kind: 'regulatory',
    note: '2011~14 저축은행 구조조정 사후평가: P&A·가교 정리, 특별계정 27.2조, 지배구조·PF 쏠림 교훈',
  },
  {
    id: 'audit-savings-bank-2011',
    title: '서민금융 지원시스템 운영 및 감독실태 (감사결과)',
    publisher: '감사원',
    date: '2011-03-17',
    kind: 'regulatory',
    note: '저축은행 PF 부실·감독 실태; 감독 전문성·검사 미적발의 선례',
  },
  {
    id: 'bcbs-144',
    title: 'Principles for Sound Liquidity Risk Management and Supervision',
    publisher: 'Basel Committee on Banking Supervision (BCBS)',
    date: '2008-09',
    url: 'https://www.bis.org/publ/bcbs144.pdf',
    pages: 'Principle 11, ¶110~117 (CFP)',
    kind: 'regulatory',
    note: '비상자금조달계획: 조달 수단은 사전에 확보·테스트되어야 하며 커뮤니케이션 계획을 포함',
  },
  {
    id: 'fsb-depositor-behaviour-2024',
    title:
      'Depositor Behaviour and Interest Rate and Liquidity Risks in the Financial System: Lessons from the March 2023 banking turmoil',
    publisher: 'Financial Stability Board (FSB)',
    date: '2024-10-23',
    url: 'https://www.fsb.org/2024/10/depositor-behaviour-and-interest-rate-and-liquidity-risks-in-the-financial-system-lessons-from-the-march-2023-banking-turmoil/',
    kind: 'regulatory',
    note: '검증 가능한 정보 공개·일관된 메시지가 런을 늦춤; 소셜미디어가 전파 속도를 압축',
  },
  {
    id: 'fdic-frc-supervision-2023',
    title: "FDIC's Supervision of First Republic Bank",
    publisher: 'Federal Deposit Insurance Corporation (FDIC)',
    date: '2023-09-08',
    kind: 'regulatory',
    note: '유동성 지원은 시간을 벌 뿐 근본 문제(자본·자산 건전성)를 해결하지 못함. URL 미확인',
  },

  // ───────── 언론(타임스탬프·인용·2차 수치 전용) ─────────
  {
    id: 'press-kfcc-bond-sale-2023-07-06',
    title: '새마을금고중앙회, 채권 1.6조원 매도 — 국고채 금리 상승 압력 (종합)',
    publisher: '연합뉴스 외 복수 언론',
    date: '2023-07-06',
    kind: 'press',
    note: '7/6 중앙회 채권 매도 약 1.6조(2차 출처, [VERIFY]); 채권시장 충격 보도',
  },
  {
    id: 'press-bank-rp-2023-07-11',
    title: '5대 은행·산업은행·기업은행, 새마을금고 국고채·통안채 RP 매입 6조원대',
    publisher: '연합뉴스 외 복수 언론',
    date: '2023-07-11',
    kind: 'press',
    note: '7/10~11 은행 7곳 RP 매입 6~6.2조(국고채·통안채 담보); 금융위 확인 보도',
  },
  {
    id: 'press-mg-outflow-2023-07-17',
    title:
      '새마을금고 예금 이탈 일 6,000~7,000억원으로 둔화 — 건설·부동산 대출 56.4조 연체율 9.23%',
    publisher: '연합뉴스 외 복수 언론 (국회 제출 자료 인용)',
    date: '2023-07-17',
    kind: 'press',
    note: '7/17 일 인출 6,000~7,000억, 건설·부동산 대출 56.4조(연체 9.23%), 관리형토지신탁 15.5조; "7~8월 17조 인출"은 2차 출처 [VERIFY]',
  },
  {
    id: 'investchosun-audit-2024-02',
    title: '새마을금고, 감사원 감사 2013년 이후 없었다',
    publisher: 'investchosun',
    date: '2024-02',
    kind: 'press',
    note: '감사원 미감사 보도 — 감독 사각지대 교훈(디브리핑 전용)',
  },
]
