/**
 * FactLedger — `initialState`의 모든 숫자 리프와 보정 앵커를 출처에 연결한다
 * (docs/authoring-guide.md §4.2).
 *
 * tag
 *  - (없음)     1차 출처로 확인된 값
 *  - `VERIFY`   아직 1차 출처로 확인되지 않은 값. **해소 문서를 note에 반드시 적는다.**
 *  - `STYLIZED` 의도적으로 반올림·단순화한 합성 기관의 값
 *  - `CAL`      출처가 아니라 보정 규칙·앵커에서 도출한 값 (calibration.md에 산식)
 *
 * 경로 규약: `institution.` / `market.` / `confidence.` / `counters.` 는 **T0 진입 직전(1998-08-14
 * 종가)의 초기 상태**를 가리키므로 값이 초기 상태와 정확히 일치해야 한다. 그 밖의 일자 관측·이벤트
 * 수치·체크포인트 목표는 `anchor.*` 경로에 둔다.
 */
export interface FactRow {
  path: string
  value: number
  unit: string
  asOf: string
  knownAt?: string
  sourceId: string
  tag?: 'VERIFY' | 'STYLIZED' | 'CAL'
  note?: string
}

const D0814 = '1998-08-14'
const T0 = '1998-08-17T08:00:00-04:00'

export const LTCM_FACTS: FactRow[] = [
  // ══════════════════════════ 기관: 자본·유동성 ══════════════════════════
  {
    path: 'institution.firm.capital',
    value: 9,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'STYLIZED',
    note: '합성 딜러의 프라임브로커리지·파생 부문 배정 자본. PWG는 1998년 말 5대 투자은행의 총자산을 $154B~$318B, 평균 레버리지 27:1로 적는다 — 부문 자본 $9B는 그 범위의 대형 딜러를 양식화한 값이며 특정 회사의 공시가 아니다.',
  },
  {
    path: 'institution.firm.liquidityPool',
    value: 6.5,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'STYLIZED',
    note: '출자·담보 납입에 쓸 수 있는 즉시 가용 자금. 컨소시엄 분담액($300M 안팎)의 20배 규모로 두어 출자 자체가 유동성 제약이 되지 않게 했다 — 이 시나리오의 제약은 자본과 정보이지 유동성이 아니다.',
  },
  {
    path: 'institution.firm.realizedLoss',
    value: 0,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
    note: '시작 시점 실현손실 0.',
  },

  // ══════════════════════════ 기관: LTCM 익스포저(상품군별 총명목) ══════════════════════════
  {
    path: 'institution.clients.0.positions.0.notional',
    value: 42,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
    note: '스왑 스프레드 수렴. PWG: 8월말 스왑 계약 명목 >$750B. 우리 몫을 5.6%로 두었다(96/1,400 = 6.9%의 상품군 배분).',
  },
  {
    path: 'institution.clients.0.positions.0.dailyVolPct',
    value: 0.0001,
    unit: 'fraction',
    asOf: D0814,
    sourceId: 'jorion-2000-ltcm',
    tag: 'CAL',
    note: '명목 대비 일간 σ. 10년 스왑 스프레드 1bp ≈ 명목의 0.08% → 일간 σ 1.25bp 가정을 8/14 기준으로 환산(volMultiplier 1.0).',
  },
  {
    path: 'institution.clients.0.positions.0.advNotional',
    value: 21,
    unit: '$B/day',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: '참여율 20% 가정에서 청산 소요 10영업일이 되도록 역산. CGFS는 1998년 가을 국채·스왑 시장의 호가 스프레드 확대와 유동성 고갈을 기록한다.',
  },
  {
    path: 'institution.clients.0.positions.1.notional',
    value: 26,
    unit: '$B',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: '미 국채 온·오프더런 베이시스. CGFS Chart 8이 이 거래의 스프레드 계열이다.',
  },
  {
    path: 'institution.clients.0.positions.1.dailyVolPct',
    value: 0.00009,
    unit: 'fraction',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
  },
  {
    path: 'institution.clients.0.positions.1.advNotional',
    value: 18,
    unit: '$B/day',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: '청산 소요 7.2영업일.',
  },
  {
    path: 'institution.clients.0.positions.2.notional',
    value: 14,
    unit: '$B',
    asOf: D0814,
    sourceId: 'frbny-mcdonough-1998-10-01',
    tag: 'CAL',
    note: '주가지수 변동성 매도. McDonough: "they took on significant positions in equity markets, through both swap and options contracts."',
  },
  {
    path: 'institution.clients.0.positions.2.dailyVolPct',
    value: 0.00032,
    unit: 'fraction',
    asOf: D0814,
    sourceId: 'cboe-vix-1998',
    tag: 'CAL',
    note: '변동성 포지션은 명목 대비 변동이 크다. VIX 34.34(8/14) 기준.',
  },
  {
    path: 'institution.clients.0.positions.2.advNotional',
    value: 6,
    unit: '$B/day',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: '청산 소요 11.7영업일 — 집중도 경고선(10일)을 처음 넘는 포지션.',
  },
  {
    path: 'institution.clients.0.positions.3.notional',
    value: 9,
    unit: '$B',
    asOf: D0814,
    sourceId: 'frbny-mcdonough-1998-10-01',
    tag: 'CAL',
    note: '신흥국 국채 베이시스. 8/17 러시아 모라토리엄의 직격 대상.',
  },
  {
    path: 'institution.clients.0.positions.3.dailyVolPct',
    value: 0.00052,
    unit: 'fraction',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
  },
  {
    path: 'institution.clients.0.positions.3.advNotional',
    value: 3,
    unit: '$B/day',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: '청산 소요 15영업일 — 가장 팔기 어려운 포지션.',
  },
  {
    path: 'institution.clients.0.positions.4.notional',
    value: 5,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
    note: '합병차익 주식 스왑.',
  },
  {
    path: 'institution.clients.0.positions.4.dailyVolPct',
    value: 0.00035,
    unit: 'fraction',
    asOf: D0814,
    sourceId: 'cboe-vix-1998',
    tag: 'CAL',
  },
  {
    path: 'institution.clients.0.positions.4.advNotional',
    value: 2.5,
    unit: '$B/day',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: '청산 소요 10영업일.',
  },
  {
    path: 'institution.clients.0.marginPosted',
    value: 0,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
    note: '8/14 기준 순대체원가가 0이므로 예치 담보도 0. PWG: "Counterparties\' current credit exposures were in most cases covered by collateral" — 즉 담보는 **현재 대체원가만** 덮었다.',
  },
  {
    path: 'institution.clients.0.marginPct',
    value: 0,
    unit: 'fraction',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    note: '초기증거금 0. PWG: "Competitive pressures, however generally led to banks\' reducing, or eliminating such haircuts, and thus sometimes banks have provided 100% financing."',
  },
  {
    path: 'institution.clients.0.creditLimit',
    value: 120,
    unit: '$B',
    asOf: D0814,
    sourceId: 'bcbs-45',
    tag: 'STYLIZED',
    note: '총명목 한도. BCBS 45는 한도가 심층 신용분석 없이 설정·상향되었음을 지적한다.',
  },
  {
    path: 'institution.clients.0.otherPbCount',
    value: 8,
    unit: 'count',
    asOf: D0814,
    sourceId: 'gao-ggd-00-67r',
    tag: 'CAL',
    note: '**우리가 파악하고 있는** LTCM의 다른 주요 거래상대 수. 실제는 GAO 기준 "over 75 creditors and counterparties"(PWG: 레포 약 75곳, OTC 파생 약 50곳)이며, 이 격차 자체가 시나리오의 학습 대상이다.',
  },
  {
    path: 'institution.marginPolicy.staticMarginPct',
    value: 0,
    unit: '%',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    note: '초기증거금 미징구 관행.',
  },

  // ══════════════════════════ 기관: custom 지표 ══════════════════════════
  {
    path: 'institution.custom.ltcmCapitalB',
    value: 4.1,
    unit: '$B',
    asOf: '1998-07-31',
    knownAt: T0,
    sourceId: 'pwg-hedge-funds-1999',
    note: '"On July 31, 1998, the LTCM Fund held $4.1 billion in capital, down about fifteen percent from the beginning of the year."',
  },
  {
    path: 'institution.custom.ltcmLiquidityB',
    value: 1.6,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
    note: '담보 납입에 쓸 수 있는 LTCM의 잔여 현금(우리 추정). PWG는 "Despite its losses, LTCM was able to meet every margin and collateral call on a timely basis"와 "By September 21, the LTCM Fund\'s liquidity situation was bleak"만 적고 금액을 주지 않는다 — 게임은 8/14 $1.6B에서 시작해 재산정 라운드마다 줄어들고, 턴 진입 시 문서화된 자본 경로에 맞추어 다시 세워진다(calibration.md §3.2).',
  },
  {
    path: 'institution.custom.ltcmPostMoneyB',
    value: 0,
    unit: '$B',
    asOf: D0814,
    sourceId: 'gao-ggd-00-67r',
    tag: 'CAL',
    note: '컨소시엄 인수 후 순자산. 9/23 이전에는 0.',
  },
  {
    path: 'institution.custom.ltcmAssetsB',
    value: 129,
    unit: '$B',
    asOf: '1997-12-31',
    knownAt: T0,
    sourceId: 'pwg-hedge-funds-1999',
    note: '"LTCM, with total assets of $129 billion at the end of 1997". 8/31에는 "over $125 billion".',
  },
  {
    path: 'institution.custom.ltcmNotionalB',
    value: 1400,
    unit: '$B',
    asOf: '1998-08-31',
    knownAt: '1998-09-20',
    sourceId: 'pwg-hedge-funds-1999',
    note: "선물 >$500B + 스왑 >$750B + 옵션·기타 OTC >$150B ≈ $1.4T. **널리 인용되는 $1.25T는 PWG 수치가 아니다** — 이 시나리오는 $1.4T만 쓴다. (별도로 PWG는 OTC 파생 명목만 '97말 $1.3T, '98말 $1.5T로 적는다.) 초기 상태에 넣은 것은 표시용이며, 딜러가 실제로 이 총액을 알게 되는 것은 9/20 연준 실사 이후다.",
  },
  {
    path: 'institution.custom.ourNotionalB',
    value: 96,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
    note: 'positions 합계(42+26+14+9+5). LTCM 전체 명목의 6.9% — 코어그룹 딜러의 몫으로 양식화.',
  },
  {
    path: 'institution.custom.replacementCostB',
    value: 0,
    unit: '$B',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: 'ourPv01B × (수렴지수 − 100). 8/14 기준 0.',
  },
  {
    path: 'institution.custom.settledValueB',
    value: 0,
    unit: '$B',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
  },
  {
    path: 'institution.custom.netExposureB',
    value: 0,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
    note: 'max(0, 대체원가 − 담보).',
  },
  {
    path: 'institution.custom.closeoutLossB',
    value: 0.18,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
    note: '자사 리스크 시스템이 추정하는 디폴트 시 청산 손실 = 순익스포저 + 청산 VaR × 군집계수. 군집계수는 **아는 거래상대 수**로 계산되므로 실제보다 작다. 목표 범위는 PWG "potential losses to some firms amounting to $300 million to $500 million each".',
  },
  {
    path: 'institution.custom.crowdFactorEst',
    value: 1.35,
    unit: 'x',
    asOf: D0814,
    sourceId: 'frbny-mcdonough-1998-10-01',
    tag: 'CAL',
    note: '1 + 0.05 × (아는 거래상대 8곳 − 1). 실제 값은 상위 17개 카운터파티 기준 1.80이다.',
  },
  {
    path: 'institution.custom.ourPv01B',
    value: 0.01,
    unit: '$B/idx',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: '수렴지수 1포인트당 대체원가 $10M. 9/21 지수 152 → 대체원가 $520M으로 PWG 범위 상단에 맞춘 값.',
  },
  {
    path: 'institution.custom.knownCounterpartyCount',
    value: 8,
    unit: 'count',
    asOf: D0814,
    sourceId: 'gao-ggd-00-67r',
    tag: 'CAL',
    note: 'otherPbCount 미러(지표 표시용).',
  },
  {
    path: 'institution.custom.trueCounterpartyCount',
    value: 0,
    unit: 'count',
    asOf: D0814,
    sourceId: 'gao-ggd-00-67r',
    tag: 'CAL',
    note: '0 = 아직 모름. 정보 교환 또는 9/20 연준 실사 보고 이후에만 채워진다(75).',
  },
  {
    path: 'institution.custom.aggregateLeverageKnown',
    value: 0,
    unit: 'flag',
    asOf: D0814,
    sourceId: 'greenspan-testimony-1998-10-01',
    tag: 'CAL',
    note: 'Greenspan: "creditors as a whole most likely underestimated the size and scope of the market bets that LTCM was undertaking."',
  },
  {
    path: 'institution.custom.peerCooperation',
    value: 50,
    unit: 'index',
    asOf: D0814,
    sourceId: 'frbny-mcdonough-1998-10-01',
    tag: 'CAL',
    note: '타 딜러 협조도 0~90. 50 = 위기 전 평시. 산식과 계수는 calibration.md §5.',
  },
  {
    path: 'institution.custom.peerJoinCount',
    value: 0,
    unit: 'count',
    asOf: D0814,
    sourceId: 'gao-ggd-00-67r',
    tag: 'CAL',
  },
  {
    path: 'institution.custom.consortiumTotalM',
    value: 0,
    unit: '$M',
    asOf: D0814,
    sourceId: 'fed-history-ltcm',
    tag: 'CAL',
  },
  {
    path: 'institution.custom.pledgedCapitalB',
    value: 0,
    unit: '$B',
    asOf: D0814,
    sourceId: 'fed-history-ltcm',
    tag: 'CAL',
  },
  {
    path: 'institution.custom.ownConvergenceB',
    value: 18,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'STYLIZED',
    note: '자사 자기매매 수렴 북. PWG: "the LTCM Fund\'s exposure to certain market risks was several times greater than that of the trading portfolios typically held by major dealer firms" — 딜러의 자기 북을 LTCM 익스포저의 1/5 규모로 양식화했다.',
  },
  {
    path: 'institution.custom.ownPv01B',
    value: 0.004,
    unit: '$B/idx',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: '자사 북의 수렴지수 1포인트당 손익 $4M.',
  },
  {
    path: 'institution.custom.ownConvergencePnlB',
    value: 0,
    unit: '$B',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
  },
  {
    path: 'institution.custom.ownMarkIdx',
    value: 100,
    unit: 'index',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: '자사 북을 마지막으로 마크한 수렴지수. 증분 마크의 기준점이므로 북을 줄여도 이미 확정된 손실이 되돌려지지 않는다.',
  },
  {
    path: 'institution.custom.volMultiplier',
    value: 1,
    unit: 'x',
    asOf: D0814,
    sourceId: 'cboe-vix-1998',
    tag: 'CAL',
    note: '8/14 VIX 34.34 = 1.0 기준. 턴마다 그날 VIX 종가에 맞춰 세운다.',
  },
  {
    path: 'institution.custom.unwoundFraction',
    value: 0,
    unit: 'fraction',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
  },
  {
    path: 'institution.custom.bookScale',
    value: 1,
    unit: 'x',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
  },
  {
    path: 'institution.custom.marginCalledB',
    value: 0,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
  },
  {
    path: 'institution.custom.marginPaidB',
    value: 0,
    unit: '$B',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
  },

  // ══════════════════════════ 시장(1998-08-14 종가) ══════════════════════════
  {
    path: 'market.policyRateBp',
    value: 550,
    unit: 'bp',
    asOf: D0814,
    sourceId: 'fed-pr-1998-10-15',
    note: 'FF 목표 5.50%(1997-03-25 이후). 9/29 5.25%, 10/15 5.00%, 11/17 4.75%로 내려간다.',
  },
  {
    path: 'market.govt2yBp',
    value: 534,
    unit: 'bp',
    asOf: D0814,
    sourceId: 'frb-h15-treasury-1998',
    note: 'DGS2 5.34%.',
  },
  {
    path: 'market.govt10yBp',
    value: 540,
    unit: 'bp',
    asOf: D0814,
    sourceId: 'frb-h15-treasury-1998',
    note: 'DGS10 5.40%.',
  },
  {
    path: 'market.govt30yBp',
    value: 555,
    unit: 'bp',
    asOf: D0814,
    sourceId: 'frb-h15-treasury-1998',
    note: 'DGS30 5.55%.',
  },
  {
    path: 'market.creditSpreadIgBp',
    value: 174,
    unit: 'bp',
    asOf: D0814,
    sourceId: 'fred-moodys-baa-aaa-1998',
    note: '무디스 Baa(7.14%) − 10년 국채(5.40%). ICE BofA IG OAS는 익명 접근에서 최근 3년만 열리므로(docs/research/data-sources-global.md §2) 1998년은 이 전 기간 공개 계열을 대리지표로 쓴다. Baa는 IG 중 최저 등급이고 듀레이션이 길어 OAS의 상한을 감싼다.',
  },
  {
    path: 'market.creditSpreadHyBp',
    value: 374,
    unit: 'bp',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: '투기등급 스프레드. **관측된 일별 종가가 아니라 CGFS Papers No 12 Table A1(p.50) "US speculative-grade bond"의 하위기간 평균에서 도출한 값**이다. 앵커: 1 Jan~3 Jul 평균 332bp + 6 Jul~14 Aug 변화 +42bp = **374bp**(6 Jul~14 Aug 평균, 창의 종료일이 시나리오 기준일 8/14와 같다). 교차 확인 — 같은 보고서 Table A2: 1998년 최저 307bp(3/30) · 최고 687bp(10/19). 종전 값 520bp는 **다음 하위기간(17 Aug~22 Sep) 평균**(374+146)이어서 러시아 모라토리엄 이전 기준일에 쓸 수 없었다. 8/14 당일 종가를 확정하려면 무료 FRED API 키로 `api.stlouisfed.org/fred/series/observations?series_id=BAMLH0A0HYM2`(1996-12-31 개시)를 호출해야 한다 — 익명 CSV는 3년 창만 반환한다.',
  },
  {
    path: 'market.fundingStressBp',
    value: 79,
    unit: 'bp',
    asOf: D0814,
    sourceId: 'fred-tedrate-1998',
    note: 'TED 0.79%.',
  },
  {
    path: 'market.equityIndex',
    value: 100,
    unit: 'index',
    asOf: D0814,
    sourceId: 'cboe-vix-1998',
    tag: 'STYLIZED',
    note: 'S&P 500을 8/14 = 100으로 지수화.',
  },
  {
    path: 'market.volIndex',
    value: 34.34,
    unit: 'index',
    asOf: D0814,
    sourceId: 'cboe-vix-1998',
    note: 'VIX 종가 34.34.',
  },
  {
    path: 'market.fxUsdLocal',
    value: 1,
    unit: 'fx',
    asOf: D0814,
    sourceId: 'frb-h15-treasury-1998',
    tag: 'STYLIZED',
    note: '기준 통화가 USD이므로 1.',
  },
  {
    path: 'market.ownStock',
    value: 100,
    unit: 'index',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'STYLIZED',
    note: '합성 기관의 주가를 8/14 = 100으로 지수화. 실제 개별 딜러 주가를 쓰지 않는다.',
  },
  {
    path: 'market.ownCdsBp',
    value: 0,
    unit: 'bp',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'STYLIZED',
    note: '1998년에는 단일 기업 CDS 시장이 형성되기 전이다. 0으로 두고 지표에 쓰지 않는다.',
  },
  {
    path: 'market.custom.tedBp',
    value: 79,
    unit: 'bp',
    asOf: D0814,
    sourceId: 'fred-tedrate-1998',
  },
  {
    path: 'market.custom.baaAaaBp',
    value: 62,
    unit: 'bp',
    asOf: D0814,
    sourceId: 'fred-moodys-baa-aaa-1998',
    note: 'Baa(7.14%) − Aaa(6.52%). **전 기간 공개되는 일별 계열**이므로 수렴거래 스프레드의 검증 가능한 대리지표다: 8/17 61 → 9/18 70 → 9/23 70 → 10/15 81bp.',
  },
  {
    path: 'market.custom.convergenceIdx',
    value: 100,
    unit: 'index',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'STYLIZED',
    note: '수렴 스프레드 종합지수 = 0.45×(10년 스왑 스프레드) + 0.25×(10년 온·오프더런) + 0.30×(Baa−Aaa), 각 계열을 8/14 = 100으로 재기준화한 가중합. 형상은 CGFS Chart 8·12, 검증 가능한 앵커는 Baa−Aaa다(calibration.md §2).',
  },
  {
    path: 'market.custom.swapSpread10yBp',
    value: 57,
    unit: 'bp',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: '10년 국채 대비 달러 스왑 스프레드. **관측된 일별 종가가 아니라 CGFS Papers No 12 Table A1(p.50) "US 10-year US$ swap"의 하위기간 평균에서 도출한 값**이다. 앵커: 1 Jan~3 Jul 평균 51bp + 6 Jul~14 Aug 변화 +6bp = **57bp**(창의 종료일이 기준일 8/14와 같다). 이후 앵커는 17 Aug~22 Sep 평균 77bp(+20), 23 Sep~15 Oct 평균 88bp(+11)이다. 교차 확인 — 같은 보고서 Table A2: 1998년 최저 44bp(2/11) · 최고 97bp(10/14). 종전 값 40bp는 Chart 12의 형상에서 읽은 것인데 **같은 보고서가 적은 1998년 최저치(44bp)보다도 낮아 성립할 수 없었다**. 8/14 당일 종가를 확정하려면 CGFS Chart 12의 원 계열(BIS 데이터 부록) 또는 Bloomberg USSW10 − USGG10YR 일별 다운로드가 필요하다. FRED의 스왑 계열(DSWP10)은 2000-07-03에 시작하여 1998년을 덮지 못한다.',
  },
  {
    path: 'market.custom.onOffRun10yBp',
    value: 9,
    unit: 'bp',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: '10년 국채 오프더런−온더런 유동성 스프레드. **관측된 일별 종가가 아니라 CGFS Papers No 12 Table A6(p.54) "Average liquidity spreads for 10-year government bonds" 미국 행의 하위기간 평균**이다. 앵커: 1 Jan~3 Jul 평균 9bp, 6 Jul~14 Aug 변화 −0bp → **9bp**(창의 종료일이 기준일 8/14와 같다). 종전 값 7bp는 Chart 8의 형상에서 읽은 근사였다. **주의 — 같은 보고서 안의 불일치**: Table A6 미국 행의 이후 변화는 −2(17 Aug~22 Sep) · −1(23 Sep~15 Oct) · −2(16 Oct~31 Dec)로 **하락**을 적지만, 같은 보고서 Chart 8(Off-the-Run U.S. Treasury Spreads over On-the-Run, 일별, 축 −12~+30bp)은 LTCM 구간의 급등을 보인다. 하위기간 평균과 일별 급등의 차이로 보이나 확정하지 못했다. **해소 문서**: CGFS Chart 8의 원 계열(BIS 데이터 부록), 또는 GovPX/CRSP 1998년 개별 국채 호가 데이터로 재구성. docs/research/ltcm-1998.md 의 "스왑/온오프더런 스프레드 시계열" 항목과 같은 건이다.',
  },

  // ══════════════════════════ 신뢰지수 ══════════════════════════
  {
    path: 'confidence.index',
    value: 72,
    unit: 'index',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
    note: 'S0 평온(≥70). 8/14는 아직 러시아 모라토리엄 전이다.',
  },
  {
    path: 'confidence.depositors',
    value: 70,
    unit: 'index',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
  },
  {
    path: 'confidence.counterparties',
    value: 70,
    unit: 'index',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
  },
  {
    path: 'confidence.regulators',
    value: 75,
    unit: 'index',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
  },
  {
    path: 'confidence.investors',
    value: 72,
    unit: 'index',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
  },
  {
    path: 'confidence.media',
    value: 75,
    unit: 'index',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
  },
  {
    path: 'confidence.board',
    value: 78,
    unit: 'index',
    asOf: D0814,
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'CAL',
  },

  // ══════════════════════════ 카운터 ══════════════════════════
  {
    path: 'counters.consortiumPledgeM',
    value: 0,
    unit: '$M',
    asOf: D0814,
    sourceId: 'fed-history-ltcm',
    tag: 'CAL',
    note: '대화(T5)에서 부르는 출자 제시액. 0 = 아직 제시 없음.',
  },
  {
    path: 'counters.marginCallM',
    value: 0,
    unit: '$M',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
    note: '대화(T3)에서 요구하는 당일 추가 담보액.',
  },
  {
    path: 'counters.infoShared',
    value: 0,
    unit: 'count',
    asOf: D0814,
    sourceId: 'gao-ggd-00-67r',
    tag: 'CAL',
  },
  {
    path: 'counters.remarginRounds',
    value: 0,
    unit: 'count',
    asOf: D0814,
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
  },

  // ══════════════════════════ 앵커: LTCM 수익률·자본 경로 ══════════════════════════
  {
    path: 'anchor.ltcm.return1994Pct',
    value: 20,
    unit: '%',
    asOf: '1994-12-31',
    sourceId: 'fed-history-ltcm',
  },
  {
    path: 'anchor.ltcm.return1995Pct',
    value: 43,
    unit: '%',
    asOf: '1995-12-31',
    sourceId: 'fed-history-ltcm',
  },
  {
    path: 'anchor.ltcm.return1996Pct',
    value: 41,
    unit: '%',
    asOf: '1996-12-31',
    sourceId: 'fed-history-ltcm',
  },
  {
    path: 'anchor.ltcm.return1997Pct',
    value: 17,
    unit: '%',
    asOf: '1997-12-31',
    sourceId: 'fed-history-ltcm',
  },
  {
    path: 'anchor.ltcm.capitalReturnedB',
    value: 2.7,
    unit: '$B',
    asOf: '1997-12-31',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"returned approximately $2.7 billion in capital to its investors, reducing the capital base of the fund by about 36 percent to $4.8 billion."',
  },
  {
    path: 'anchor.ltcm.capital1997B',
    value: 4.8,
    unit: '$B',
    asOf: '1997-12-31',
    sourceId: 'pwg-hedge-funds-1999',
  },
  {
    path: 'anchor.ltcm.leverage1997',
    value: 28,
    unit: 'x',
    asOf: '1997-12-31',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"LTCM\'s balance sheet leverage was 28-to-1 at the end of 1997."',
  },
  {
    path: 'anchor.ltcm.capital0731B',
    value: 4.1,
    unit: '$B',
    asOf: '1998-07-31',
    sourceId: 'pwg-hedge-funds-1999',
  },
  {
    path: 'anchor.ltcm.augustLossB',
    value: 1.8,
    unit: '$B',
    asOf: '1998-08-31',
    knownAt: '1998-09-02',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"During the single month of August, the LTCM Fund suffered additional losses of $1.8 billion."',
  },
  {
    path: 'anchor.ltcm.augustLossPct',
    value: 44,
    unit: '%',
    asOf: '1998-08-31',
    knownAt: '1998-09-02',
    sourceId: 'fed-history-ltcm',
    note: '"The fund lost 44 percent of its value in August alone."',
  },
  {
    path: 'anchor.ltcm.ytdLossPct',
    value: 52,
    unit: '%',
    asOf: '1998-08-31',
    knownAt: '1998-09-02',
    sourceId: 'frbny-mcdonough-1998-10-01',
    note: '9/2 투자자 서한: "52 percent losses on the year through August 31."',
  },
  {
    path: 'anchor.ltcm.capital0831B',
    value: 2.3,
    unit: '$B',
    asOf: '1998-08-31',
    knownAt: '1998-09-02',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"The Fund\'s capital base was now $2.3 billion."',
  },
  {
    path: 'anchor.ltcm.assets0831B',
    value: 125,
    unit: '$B',
    asOf: '1998-08-31',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"over $125 billion in assets" → $4.8B 기준으로도 레버리지 25:1 초과.',
  },
  {
    path: 'anchor.ltcm.leverage0831',
    value: 25,
    unit: 'x',
    asOf: '1998-08-31',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"this level of assets still implies a balance-sheet leverage ratio of more than 25-to-1."',
  },
  {
    path: 'anchor.ltcm.capital0918B',
    value: 1.5,
    unit: '$B',
    asOf: '1998-09-18',
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
    note: '8/31 $2.3B와 9/23 $0.4B 사이의 보간. PWG는 "continuing declines in the Fund\'s capital"만 적고 일별 수치를 주지 않는다. 산식은 calibration.md §3.',
  },
  {
    path: 'anchor.ltcm.capital0921B',
    value: 0.9,
    unit: '$B',
    asOf: '1998-09-21',
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
    note: '같은 보간. "By September 21, the LTCM Fund\'s liquidity situation was bleak."',
  },
  {
    path: 'anchor.ltcm.capital0922B',
    value: 0.6,
    unit: '$B',
    asOf: '1998-09-22',
    sourceId: 'pwg-hedge-funds-1999',
    tag: 'CAL',
    note: '같은 보간. 널리 인용되는 "9월 하순 자본 $600M"과 일치하지만, 1차 사후평가에는 이 수치가 없다.',
  },
  {
    path: 'anchor.ltcm.capital0923B',
    value: 0.4,
    unit: '$B',
    asOf: '1998-09-23',
    sourceId: 'gao-ggd-00-67r',
    tag: 'CAL',
    note: '**역산**: GAO는 출자 $3.6B가 "90 percent of the net asset value of the fund on that date"라고 적는다. 출자 후 순자산 ≈ $3.625B/0.9 = $4.03B이고 원소유자 몫 10% ≈ $0.40B이므로, 출자 직전 자본은 ≈$0.4B이다. Greenspan도 원소유자 지분을 "one tenth"로 확인한다.',
  },
  {
    path: 'anchor.ltcm.investorCount',
    value: 100,
    unit: 'count',
    asOf: '1998-09',
    sourceId: 'gao-ggd-00-67r',
    note: '"over 100 equity investors."',
  },
  {
    path: 'anchor.ltcm.counterpartyCount',
    value: 75,
    unit: 'count',
    asOf: '1998-09',
    sourceId: 'frbny-mcdonough-1998-10-01',
    note: 'McDonough "more than 75 counterparties"; GAO "over 75 creditors and counterparties"; PWG는 레포 약 75곳·OTC 파생 약 50곳으로 나누어 적는다.',
  },
  {
    path: 'anchor.ltcm.repoCounterparties',
    value: 75,
    unit: 'count',
    asOf: '1998-08',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"repo and reverse repo transactions ... with approximately seventy-five counterparties."',
  },
  {
    path: 'anchor.ltcm.otcCounterparties',
    value: 50,
    unit: 'count',
    asOf: '1998-08',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"engaged in OTC derivative transactions with about fifty counterparties."',
  },

  // ══════════════════════════ 앵커: 명목·순익스포저 ══════════════════════════
  {
    path: 'anchor.notional.futuresB',
    value: 500,
    unit: '$B',
    asOf: '1998-08-31',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"contracts on futures exchanges exceeded $500 billion" (하한).',
  },
  {
    path: 'anchor.notional.swapsB',
    value: 750,
    unit: '$B',
    asOf: '1998-08-31',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"swaps contracts more than $750 billion" (하한).',
  },
  {
    path: 'anchor.notional.optionsB',
    value: 150,
    unit: '$B',
    asOf: '1998-08-31',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"options and other OTC derivatives over $150 billion" (하한).',
  },
  {
    path: 'anchor.notional.totalB',
    value: 1400,
    unit: '$B',
    asOf: '1998-08-31',
    sourceId: 'pwg-hedge-funds-1999',
    note: '세 하한의 합 ≈$1.4T. 흔히 인용되는 $1.25T는 PWG 수치가 아니다(docs/research/README.md 정정 목록).',
  },
  {
    path: 'anchor.notional.otcOnly1997B',
    value: 1300,
    unit: '$B',
    asOf: '1997-12-31',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"The notional amount of LTCM\'s total OTC derivatives position was $1.3 trillion at the end of 1997" — 거래소 선물을 뺀 수치이므로 $1.4T와 같은 기준이 아니다.',
  },
  {
    path: 'anchor.notional.otcOnly1998B',
    value: 1500,
    unit: '$B',
    asOf: '1998-12-31',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"and $1.5 trillion at the end of 1998."',
  },
  {
    path: 'anchor.exposure.top17AggregateLowB',
    value: 3,
    unit: '$B',
    asOf: '1998-09-23',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"LTCM itself estimated that its top 17 counterparties would have suffered ... potentially between $3 billion and $5 billion in aggregate."',
  },
  {
    path: 'anchor.exposure.top17AggregateHighB',
    value: 5,
    unit: '$B',
    asOf: '1998-09-23',
    sourceId: 'pwg-hedge-funds-1999',
  },
  {
    path: 'anchor.exposure.perFirmLowB',
    value: 0.3,
    unit: '$B',
    asOf: '1998-09-23',
    sourceId: 'pwg-hedge-funds-1999',
    note: '"potential losses to some firms amounting to $300 million to $500 million each." 게임의 청산손실 보정 목표 구간.',
  },
  {
    path: 'anchor.exposure.perFirmHighB',
    value: 0.5,
    unit: '$B',
    asOf: '1998-09-23',
    sourceId: 'pwg-hedge-funds-1999',
  },

  // ══════════════════════════ 앵커: 컨소시엄 ══════════════════════════
  {
    path: 'anchor.consortium.totalM',
    value: 3625,
    unit: '$M',
    asOf: '1998-09-23',
    sourceId: 'fed-history-ltcm',
    note: '"fourteen firms put up $3.625 billion in capital in exchange for 90 percent of the fund\'s ownership." GAO는 9/28 집행액을 "about $3.6 billion"으로, Greenspan은 "about $3-1/2 billion"으로 적는다.',
  },
  {
    path: 'anchor.consortium.firmCount',
    value: 14,
    unit: 'count',
    asOf: '1998-09-23',
    sourceId: 'gao-ggd-00-67r',
    note: 'Chase · Goldman Sachs · Merrill Lynch · J.P. Morgan · Morgan Stanley Dean Witter · Salomon Smith Barney(Travelers) · CSFB · Barclays · Deutsche Bank · UBS · Bankers Trust · Société Générale · Paribas · Lehman Brothers.',
  },
  {
    path: 'anchor.consortium.declinedCount',
    value: 2,
    unit: 'count',
    asOf: '1998-09-23',
    sourceId: 'gao-ggd-00-67r',
    note: '"Although Bear Stearns and Credit Agricole were included in these discussions, they declined to participate in the Consortium." McDonough도 "Two firms declined to participate."',
  },
  {
    path: 'anchor.consortium.equityStakePct',
    value: 90,
    unit: '%',
    asOf: '1998-09-23',
    sourceId: 'gao-ggd-00-67r',
  },
  {
    path: 'anchor.consortium.coreShareM',
    value: 300,
    unit: '$M',
    asOf: '1998-09-23',
    sourceId: 'frbny-mcdonough-1998-10-01',
    tag: 'CAL',
    note: 'McDonough: "with three firms contributing smaller amounts than the other eleven." 총액 $3,625M에서 소액 3사(SG $125M, Paribas $100M, Lehman $100M)를 빼면 11사 × $300M = $3,300M으로 정확히 맞는다 — 균등 분담 $300M은 이 역산이다.',
  },
  {
    path: 'anchor.consortium.smallShareSgM',
    value: 125,
    unit: '$M',
    asOf: '1998-09-23',
    sourceId: 'fed-history-ltcm',
    tag: 'CAL',
    note: '소액 3사 배분($125M + $100M + $100M = $325M)은 총액 역산과 2차 기록이 일치하는 조합이다. 1차 사후평가에는 회사별 금액표가 없다.',
  },
  {
    path: 'anchor.consortium.smallShareOtherM',
    value: 100,
    unit: '$M',
    asOf: '1998-09-23',
    sourceId: 'fed-history-ltcm',
    tag: 'CAL',
  },
  {
    path: 'anchor.consortium.minViableM',
    value: 3300,
    unit: '$M',
    asOf: '1998-09-23',
    sourceId: 'gao-ggd-00-67r',
    tag: 'CAL',
    note: '게임의 성립 최소선. 문서화된 $3,625M의 91%. 이 아래에서는 순자산의 90%를 인수하는 구조가 성립하지 않는다고 본다(calibration.md §5.3).',
  },

  // ══════════════════════════ 앵커: 일자별 시장 종가 ══════════════════════════
  {
    path: 'anchor.market.0817.govt10yBp',
    value: 540,
    unit: 'bp',
    asOf: '1998-08-17',
    sourceId: 'frb-h15-treasury-1998',
  },
  {
    path: 'anchor.market.0817.vix',
    value: 31.86,
    unit: 'index',
    asOf: '1998-08-17',
    sourceId: 'cboe-vix-1998',
  },
  {
    path: 'anchor.market.0817.igBp',
    value: 174,
    unit: 'bp',
    asOf: '1998-08-17',
    sourceId: 'fred-moodys-baa-aaa-1998',
    note: 'Baa 7.14 − 10y 5.40.',
  },
  {
    path: 'anchor.market.0902.govt10yBp',
    value: 510,
    unit: 'bp',
    asOf: '1998-09-02',
    sourceId: 'frb-h15-treasury-1998',
  },
  {
    path: 'anchor.market.0902.vix',
    value: 36.76,
    unit: 'index',
    asOf: '1998-09-02',
    sourceId: 'cboe-vix-1998',
  },
  {
    path: 'anchor.market.0902.igBp',
    value: 204,
    unit: 'bp',
    asOf: '1998-09-02',
    sourceId: 'fred-moodys-baa-aaa-1998',
    note: 'Baa 7.14 − 10y 5.10.',
  },
  {
    path: 'anchor.market.0831.vix',
    value: 44.28,
    unit: 'index',
    asOf: '1998-08-31',
    sourceId: 'cboe-vix-1998',
    note: '8월 마지막 거래일의 주식 급락일 종가.',
  },
  {
    path: 'anchor.market.0918.govt10yBp',
    value: 470,
    unit: 'bp',
    asOf: '1998-09-18',
    sourceId: 'frb-h15-treasury-1998',
  },
  {
    path: 'anchor.market.0918.vix',
    value: 38.63,
    unit: 'index',
    asOf: '1998-09-18',
    sourceId: 'cboe-vix-1998',
  },
  {
    path: 'anchor.market.0918.igBp',
    value: 237,
    unit: 'bp',
    asOf: '1998-09-18',
    sourceId: 'fred-moodys-baa-aaa-1998',
    note: 'Baa 7.07 − 10y 4.70.',
  },
  {
    path: 'anchor.market.0921.govt10yBp',
    value: 469,
    unit: 'bp',
    asOf: '1998-09-21',
    sourceId: 'frb-h15-treasury-1998',
  },
  {
    path: 'anchor.market.0921.vix',
    value: 38.58,
    unit: 'index',
    asOf: '1998-09-21',
    sourceId: 'cboe-vix-1998',
  },
  {
    path: 'anchor.market.0921.igBp',
    value: 238,
    unit: 'bp',
    asOf: '1998-09-21',
    sourceId: 'fred-moodys-baa-aaa-1998',
    note: 'Baa 7.07 − 10y 4.69.',
  },
  {
    path: 'anchor.market.0922.govt10yBp',
    value: 473,
    unit: 'bp',
    asOf: '1998-09-22',
    sourceId: 'frb-h15-treasury-1998',
  },
  {
    path: 'anchor.market.0922.vix',
    value: 36.62,
    unit: 'index',
    asOf: '1998-09-22',
    sourceId: 'cboe-vix-1998',
  },
  {
    path: 'anchor.market.0922.igBp',
    value: 235,
    unit: 'bp',
    asOf: '1998-09-22',
    sourceId: 'fred-moodys-baa-aaa-1998',
    note: 'Baa 7.08 − 10y 4.73.',
  },
  {
    path: 'anchor.market.0923.govt10yBp',
    value: 469,
    unit: 'bp',
    asOf: '1998-09-23',
    sourceId: 'frb-h15-treasury-1998',
  },
  {
    path: 'anchor.market.0923.govt2yBp',
    value: 452,
    unit: 'bp',
    asOf: '1998-09-23',
    sourceId: 'frb-h15-treasury-1998',
  },
  {
    path: 'anchor.market.0923.vix',
    value: 32.47,
    unit: 'index',
    asOf: '1998-09-23',
    sourceId: 'cboe-vix-1998',
  },
  {
    path: 'anchor.market.0923.igBp',
    value: 238,
    unit: 'bp',
    asOf: '1998-09-23',
    sourceId: 'fred-moodys-baa-aaa-1998',
    note: 'Baa 7.07 − 10y 4.69.',
  },
  {
    path: 'anchor.market.0923.tedBp',
    value: 95,
    unit: 'bp',
    asOf: '1998-09-23',
    sourceId: 'fred-tedrate-1998',
  },
  {
    path: 'anchor.market.1015.policyRateBp',
    value: 500,
    unit: 'bp',
    asOf: '1998-10-15',
    sourceId: 'fed-pr-1998-10-15',
    note: '정례 회의 밖 인하. 재할인율은 4.75%.',
  },
  {
    path: 'anchor.market.1015.igBp',
    value: 268,
    unit: 'bp',
    asOf: '1998-10-15',
    sourceId: 'fred-moodys-baa-aaa-1998',
    note: 'Baa 7.26 − 10y 4.58. 신용스프레드의 정점은 9월이 아니라 10월이었다.',
  },
  {
    path: 'anchor.market.1008.tedBp',
    value: 154,
    unit: 'bp',
    asOf: '1998-10-08',
    sourceId: 'fred-tedrate-1998',
    note: '자금시장 스트레스의 정점도 10월이다(9/23 95bp → 10/16 166bp).',
  },

  // ══════════════════════════ 앵커: 수렴지수 궤적 (STYLIZED 합성) ══════════════════════════
  {
    path: 'anchor.convergence.0817',
    value: 103,
    unit: 'index',
    asOf: '1998-08-17',
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'STYLIZED',
  },
  {
    path: 'anchor.convergence.0902',
    value: 128,
    unit: 'index',
    asOf: '1998-09-02',
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'STYLIZED',
  },
  {
    path: 'anchor.convergence.0918',
    value: 146,
    unit: 'index',
    asOf: '1998-09-18',
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'STYLIZED',
  },
  {
    path: 'anchor.convergence.0921',
    value: 152,
    unit: 'index',
    asOf: '1998-09-21',
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'STYLIZED',
  },
  {
    path: 'anchor.convergence.0922',
    value: 150,
    unit: 'index',
    asOf: '1998-09-22',
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'STYLIZED',
  },
  {
    path: 'anchor.convergence.0923',
    value: 148,
    unit: 'index',
    asOf: '1998-09-23',
    sourceId: 'cgfs-12-autumn-1998',
    tag: 'STYLIZED',
  },
]
