/**
 * FactLedger — 초기 상태의 모든 숫자 리프와 턴 외생 충격의 출처 (docs/authoring-guide.md 체크리스트 1·2).
 * tag: VERIFY (미확인, 릴리스 전 해소) · STYLIZED (선언된 단순화) · CAL (보정 규칙에서 도출; calibration.md)
 * 단위: £M (units.scale = 1e6).
 */
export interface FactRow {
  path: string
  value: number
  unit: string
  asOf: string
  knownAt?: string
  sourceId: string
  tag?: 'VERIFY' | 'STYLIZED' | 'CAL'
  note?: string
}

export const LDI_FACTS: FactRow[] = [
  // ───────────── 부채 ─────────────
  {
    path: 'institution.liabilities.pv',
    value: 5000,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'ppf-purple-book-2022',
    tag: 'STYLIZED',
    note: '합성 스킴 기술적 준비금(TP) 규모 £5bn — 계획서 부록 B-1 설계값',
  },
  {
    path: 'institution.liabilities.modDuration',
    value: 19,
    unit: 'y',
    asOf: '2022-09-22',
    sourceId: 'tpr-ldi-guidance-2023',
    tag: 'STYLIZED',
    note: '성숙 DB 스킴 부채 수정듀레이션 18~20년 범위의 중간값',
  },
  {
    path: 'institution.liabilities.discountRateBp',
    value: 380,
    unit: 'bp',
    asOf: '2022-09-22',
    sourceId: 'boe-yield-curves',
    tag: 'STYLIZED',
    note: '30년 길트 수익률 근사(할인율 = 길트 플랫 가정)',
  },
  // ───────────── 자산 ─────────────
  {
    path: 'institution.assets.cash',
    value: 150,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'ppf-purple-book-2022',
    tag: 'STYLIZED',
    note: '자산의 3% — 위기 전 스킴 현금 보유 낮음(WPC 보고: 다수 스킴 현금 미미)',
  },
  {
    path: 'institution.assets.gilts.marketValue',
    value: 600,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'ppf-purple-book-2022',
    tag: 'STYLIZED',
    note: '풀 밖 직접보유 장기 길트(담보 예비·매각 가능)',
  },
  {
    path: 'institution.assets.gilts.bookValue',
    value: 680,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'boe-yield-curves',
    tag: 'STYLIZED',
    note: '8/1 이후 +135bp 반영 전 취득가 근사(D18 × 1.35% ≈ −12%)',
  },
  {
    path: 'institution.assets.gilts.modDuration',
    value: 18,
    unit: 'y',
    asOf: '2022-09-22',
    sourceId: 'boe-yield-curves',
    tag: 'STYLIZED',
    note: '30년 만기 부근 명목 길트 수정듀레이션',
  },
  {
    path: 'institution.assets.gilts.pledgedShare',
    value: 0,
    unit: 'fraction',
    asOf: '2022-09-22',
    sourceId: 'ppf-purple-book-2022',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.assets.corporateBonds.marketValue',
    value: 1000,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'ppf-purple-book-2022',
    tag: 'STYLIZED',
    note: '영국 DB 채권 비중 약 70% 중 IG 회사채 부분',
  },
  {
    path: 'institution.assets.corporateBonds.bookValue',
    value: 1080,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'ppf-purple-book-2022',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.assets.corporateBonds.modDuration',
    value: 7,
    unit: 'y',
    asOf: '2022-09-22',
    sourceId: 'cgfs-36',
    tag: 'STYLIZED',
    note: 'GBP IG 회사채 지수 듀레이션 근사',
  },
  {
    path: 'institution.assets.corporateBonds.pledgedShare',
    value: 0,
    unit: 'fraction',
    asOf: '2022-09-22',
    sourceId: 'ppf-purple-book-2022',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.assets.equities',
    value: 1000,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'ppf-purple-book-2022',
    tag: 'STYLIZED',
    note: '주식 비중 약 20%',
  },
  {
    path: 'institution.assets.illiquid',
    value: 750,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'ppf-purple-book-2022',
    tag: 'STYLIZED',
    note: '부동산·사모·인프라 등 비유동자산 약 15%',
  },
  // ───────────── LDI 풀 ─────────────
  {
    path: 'institution.assets.ldi.exposure',
    value: 4200,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'boe-breeden-2022',
    tag: 'CAL',
    note: '헤지비율 80% × 부채 PV01 9.5 = 7.6 → 익스포저 = 7.6 × 10,000 / D18 ≈ 4,200 (calibration.md §1)',
  },
  {
    path: 'institution.assets.ldi.equity',
    value: 1400,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'boe-ldi-staff-paper-2023',
    tag: 'STYLIZED',
    note: '레버리지 3x = 4,200 / 1,400 — 계획서 부록 B-1 설계값(풀드펀드 통상 2~4x)',
  },
  {
    path: 'institution.assets.ldi.modDuration',
    value: 18,
    unit: 'y',
    asOf: '2022-09-22',
    sourceId: 'boe-yield-curves',
    tag: 'STYLIZED',
    note: '장기 길트·스왑 혼합 헤지 듀레이션',
  },
  {
    path: 'institution.assets.ldi.collateral.cash',
    value: 300,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'boe-ldi-staff-paper-2023',
    tag: 'CAL',
    note: '담보버퍼 120bp × PV01 7.56 = 907 중 현금 300 (calibration.md §1; BoE: 위기 전 풀드펀드 버퍼 100~150bp)',
  },
  {
    path: 'institution.assets.ldi.collateral.eligibleGilts',
    value: 607,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'boe-ldi-staff-paper-2023',
    tag: 'CAL',
    note: '담보버퍼 907 중 적격 길트 607',
  },
  {
    path: 'institution.assets.ldi.marginCallOutstanding',
    value: 0,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'boe-ldi-staff-paper-2023',
  },
  {
    path: 'institution.assets.ldi.repoRateBp',
    value: 230,
    unit: 'bp',
    asOf: '2022-09-22',
    sourceId: 'boe-mpc-2022-09-22',
    tag: 'STYLIZED',
    note: 'Bank Rate 2.25% + 5bp',
  },
  {
    path: 'institution.hedgeRatio',
    value: 0.8,
    unit: 'fraction',
    asOf: '2022-09-22',
    sourceId: 'boe-breeden-2022',
    tag: 'STYLIZED',
    note: '계획서 설계값; 풀 PV01 7.56 / 부채 PV01 9.5 = 0.796',
  },
  {
    path: 'institution.sponsor.contributionCapacity',
    value: 300,
    unit: '£M',
    asOf: '2022-09-22',
    sourceId: 'wpc-ldi-report-2023',
    tag: 'STYLIZED',
    note: '중간 수준 커버넌트 스폰서의 긴급 출연 여력(부채의 6%)',
  },
  // ───────────── 시장 ─────────────
  {
    path: 'market.policyRateBp',
    value: 225,
    unit: 'bp',
    asOf: '2022-09-22',
    sourceId: 'boe-mpc-2022-09-22',
  },
  {
    path: 'market.govt2yBp',
    value: 350,
    unit: 'bp',
    asOf: '2022-09-22',
    sourceId: 'boe-yield-curves',
    note: '2년 길트 9/22 종가 ≈3.5%',
  },
  {
    path: 'market.govt10yBp',
    value: 350,
    unit: 'bp',
    asOf: '2022-09-22',
    sourceId: 'boe-yield-curves',
    tag: 'STYLIZED',
    note: '10년 ≈3.5% 반올림',
  },
  {
    path: 'market.govt30yBp',
    value: 380,
    unit: 'bp',
    asOf: '2022-09-22',
    sourceId: 'boe-yield-curves',
    tag: 'STYLIZED',
    note: '30년 9/22 종가 ≈3.8% (도시에 "~3.7%"; 9/27 종가 ≈5.0~5.1%, BoE QB: 3거래일 +130bp와 정합하도록 3.80 채택)',
  },
  {
    path: 'market.creditSpreadIgBp',
    value: 210,
    unit: 'bp',
    asOf: '2022-09-22',
    sourceId: 'cgfs-36',
    tag: 'STYLIZED',
    note: 'GBP IG OAS 근사',
  },
  {
    path: 'market.creditSpreadHyBp',
    value: 650,
    unit: 'bp',
    asOf: '2022-09-22',
    sourceId: 'cgfs-36',
    tag: 'STYLIZED',
  },
  {
    path: 'market.fundingStressBp',
    value: 15,
    unit: 'bp',
    asOf: '2022-09-22',
    sourceId: 'boe-fsr-2022-12',
    tag: 'STYLIZED',
    note: 'SONIA-OIS 계열 스트레스 지표 평온 수준',
  },
  {
    path: 'market.equityIndex',
    value: 100,
    unit: 'index',
    asOf: '2022-09-22',
    sourceId: 'boe-fsr-2022-12',
    tag: 'STYLIZED',
    note: '주가지수는 시나리오 중 불변(양식화)',
  },
  {
    path: 'market.volIndex',
    value: 27,
    unit: 'index',
    asOf: '2022-09-22',
    sourceId: 'boe-fsr-2022-12',
    tag: 'STYLIZED',
    note: 'VIX 9/22 ≈27',
  },
  {
    path: 'market.fxUsdLocal',
    value: 0.89,
    unit: 'GBP/USD',
    asOf: '2022-09-22',
    sourceId: 'boe-fsr-2022-12',
    tag: 'STYLIZED',
    note: 'GBPUSD ≈1.125 → 파운드/달러 0.89',
  },
  {
    path: 'market.ownStock',
    value: 100,
    unit: 'index',
    asOf: '2022-09-22',
    sourceId: 'ppf-purple-book-2022',
    tag: 'STYLIZED',
    note: '연기금은 상장주가 없음 — 사용 안 함',
  },
  {
    path: 'market.ownCdsBp',
    value: 0,
    unit: 'bp',
    asOf: '2022-09-22',
    sourceId: 'ppf-purple-book-2022',
    tag: 'STYLIZED',
    note: '해당 없음',
  },
  // ───────────── 신뢰 ─────────────
  {
    path: 'confidence.index',
    value: 70,
    unit: 'index',
    asOf: '2022-09-22',
    sourceId: 'boe-fsr-2022-12',
    tag: 'CAL',
    note: 'S0 평온 하단: 8/1 이후 +135bp 상승과 재정 이벤트 경계',
  },
  {
    path: 'confidence.depositors',
    value: 70,
    unit: 'index',
    asOf: '2022-09-22',
    sourceId: 'boe-fsr-2022-12',
    tag: 'CAL',
    note: '가입자(표시용)',
  },
  {
    path: 'confidence.counterparties',
    value: 75,
    unit: 'index',
    asOf: '2022-09-22',
    sourceId: 'boe-fsr-2022-12',
    tag: 'CAL',
    note: 'LDI 운용사·레포 은행',
  },
  {
    path: 'confidence.regulators',
    value: 70,
    unit: 'index',
    asOf: '2022-09-22',
    sourceId: 'lords-ldi-report-2023',
    tag: 'CAL',
    note: 'TPR — 위기 전 레버리지 LDI 감독 공백',
  },
  {
    path: 'confidence.investors',
    value: 70,
    unit: 'index',
    asOf: '2022-09-22',
    sourceId: 'boe-fsr-2022-12',
    tag: 'CAL',
    note: '스폰서',
  },
  {
    path: 'confidence.media',
    value: 65,
    unit: 'index',
    asOf: '2022-09-22',
    sourceId: 'boe-fsr-2022-12',
    tag: 'CAL',
  },
  {
    path: 'confidence.board',
    value: 75,
    unit: 'index',
    asOf: '2022-09-22',
    sourceId: 'wpc-ldi-report-2023',
    tag: 'CAL',
    note: '수탁자 이사회',
  },
  // ───────────── 외생 충격(턴 진입) ─────────────
  {
    path: 'turns.t1.entry.yieldShock.deltaBp',
    value: 35,
    unit: 'bp',
    asOf: '2022-09-23',
    sourceId: 'boe-qb-2023-gilt',
    tag: 'CAL',
    note: '9/23~27 +130bp를 35/50/45로 분할 (35bp 초과 2일: BoE 스태프 페이퍼)',
  },
  {
    path: 'turns.t2.entry.yieldShock.deltaBp',
    value: 50,
    unit: 'bp',
    asOf: '2022-09-26',
    sourceId: 'boe-ldi-staff-paper-2023',
    tag: 'CAL',
    note: '일일 35bp 초과 상승 ①',
  },
  {
    path: 'turns.t3.entry.yieldShock.deltaBp',
    value: 45,
    unit: 'bp',
    asOf: '2022-09-27',
    sourceId: 'boe-ldi-staff-paper-2023',
    tag: 'CAL',
    note: '일일 35bp 초과 상승 ② — 3거래일 누적 +130bp(BoE QB) 재현',
  },
  {
    path: 'turns.t4.entry.yieldShock.deltaBp',
    value: 5,
    unit: 'bp',
    asOf: '2022-09-28T08:00+01:00',
    sourceId: 'boe-yield-curves',
    tag: 'STYLIZED',
    note: '9/28 오전 장중 고점 ≈5.1%대',
  },
  {
    path: 'turns.t5.entry.yieldShock.deltaBp',
    value: -110,
    unit: 'bp',
    asOf: '2022-09-28T16:30+01:00',
    sourceId: 'boe-qb-2023-gilt',
    note: '발표 당일 30년 −100bp 이상(도시에·QB), 종가 ≈4.0%',
  },
  {
    path: 'turns.t6.entry.yieldShock.deltaBp',
    value: 95,
    unit: 'bp',
    asOf: '2022-10-11',
    sourceId: 'boe-fsr-2022-12',
    tag: 'CAL',
    note: '9/28 종가 ≈4.05% → 10/11 ≈5.0%(호가 스프레드 2.5bp, 연동채 매입 추가일)',
  },
  {
    path: 'turns.t7.entry.yieldShock.deltaBp',
    value: 10,
    unit: 'bp',
    asOf: '2022-10-14',
    sourceId: 'boe-fsr-2022-12',
    note: '10/14 정점 — 잠시 5% 상회, 8/1 대비 +270bp 초과(FSR §1.2): 2.40 → 5.10',
  },
]
