import type { Source } from '../../engine/types'

/**
 * uk-ldi-2022 서지. 공유 서지(src/content/sources.ts)와 같은 id를 쓰는 항목은 내용도 동일하게 유지한다
 * (boe-qb-2023-gilt · boe-ldi-staff-paper-2023 · tpr-ldi-guidance-2023 · boe-breeden-2022 · imf-wp-2023-210 · cgfs-36).
 * 나머지는 시나리오 로컬 항목이며, 공유 서지 승격 후보다(보고서 참조).
 */
export const LDI_SOURCES: Source[] = [
  {
    id: 'boe-qb-2023-gilt',
    title: 'Financial stability buy/sell tools: a gilt market case study (Quarterly Bulletin 2023)',
    publisher: 'Bank of England',
    date: '2023-11-20',
    kind: 'regulatory',
    url: 'https://www.bankofengland.co.uk/quarterly-bulletin/2023/2023/financial-stability-buy-sell-tools-a-gilt-market-case-study',
    note: '9/22→27 30년 +130bp(3거래일), 호가 스프레드 0.5→2.5bp, 매입 £19.3bn(명목 12.1 + 연동 7.2), 연동채 10/11 추가, 재매각 11/29~1/12',
  },
  {
    id: 'boe-ldi-staff-paper-2023',
    title: 'Bank staff paper: LDI minimum resilience — recommendation and explainer',
    publisher: 'Bank of England (Financial Policy Committee)',
    date: '2023-03-29',
    kind: 'regulatory',
    url: 'https://www.bankofengland.co.uk/financial-policy-summary-and-record/2023/bank-staff-paper-ldi-minimum-resilience',
    note: '최소 회복력 250bp; 30년 일일 35bp 초과 상승 2회(2000년 이후 최대 29bp); 2022.12 FPC 300~400bp 유지 권고',
  },
  {
    id: 'tpr-ldi-guidance-2023',
    title: 'Using leveraged liability-driven investment (LDI 가이드)',
    publisher: 'The Pensions Regulator (TPR)',
    date: '2023-04-24',
    kind: 'regulatory',
    url: 'https://www.thepensionsregulator.gov.uk/en/document-library/scheme-management-detailed-guidance/funding-and-investment-detailed-guidance/liability-driven-investment',
    note: '시장 스트레스 버퍼 250bp + 운영 버퍼, 담보 보충 5일 가정, 수탁자 운영 준비 요건',
  },
  {
    id: 'boe-breeden-2022',
    title:
      'Risks from leverage: how did a small corner of the pensions industry threaten financial stability? (Sarah Breeden 연설)',
    publisher: 'Bank of England',
    date: '2022-11-07',
    kind: 'regulatory',
    url: 'https://www.bankofengland.co.uk/speech/2022/november/sarah-breeden-speech-at-isda-aimi-boe-on-nbfi-and-leverage',
    note: '13일간 LDI 펀드 자금 조달 >£40bn, 길트 매도 >£30bn; 풀드펀드 LDI 시장의 10~15%(≈£200bn); 리밸런싱에 "통상 1주, 때로 2주"',
  },
  {
    id: 'imf-wp-2023-210',
    title:
      "Putting Out the NBFIRE: Lessons from the UK's Liability-Driven Investment (LDI) Crisis (WP/23/210)",
    publisher: 'International Monetary Fund',
    date: '2023-09-29',
    kind: 'academic',
    url: 'https://www.imf.org/en/publications/wp/issues/2023/09/29/putting-out-the-nbfire-lessons-from-the-uk-s-liability-driven-investment-ldi-crisis-539683',
    note: '마진콜 추정 ≈£70bn, 길트 매도 추정 ≈£37bn, 30년 9/23~27 +140bp(IMF 기준), 파이어세일 역학',
  },
  {
    id: 'boe-fsr-2022-12',
    title: 'Financial Stability Report — December 2022 (§1.2 시장 상황, §5 LDI 펀드 회복력)',
    publisher: 'Bank of England (Financial Policy Committee)',
    date: '2022-12-13',
    kind: 'regulatory',
    url: 'https://www.bankofengland.co.uk/financial-stability-report/2022/december-2022',
    note: '8/1→10/14 정점 30년 +270bp 초과(잠시 5% 상회); 담보 콜·강제 길트 매도의 악순환; 미국·독일 30년은 같은 기간 약 +150bp',
  },
  {
    id: 'boe-pr-2022-09-28',
    title: 'Bank of England announces gilt market operation',
    publisher: 'Bank of England',
    date: '2022-09-28',
    kind: 'regulatory',
    url: 'https://www.bankofengland.co.uk/news/2022/september/bank-of-england-announces-gilt-market-operation',
    note: '11:00 발표: 9/28~10/14 장기 길트 임시 매입, 금융안정 목적, APF 길트 매각 10/31로 연기',
  },
  {
    id: 'boe-pr-2022-10-10',
    title: 'Bank of England announces additional measures to support market functioning',
    publisher: 'Bank of England',
    date: '2022-10-10',
    kind: 'regulatory',
    url: 'https://www.bankofengland.co.uk/news/2022/october/bank-of-england-announces-additional-measures-to-support-market-functioning',
    note: '회당 매입 한도 £5bn→£10bn, TECRF(담보 확대 레포, 회사채 포함) 신설, 10/14 종료 재확인',
  },
  {
    id: 'boe-pr-2022-10-11',
    title: 'Bank of England widens gilt purchase operations to include index-linked gilts',
    publisher: 'Bank of England',
    date: '2022-10-11',
    kind: 'regulatory',
    url: 'https://www.bankofengland.co.uk/news/2022/october/bank-of-england-widens-gilt-purchase-operations-to-include-index-linked-gilts',
    note: '물가연동채 매입 추가(연동채 시장 기능 저하 대응)',
  },
  {
    id: 'boe-mpc-2022-09-22',
    title: 'Monetary Policy Summary and minutes of the MPC meeting — September 2022',
    publisher: 'Bank of England',
    date: '2022-09-22',
    kind: 'regulatory',
    url: 'https://www.bankofengland.co.uk/monetary-policy-summary-and-minutes/2022/september-2022',
    note: 'Bank Rate 1.75→2.25%(+50bp), APF 길트 매각(QT) 개시 확정',
  },
  {
    id: 'boe-statement-2022-09-26',
    title: 'Statement from the Governor of the Bank of England',
    publisher: 'Bank of England',
    date: '2022-09-26',
    kind: 'regulatory',
    url: 'https://www.bankofengland.co.uk/news/2022/september/statement-from-the-governor-of-the-boe',
    note: '9/26 저녁: "시장을 면밀히 주시", 필요 시 금리 조정 주저하지 않을 것 — 임시 매입 언급 없음(사후정보 컷 근거)',
  },
  {
    id: 'hmt-growth-plan-2022',
    title: 'The Growth Plan 2022 (이른바 미니예산)',
    publisher: 'HM Treasury',
    date: '2022-09-23',
    kind: 'primary',
    url: 'https://www.gov.uk/government/publications/the-growth-plan-2022-documents',
    note: '9/23 09:30 발표: 재원 없는 감세(소득세 기본세율 인하, 45% 최고세율 폐지, 국민보험 인상 철회 등), OBR 전망 미동반',
  },
  {
    id: 'ppf-purple-book-2022',
    title: 'The Purple Book 2022 — DB pensions universe risk profile',
    publisher: 'Pension Protection Fund',
    date: '2022-12',
    kind: 'data',
    url: 'https://www.ppf.co.uk/purple-book',
    note: '영국 DB 스킴 자산배분(채권 비중 약 70%, 주식 약 20%), 헤지 비율·펀딩 수준 참고 — 합성 스킴 대차대조표 양식화 근거',
  },
  {
    id: 'wpc-ldi-report-2023',
    title: 'Defined benefit pensions with Liability Driven Investments (HC 826)',
    publisher: 'House of Commons Work and Pensions Committee',
    date: '2023-06-23',
    kind: 'regulatory',
    url: 'https://publications.parliament.uk/pa/cm5803/cmselect/cmworpen/826/report.html',
    note: '풀드펀드 운영 지연·수탁자 거버넌스·컨설턴트 역할 평가; URL은 위원회 보고서 HTML판(페이지 미확인)',
  },
  {
    id: 'lords-ldi-report-2023',
    title: 'Investigation into the LDI crisis (Industry and Regulators Committee 서한·보고)',
    publisher: 'House of Lords Industry and Regulators Committee',
    date: '2023-02-07',
    kind: 'regulatory',
    url: 'https://committees.parliament.uk/committee/517/industry-and-regulators-committee/',
    note: '레버리지 LDI의 규제 공백, TPR 역할, 스킴 운영 준비 미흡 지적',
  },
  {
    id: 'tpr-statement-2022-10-12',
    title: 'Statement on liability-driven investment (LDI) and market volatility',
    publisher: 'The Pensions Regulator (TPR)',
    date: '2022-10-12',
    kind: 'regulatory',
    url: 'https://www.thepensionsregulator.gov.uk/en/media-hub/press-releases/2022-press-releases/tpr-statement-on-ldi',
    note: '수탁자에게 회복력·유동성·거버넌스 점검 요구; URL은 보도자료 경로(정확 경로 미확인)',
  },
  {
    id: 'boe-swp-1019-pinter-2023',
    title:
      'An anatomy of the 2022 gilt market crisis (Staff Working Paper No. 1,019) — Gabor Pinter',
    publisher: 'Bank of England',
    date: '2023-03',
    kind: 'academic',
    url: 'https://www.bankofengland.co.uk/working-paper/2023/an-anatomy-of-the-2022-gilt-market-crisis',
    note: '거래 데이터로 본 LDI 펀드·연기금의 매도 집중, 딜러 중개 한계, 장기물 유동성 붕괴',
  },
  {
    id: 'bailey-2022-10-11-press',
    title: "Bailey tells pension funds: 'You've got three days left' (IIF 연차총회 발언 보도)",
    publisher: 'Reuters / Financial Times',
    date: '2022-10-11',
    kind: 'press',
    url: 'https://www.reuters.com/markets/europe/bank-england-tells-pension-funds-you-have-three-days-left-2022-10-11/',
    note: '타임스탬프·인용 용도만: 10/11 저녁(워싱턴) 총재 발언 → 10/14 종료 확정 인식',
  },
  {
    id: 'boe-yield-curves',
    title: 'Yield curves — daily government liability nominal spot curves',
    publisher: 'Bank of England (statistics)',
    date: '2022',
    kind: 'data',
    url: 'https://www.bankofengland.co.uk/statistics/yield-curves',
    note: '30년 명목 길트 수익률 일별 경로(9/22 ≈3.8% → 9/27 ≈5.0~5.1% → 9/28 종가 ≈4.0% → 10/11~14 5% 상회)',
  },
  {
    id: 'cgfs-36',
    title: 'The role of margin requirements and haircuts in procyclicality (CGFS Papers No 36)',
    publisher: 'Committee on the Global Financial System (BIS)',
    date: '2010-03',
    kind: 'regulatory',
    url: 'https://www.bis.org/publ/cgfs36.htm',
    note: '시장 관행 헤어컷 참고값: IG 회사채 5~10%, 주식 15~25%; 헤어컷 경기순응성',
  },
]
