/**
 * FactLedger — initialState 의 모든 숫자 리프와 보정 앵커를 출처에 연결한다 (docs/authoring-guide.md §4.2).
 * tag: VERIFY (2차 출처·언론·미확인 — 도시에 [2차]/[미확인] 항목은 지시에 따라 태그 유지) ·
 *      STYLIZED (선언된 단순화) · CAL (보정 규칙·앵커에서 도출)
 */
export interface FactRow {
  path: string
  value: number
  unit: string
  asOf: string
  knownAt?: string
  sourceId: string
  tag?: 'VERIFY' | 'STYLIZED' | 'CAL'
  note?: string
}

const Q2 = '2008-05-31'
const Q3 = '2008-08-31'
const T0 = '2008-09-09T09:00:00-04:00'

export const LEHMAN_FACTS: FactRow[] = [
  // ───────────── 자산 ─────────────
  {
    path: 'institution.cash',
    value: 42,
    unit: '$B',
    asOf: Q3,
    knownAt: '2008-09-10T07:30:00-04:00',
    sourceId: 'lehman-8k-2008-09-10',
    note: '"Estimated Liquidity Pool of $42 Billion". 내부적으로는 T0에 인지. 도시에·Valukas "약 $41B"와 병기',
  },
  {
    path: 'institution.custom.encumberedInPool',
    value: 7.5,
    unit: '$B',
    asOf: Q3,
    sourceId: 'valukas-report-2010',
    note: '유동성 풀에 포함된 JPM 담보 ≈$5.5B + 씨티 comfort deposit $2B. **1차 확인**: Valukas 보고서 Vol. 4 §III.A.5(Secured Lenders) 목차 항목 (5)(b), p.1455 — "Lehman Did Not Disclose in Its Second Quarter 2008 10-Q, Filed July 10, 2008, That It Was Including Both the $2 Billion Citibank \'Comfort Deposit\' and Approximately $5.5 Billion of Securities Collateral Pledged to JPMorgan in Its Liquidity Pool". 같은 절은 이 밖에 BofA $500m·HSBC ≈$1B·9월 합의서에 따른 JPM 추가 $8B도 풀에 포함되어 있었다고 적는다',
  },
  {
    path: 'institution.securities.afs.marketValue',
    value: 190,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '보유 금융상품 $269.4B 중 유동 인벤토리(국채·기관채·투자등급·주식) 양식화',
  },
  {
    path: 'institution.securities.afs.bookValue',
    value: 190,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.securities.afs.modDuration',
    value: 3,
    unit: 'y',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.securities.afs.pledgedShare',
    value: 0.8,
    unit: 'fraction',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '트라이파티 레포 $188B(5/31)로 조달되는 인벤토리 비중',
  },
  {
    path: 'institution.securities.htm.bookValue',
    value: 46,
    unit: '$B',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    note: 'CRE $32.6B + 주택 $13.2B(pro forma) = 45.8',
  },
  {
    path: 'institution.securities.htm.marketValue',
    value: 38,
    unit: '$B',
    asOf: T0,
    sourceId: 'valukas-report-2010',
    tag: 'CAL',
    note: '시장이 요구하는 추가 상각 ≈17% (마크 논쟁; Valukas 실사·애널리스트 비판) — economicTce 에만 반영',
  },
  {
    path: 'institution.securities.htm.modDuration',
    value: 5,
    unit: 'y',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.securities.htm.pledgedShare',
    value: 0.5,
    unit: 'fraction',
    asOf: Q3,
    sourceId: 'fcic-report-2011',
    tag: 'STYLIZED',
    note: 'CMBS 일부가 트라이파티 레포 담보(repoOther)로 예치',
  },
  {
    path: 'institution.loans.corporate',
    value: 295,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '역레포 $169.7B + 증권차입 $124.8B = 294.5 (매치드북)',
  },
  {
    path: 'institution.loans.fi',
    value: 41,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    note: '브로커·고객·기타 미수금 16.7 + 20.8 + 4.2 = 41.7',
  },
  {
    path: 'institution.loans.retail',
    value: 0,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.loans.sme',
    value: 0,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.loans.nonPerforming',
    value: 0,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.loans.avgDuration',
    value: 0.1,
    unit: 'y',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.otherAssets',
    value: 26,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: 'plug: 총자산 640 − (42 + 190 + 46 + 295 + 41). 영업권·IMD 장부가 포함',
  },
  {
    path: 'institution.leverageExposure',
    value: 640,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note:
      '10-Q 원문 확인: 5/31 총자산 $639,432M · 총부채 $613,156M · 자기자본 $26,276M. 합성 대차대조표가 ' +
      '정수로 맞아떨어지도록 640으로 반올림(+0.6)했다',
  },
  // ───────────── 조달 세그먼트 ─────────────
  {
    path: 'institution.deposits.0.balance',
    value: 25,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '고객 지급채무 $57.3B 중 PB 프리크레딧 양식화',
  },
  {
    path: 'institution.deposits.1.balance',
    value: 15,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: 'OTC 파생 담보(현금)·노베이션 대상',
  },
  {
    path: 'institution.deposits.2.balance',
    value: 12,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '단기차입 $35.3B 중 CP·MTN·은행 라인 등 만기 도래분 양식화',
  },
  {
    path: 'institution.deposits.3.balance',
    value: 28,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '기타 고객 지급채무(운영성·결제 대기)',
  },
  // 유출률 앵커 (S0/S1/S2/S3)
  {
    path: 'institution.deposits.0.runoffByState.2',
    value: 0.12,
    unit: 'fraction/day',
    asOf: '2008-09-11',
    sourceId: 'sec-cox-basel-2008-03-20',
    tag: 'CAL',
    note: '베어 유동성 풀 3일 −89%($18.1B→≈$2B)와 리먼 9/10~12 풀 $42B→<$2B(Valukas)를 세그먼트+레포 채널 합산으로 재현',
  },
  {
    path: 'institution.deposits.0.runoffByState.3',
    value: 0.15,
    unit: 'fraction/day',
    asOf: '2008-09-12',
    sourceId: 'valukas-report-2010',
    tag: 'CAL',
    note: 'S3 금요일: 세그먼트 유출 ≈8 + 레포 롤오프 4.5 + JPM 2차 콜 5 → 풀 ≈2~3',
  },
  {
    path: 'institution.deposits.2.runoffByState.2',
    value: 0.2,
    unit: 'fraction/day',
    asOf: '2008-09-11',
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
    note: '도매 무담보: 만기 시 100% 미갱신 (일평균 만기 도래 ≈25~35%)',
  },
  // ───────────── 도매·레포 ─────────────
  {
    path: 'institution.wholesale.unsecuredLong',
    value: 128,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    note: '장기차입 $128.2B. 도시에 "부채 ~$100B"[2차]는 채권 채무 추정치로 병기',
  },
  {
    path: 'institution.wholesale.repoL1',
    value: 120,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '트라이파티 레포 $188B(5/31) → 합성 185 = 120(국채·기관) + 40(IG·주식) + 25(CMBS·비IG) [CAL/VERIFY: 9월 초 규모 $150~200B]',
  },
  {
    path: 'institution.wholesale.repoL2A',
    value: 40,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.wholesale.repoOther',
    value: 25,
    unit: '$B',
    asOf: Q2,
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
    note: '카운터파티가 롤오버를 거부한 비유동 담보 레포. 9/11~12 전량 소멸을 재현하도록 크기 설정',
  },
  {
    path: 'institution.wholesale.unsecuredShort',
    value: 0,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '단기 무담보는 deposits[2]로 표현',
  },
  {
    path: 'institution.wholesale.cbAdvances',
    value: 0,
    unit: '$B',
    asOf: T0,
    sourceId: 'fed-history-support-institutions',
    note: '9/15 이전 PDCF 차입 잔액 없음',
  },
  {
    path: 'institution.wholesale.cbFacilityCapacity',
    value: 0,
    unit: '$B',
    asOf: T0,
    sourceId: 'ball-nber-w22410',
    tag: 'CAL',
    note: 'PDCF 적격 담보 ≥$131B(Ball)가 있었으나 브로커딜러 앞 사전 예치·테스트가 없었다는 설정. T0.B 선택 시 +20',
  },
  {
    path: 'institution.wholesale.cbFacilityPending',
    value: 0,
    unit: '$B',
    asOf: T0,
    sourceId: 'ball-nber-w22410',
    tag: 'CAL',
  },
  {
    path: 'institution.committed.creditToCorporates',
    value: 0,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.committed.liquidityToFIs',
    value: 0,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.otherLiabilities',
    value: 219,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: 'plug: 공매도 포지션 $141.5B + 파생·기타. A = L + E: 640 = 80 + 185 + 128 + 219 + 28',
  },
  // ───────────── 자본 ─────────────
  {
    path: 'institution.capital.cet1',
    value: 20,
    unit: '$B',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'STYLIZED',
    note: '주주지분 $28.4B − 우선주 ≈8 = 보통주 ≈20 (도시에 "자본 ~$20B" 부합). 3분기 손실 $3.9B는 이미 반영된 수치',
  },
  {
    path: 'institution.capital.at1',
    value: 8,
    unit: '$B',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'STYLIZED',
    note: '우선주(2008.4·6 발행 포함) 양식화',
  },
  {
    path: 'institution.capital.tier2',
    value: 0,
    unit: '$B',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.rwa',
    value: 255,
    unit: '$B',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'CAL',
    note: 'Tier 1 ≈11.0% 역산 (28/255)',
  },
  {
    path: 'institution.fireSaleDiscount',
    value: 0.1,
    unit: 'fraction',
    asOf: T0,
    sourceId: 'cgfs-36',
    tag: 'CAL',
    note: '비유동 자산 5~15% (가이드 행동 비용표)',
  },
  {
    path: 'institution.taxRate',
    value: 0,
    unit: 'fraction',
    asOf: T0,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.custom.minimumCash',
    value: 0,
    unit: '$B',
    asOf: T0,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.custom.neubergerValue',
    value: 7,
    unit: '$B',
    asOf: '2008-09-09',
    sourceId: 'press-nb-carlyle-2008-09',
    tag: 'VERIFY',
    note: '칼라일 제안 ≈$7B(파산 전); 중순 입찰 ≈$5B; 최종 $2.15B(8-K 9/29, 1차). 파산 전 입찰가를 수치로 적은 1차 문서를 찾지 못했다 — **Valukas 보고서 Vol. 2 §III.A.2(Survival)의 IMD 매각 절차 서술에는 칼라일 제안 금액이 없음을 본문 검색으로 확인했다.** 해소 문서: LBHI 파산사건 기록(Bankr. S.D.N.Y. No. 08-13555) 중 IMD(뉴버거버먼) 매각 승인 신청서와 그 증거자료(2008-10-06 제출분 및 후속 매각절차 명령), 또는 Valukas 보고서 Vol. 6~9 부록의 IMD 매각 관련 증거(Appendix 소장 문서 목록)',
  },
  {
    path: 'institution.custom.repoRollRate',
    value: 100,
    unit: '%',
    asOf: T0,
    sourceId: 'nyfed-sr506',
    tag: 'CAL',
  },
  {
    path: 'institution.custom.repoBookStart',
    value: 185,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.custom.clearingBankCalls',
    value: 0,
    unit: '$B',
    asOf: T0,
    sourceId: 'valukas-report-2010',
  },
  {
    path: 'institution.custom.spinCoSize',
    value: 30,
    unit: '$B',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    note: 'REI Global $25~30B',
  },
  // ───────────── 시장 ─────────────
  {
    path: 'market.policyRateBp',
    value: 200,
    unit: 'bp',
    asOf: '2008-04-30',
    sourceId: 'fed-history-credit-programs',
    note: 'FF 목표 2.00%',
  },
  {
    path: 'market.govt2yBp',
    value: 223,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'frb-h15-treasury-2008',
    note: 'DGS2 2008-09-09 종가 2.23%',
  },
  {
    path: 'market.govt10yBp',
    value: 362,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'frb-h15-treasury-2008',
    note: 'DGS10 2008-09-09 종가 3.62%',
  },
  {
    path: 'market.govt30yBp',
    value: 420,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'frb-h15-treasury-2008',
    note: 'DGS30 2008-09-09 종가 4.20%',
  },
  {
    path: 'market.creditSpreadIgBp',
    value: 300,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'VERIFY',
    note:
      '**해소 문서**: `api.stlouisfed.org/fred/series/observations?series_id=BAMLC0A0CM&observation_date=2008-09-09` ' +
      '(무료 FRED API 키 필요). 익명 CSV(`fredgraph.csv?id=BAMLC0A0CM`)는 날짜 파라미터를 붙여도 최근 3년만 ' +
      '반환한다(docs/research/data-sources-global.md §2). 교차 확인(공개 계열로 직접 조회): 2008-09-09 ' +
      'DBAA 6.97% · DAAA 5.37% · DGS10 3.62% → Baa−10y 335bp, Aaa−10y 175bp — 300bp는 그 사이에 든다',
  },
  {
    path: 'market.creditSpreadHyBp',
    value: 850,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'VERIFY',
    note:
      '**해소 문서**: `api.stlouisfed.org/fred/series/observations?series_id=BAMLH0A0HYM2&observation_date=2008-09-09` ' +
      '(무료 FRED API 키 필요). 익명 접근의 제약은 IG와 동일하다(docs/research/data-sources-global.md §2)',
  },
  {
    path: 'market.fundingStressBp',
    value: 119,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'fred-tedrate-2008',
    note: 'TED 2008-09-09 1.19%; 9/12 1.36 → 9/15 1.79; 10/10 4.58% 정점 [fcic-report-2011]',
  },
  {
    path: 'market.custom.tedBp',
    value: 119,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'fred-tedrate-2008',
  },
  {
    path: 'market.equityIndex',
    value: 100,
    unit: 'index',
    asOf: '2008-09-08',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'STYLIZED',
  },
  {
    path: 'market.volIndex',
    value: 25.5,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'cboe-vix-2008',
    note: 'VIX 2008-09-09 종가 25.47',
  },
  {
    path: 'market.fxUsdLocal',
    value: 1,
    unit: 'fx',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'STYLIZED',
  },
  {
    path: 'market.ownStock',
    value: 100,
    unit: 'index',
    asOf: '2008-09-08',
    sourceId: 'press-kdb-2008-09-09',
    note: '9/8 종가 = 100; 9/9 −45%, 9/10 −7%, 9/11 −42%, 9/12 −14% [press]',
  },
  {
    path: 'market.ownCdsBp',
    value: 475,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'VERIFY',
    note: '리먼 5년 CDS 2008-09-09. Markit 일별 스프레드는 공개 접근이 불가해 미확인. **해소 문서**: FCIC 자료실(fcic.law.stanford.edu)의 위원회 수집 데이터 파일 중 Markit CDS 스프레드 계열, 또는 Markit/IHS 라이선스 데이터. **본 점검에서 확인한 사실**: Valukas 보고서 Vol. 1·2·4 본문에는 리먼 CDS 스프레드의 bp 수치가 없다(전문 검색). 따라서 종전 주석이 적던 "Valukas Vol.4 담보·CDS 절"은 해소 경로가 아니다',
  },
  // ───────────── 신뢰 ─────────────
  {
    path: 'confidence.index',
    value: 58,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
    note: 'S1 우려 중간: 6월 이후 지속 압박, 9/9 −45%',
  },
  {
    path: 'confidence.depositors',
    value: 55,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
  },
  {
    path: 'confidence.counterparties',
    value: 52,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
  },
  {
    path: 'confidence.regulators',
    value: 50,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
  },
  {
    path: 'confidence.investors',
    value: 45,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'CAL',
  },
  {
    path: 'confidence.media',
    value: 45,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'CAL',
  },
  {
    path: 'confidence.board',
    value: 70,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
  },
  // ───────────── 외생 이벤트 크기 (턴 효과) ─────────────
  {
    path: 'event.t2.clearingBankCall',
    value: 5,
    unit: '$B',
    asOf: '2008-09-11',
    sourceId: 'valukas-report-2010',
    note: 'JPM 추가 담보 요구 $5B (9/9 요구 → 9/11 이행)',
  },
  {
    path: 'event.t3.clearingBankCall2',
    value: 5,
    unit: '$B',
    asOf: '2008-09-12',
    sourceId: 'valukas-report-2010',
    note: 'JPM 2차 추가 담보 요구 $5B (9/11 요구 → 9/12 현금 이행). **1차 확인**: Valukas 보고서 Vol. 4 §III.A.5(Secured Lenders) — "JPMorgan demanded $5 billion more in cash collateral on September 11, 2008, which Lehman provided by the afternoon of September 12." 같은 절의 요약은 청산은행 담보의 세 축을 (i) 2008년 중 청산 관련 마진 누적 ≈$8B, (ii) 9/9 요구 $5B, (iii) 9/11 요구 현금 $5B로 적는다',
  },
  {
    path: 'event.t0.pdcfPrepositionCapacity',
    value: 20,
    unit: '$B',
    asOf: '2008-09-09',
    sourceId: 'ball-nber-w22410',
    tag: 'CAL',
    note: '브로커딜러가 2주 내 PDCF 앞으로 이동·테스트 가능한 투자등급 미담보 인벤토리 [CAL] (Ball: 적격 담보 ≥$131B)',
  },
  {
    path: 'event.t5.pdcfExpansionCapacity',
    value: 12,
    unit: '$B',
    asOf: '2008-09-14T21:00:00-04:00',
    sourceId: 'fed-pr-2008-09-14',
    tag: 'CAL',
    note: '9/14 담보 확대(트라이파티 적격 전체)로 늘어나는 BD 여력 12(사전 목록 준비 시 20); 9/15 LBI PDCF $28B 차입(Fed History) 자릿수',
  },
  {
    path: 'anchor.bear.liquidityPool',
    value: 18.1,
    unit: '$B',
    asOf: '2008-03-10',
    sourceId: 'sec-cox-basel-2008-03-20',
    note: '**1차 확인**: SEC 위원장 Cox가 바젤위원회에 보낸 2008-03-20 서한(SEC Press Release 2008-48) 본문의 베어스턴스 지주 유동성 풀 표 — 3/10 $18.1B(고객자산보호규칙 조정 시 15.1) → 3/11 $11.5B → 3/12 $12.4B → 3/13 $2B. 서한은 "On Tuesday, March 11, the holding company liquidity pool declined from $18.1 billion to $11.5 billion"이라고 적는다',
  },
  {
    path: 'anchor.lehman.usablePoolFriday',
    value: 2.4,
    unit: '$B',
    asOf: '2008-09-12',
    sourceId: 'valukas-report-2010',
    note: '9/12(금) 즉시 현금화 가능 자산 **$2.4B**. **1차 확인**: Valukas 보고서 Vol. 4 §III.A.5 — 리먼은 전주 말 보고유동성 $42.1B(고현금화 가능 $33.8B)로 마쳤고, 9/10 $37.6B(저현금화 $27.3B), 9/12에는 보고유동성 $32.5B 중 $30.1B가 "low ability to monetize"로 분류되었다. "In other words, only $2.4 billion of Lehman\'s $32.5 billion liquidity pool was readily convertible to cash on September 12." 종전 값 2(「<$2B」)는 2차 인용이었다. 이 정정에 맞추어 t3 `cash` 체크포인트의 기대값도 2 → 2.4로 옮겼다(허용오차 1.0은 그대로)',
  },
  {
    path: 'anchor.lehman.chapter11Assets',
    value: 639,
    unit: '$B',
    asOf: '2008-09-15',
    sourceId: 'lehman-10q-2q08',
    note: '파산 신청서가 인용한 $639B는 5/31 10-Q 총자산 $639,432M(원문 확인)',
  },
  // ───────────── 9/11·9/12 일중 티커 앵커 (L2-c 서브턴 틱) ─────────────
  // 앵커는 전부 "그날의 종가"이고 일중 분포는 [STYLIZED]다. FRED 계열은 등록 없이 받을 수 있으며
  // (docs/research/data-sources-global.md §1) 아래 값은 fredgraph.csv 에서 직접 확인했다.
  {
    path: 'anchor.tedBp.2008-09-10',
    value: 120,
    unit: 'bp',
    asOf: '2008-09-10',
    sourceId: 'fred-tedrate-2008',
    note: 'TEDRATE 9/10 종가 1.20%. T2 티커의 틱 0 앵커 (T2 entryEffects가 이 값으로 앵커를 세운다)',
  },
  {
    path: 'anchor.tedBp.2008-09-11',
    value: 124,
    unit: 'bp',
    asOf: '2008-09-11',
    sourceId: 'fred-tedrate-2008',
    note: 'TEDRATE 9/11 종가 1.24%. T2 티커의 종착점이자 T3 티커의 틱 0 앵커',
  },
  {
    path: 'anchor.tedBp.2008-09-12',
    value: 136,
    unit: 'bp',
    asOf: '2008-09-12',
    sourceId: 'fred-tedrate-2008',
    note: 'TEDRATE 9/12 종가 1.36%. T3 티커의 종착점 (9/15 1.79 → 10/10 4.58 정점)',
  },
  {
    path: 'anchor.vix.2008-09-11',
    value: 24.39,
    unit: 'index',
    asOf: '2008-09-11',
    sourceId: 'cboe-vix-2008',
    note:
      'VIXCLS 9/11 종가 24.39 (9/9 25.47 → 9/10 24.52 → 9/11 24.39 → 9/12 25.66). 티커에는 쓰지 않고 ' +
      'TED 궤적의 교차 확인용으로만 기록한다 — 파산 직전 주에도 VIX는 25 안팎에 머물렀고, ' +
      '스트레스는 주식 변동성이 아니라 자금시장(TED)에 먼저 나타났다',
  },
  {
    path: 'anchor.vix.2008-09-12',
    value: 25.66,
    unit: 'index',
    asOf: '2008-09-12',
    sourceId: 'cboe-vix-2008',
    note: 'VIXCLS 9/12 종가 25.66 → 9/15 31.70 (파산 신청 당일 +24%)',
  },
  {
    path: 'anchor.ownStockGap.2008-09-11',
    value: -0.2,
    unit: 'fraction',
    asOf: '2008-09-11T09:30-04:00',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'STYLIZED',
    note:
      '9/11 종가 −42%를 프리마켓 갭(−20%) × 장중 티커(0.725)로 분해했다. 곱 0.58은 종전 단일 ' +
      '−42%와 정확히 같다. 시간대별 분해 자료는 없으므로 갭·티커 배분 자체는 양식화 값이다',
  },
  {
    path: 'anchor.ownStockGap.2008-09-12',
    value: -0.0703,
    unit: 'fraction',
    asOf: '2008-09-12T09:30-04:00',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'STYLIZED',
    note: '9/12 종가 −14% = 갭(0.86/0.925 − 1 ≈ −7.03%) × 장중 티커(0.925). 곱 0.86은 종전과 동일',
  },
  {
    path: 'anchor.ownCdsBp.2008-09-11',
    value: 700,
    unit: 'bp',
    asOf: '2008-09-11',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'VERIFY',
    note:
      '기존 T2 시세 이벤트(t2-market)가 표시하던 "≈700bp+"를 티커 종착점으로 승계한 값이다. ' +
      'Markit 일별 스프레드는 공개 접근이 불가해 미확인 — **해소 문서**는 T0 앵커(475bp)와 동일하게 ' +
      'FCIC 자료실의 위원회 수집 Markit CDS 계열 또는 Markit/IHS 라이선스 데이터다. ' +
      '**본 점검에서 Valukas 보고서 Vol. 1·2·4 본문에 CDS bp 수치가 없음을 확인했으므로 그 경로는 제외한다.** ' +
      '교차 확인 주의: BIS Quarterly Review 2008-12 [bis-qr-2008-12]가 인용하는 9월 초 327 → 360/370bp는 ' +
      'KDB 협상 결렬(9/9) **이전**의 관측이므로 이 앵커와 같은 시점이 아니다 — 모순이라기보다 다른 날짜다. ' +
      '그래도 9/9·9/11 값 자체는 미확정이므로 위 두 1차 문서로 확정해야 한다',
  },
  {
    path: 'anchor.ownCdsBp.2008-09-12',
    value: 775,
    unit: 'bp',
    asOf: '2008-09-12',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'VERIFY',
    note:
      '9/12 5년 CDS. 기존 시나리오에 표시 값이 없던 날이므로 9/11 대비 추가 확대를 양식화했다. ' +
      '**해소 문서**는 9/11 앵커와 같다 — FCIC 자료실의 위원회 수집 Markit CDS 계열 또는 ' +
      'Markit/IHS 라이선스 데이터(Valukas 보고서 본문에는 bp 수치가 없다)',
  },
  {
    path: 'anchor.nyDayProfile',
    value: 0.35,
    unit: 'fraction',
    asOf: '2008-09-11',
    sourceId: 'nyfed-sr506',
    tag: 'STYLIZED',
    note:
      '뉴욕 영업일 유출 프로필 [0.35, 0.25, 0.18, 0.12, 0.10]의 첫 슬라이스. 전방 집중의 근거는 ' +
      '트라이파티 언와인드가 아침에 일괄 실행된다는 구조(NY Fed SR 506 / EPR 2012)이며, ' +
      '시각별 인출 자료는 공개되지 않았으므로 분포 자체는 양식화 값이다. 합계는 1이다',
  },
]
