/**
 * FactLedger — initialState 의 모든 숫자 리프와 보정 앵커를 출처에 연결한다 (docs/authoring-guide.md §4.2).
 * tag: VERIFY (2차 출처·언론·미확인 — 도시에 [2차]/[미확인] 항목은 지시에 따라 태그 유지) ·
 *      STYLIZED (선언된 단순화) · CAL (보정 규칙·앵커에서 도출)
 */
export interface FactRow {
  path: string
  value: number
  unit: string
  asOf: string
  knownAt?: string
  sourceId: string
  tag?: 'VERIFY' | 'STYLIZED' | 'CAL'
  note?: string
}

const Q2 = '2008-05-31'
const Q3 = '2008-08-31'
const T0 = '2008-09-09T09:00:00-04:00'

export const LEHMAN_FACTS: FactRow[] = [
  // ───────────── 자산 ─────────────
  {
    path: 'institution.cash',
    value: 42,
    unit: '$B',
    asOf: Q3,
    knownAt: '2008-09-10T07:30:00-04:00',
    sourceId: 'lehman-8k-2008-09-10',
    note: '"Estimated Liquidity Pool of $42 Billion". 내부적으로는 T0에 인지. 도시에·Valukas "약 $41B"와 병기',
  },
  {
    path: 'institution.custom.encumberedInPool',
    value: 7.5,
    unit: '$B',
    asOf: Q3,
    sourceId: 'valukas-report-2010',
    tag: 'VERIFY',
    note: '유동성 풀에 포함된 JPM 담보 ≈$5.5B + 씨티 comfort deposit $2B (2차 인용)',
  },
  {
    path: 'institution.securities.afs.marketValue',
    value: 190,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '보유 금융상품 $269.4B 중 유동 인벤토리(국채·기관채·투자등급·주식) 양식화',
  },
  {
    path: 'institution.securities.afs.bookValue',
    value: 190,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.securities.afs.modDuration',
    value: 3,
    unit: 'y',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.securities.afs.pledgedShare',
    value: 0.8,
    unit: 'fraction',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '트라이파티 레포 $188B(5/31)로 조달되는 인벤토리 비중',
  },
  {
    path: 'institution.securities.htm.bookValue',
    value: 46,
    unit: '$B',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    note: 'CRE $32.6B + 주택 $13.2B(pro forma) = 45.8',
  },
  {
    path: 'institution.securities.htm.marketValue',
    value: 38,
    unit: '$B',
    asOf: T0,
    sourceId: 'valukas-report-2010',
    tag: 'CAL',
    note: '시장이 요구하는 추가 상각 ≈17% (마크 논쟁; Valukas 실사·애널리스트 비판) — economicTce 에만 반영',
  },
  {
    path: 'institution.securities.htm.modDuration',
    value: 5,
    unit: 'y',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.securities.htm.pledgedShare',
    value: 0.5,
    unit: 'fraction',
    asOf: Q3,
    sourceId: 'fcic-report-2011',
    tag: 'STYLIZED',
    note: 'CMBS 일부가 트라이파티 레포 담보(repoOther)로 예치',
  },
  {
    path: 'institution.loans.corporate',
    value: 295,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '역레포 $169.7B + 증권차입 $124.8B = 294.5 (매치드북)',
  },
  {
    path: 'institution.loans.fi',
    value: 41,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    note: '브로커·고객·기타 미수금 16.7 + 20.8 + 4.2 = 41.7',
  },
  {
    path: 'institution.loans.retail',
    value: 0,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.loans.sme',
    value: 0,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.loans.nonPerforming',
    value: 0,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.loans.avgDuration',
    value: 0.1,
    unit: 'y',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.otherAssets',
    value: 26,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: 'plug: 총자산 640 − (42 + 190 + 46 + 295 + 41). 영업권·IMD 장부가 포함',
  },
  {
    path: 'institution.leverageExposure',
    value: 640,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'VERIFY',
    note: '총자산 $639.4B(5/31 10-Q; 파산 신청서 인용). 도시에 [2차] 태그 유지 — 10-Q(1차)로 해소 가능',
  },
  // ───────────── 조달 세그먼트 ─────────────
  {
    path: 'institution.deposits.0.balance',
    value: 25,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '고객 지급채무 $57.3B 중 PB 프리크레딧 양식화',
  },
  {
    path: 'institution.deposits.1.balance',
    value: 15,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: 'OTC 파생 담보(현금)·노베이션 대상',
  },
  {
    path: 'institution.deposits.2.balance',
    value: 12,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '단기차입 $35.3B 중 CP·MTN·은행 라인 등 만기 도래분 양식화',
  },
  {
    path: 'institution.deposits.3.balance',
    value: 28,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '기타 고객 지급채무(운영성·결제 대기)',
  },
  // 유출률 앵커 (S0/S1/S2/S3)
  {
    path: 'institution.deposits.0.runoffByState.2',
    value: 0.12,
    unit: 'fraction/day',
    asOf: '2008-09-11',
    sourceId: 'sec-cox-basel-2008-03-20',
    tag: 'CAL',
    note: '베어 유동성 풀 3일 −89%($18.1B→≈$2B)와 리먼 9/10~12 풀 $42B→<$2B(Valukas)를 세그먼트+레포 채널 합산으로 재현',
  },
  {
    path: 'institution.deposits.0.runoffByState.3',
    value: 0.15,
    unit: 'fraction/day',
    asOf: '2008-09-12',
    sourceId: 'valukas-report-2010',
    tag: 'CAL',
    note: 'S3 금요일: 세그먼트 유출 ≈8 + 레포 롤오프 4.5 + JPM 2차 콜 5 → 풀 ≈2~3',
  },
  {
    path: 'institution.deposits.2.runoffByState.2',
    value: 0.2,
    unit: 'fraction/day',
    asOf: '2008-09-11',
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
    note: '도매 무담보: 만기 시 100% 미갱신 (일평균 만기 도래 ≈25~35%)',
  },
  // ───────────── 도매·레포 ─────────────
  {
    path: 'institution.wholesale.unsecuredLong',
    value: 128,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    note: '장기차입 $128.2B. 도시에 "부채 ~$100B"[2차]는 채권 채무 추정치로 병기',
  },
  {
    path: 'institution.wholesale.repoL1',
    value: 120,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '트라이파티 레포 $188B(5/31) → 합성 185 = 120(국채·기관) + 40(IG·주식) + 25(CMBS·비IG) [CAL/VERIFY: 9월 초 규모 $150~200B]',
  },
  {
    path: 'institution.wholesale.repoL2A',
    value: 40,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.wholesale.repoOther',
    value: 25,
    unit: '$B',
    asOf: Q2,
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
    note: '카운터파티가 롤오버를 거부한 비유동 담보 레포. 9/11~12 전량 소멸을 재현하도록 크기 설정',
  },
  {
    path: 'institution.wholesale.unsecuredShort',
    value: 0,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: '단기 무담보는 deposits[2]로 표현',
  },
  {
    path: 'institution.wholesale.cbAdvances',
    value: 0,
    unit: '$B',
    asOf: T0,
    sourceId: 'fed-history-support-institutions',
    note: '9/15 이전 PDCF 차입 잔액 없음',
  },
  {
    path: 'institution.wholesale.cbFacilityCapacity',
    value: 0,
    unit: '$B',
    asOf: T0,
    sourceId: 'ball-nber-w22410',
    tag: 'CAL',
    note: 'PDCF 적격 담보 ≥$131B(Ball)가 있었으나 브로커딜러 앞 사전 예치·테스트가 없었다는 설정. T0.B 선택 시 +20',
  },
  {
    path: 'institution.wholesale.cbFacilityPending',
    value: 0,
    unit: '$B',
    asOf: T0,
    sourceId: 'ball-nber-w22410',
    tag: 'CAL',
  },
  {
    path: 'institution.committed.creditToCorporates',
    value: 0,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.committed.liquidityToFIs',
    value: 0,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.otherLiabilities',
    value: 219,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
    note: 'plug: 공매도 포지션 $141.5B + 파생·기타. A = L + E: 640 = 80 + 185 + 128 + 219 + 28',
  },
  // ───────────── 자본 ─────────────
  {
    path: 'institution.capital.cet1',
    value: 20,
    unit: '$B',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'STYLIZED',
    note: '주주지분 $28.4B − 우선주 ≈8 = 보통주 ≈20 (도시에 "자본 ~$20B" 부합). 3분기 손실 $3.9B는 이미 반영된 수치',
  },
  {
    path: 'institution.capital.at1',
    value: 8,
    unit: '$B',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'STYLIZED',
    note: '우선주(2008.4·6 발행 포함) 양식화',
  },
  {
    path: 'institution.capital.tier2',
    value: 0,
    unit: '$B',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.rwa',
    value: 255,
    unit: '$B',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'CAL',
    note: 'Tier 1 ≈11.0% 역산 (28/255)',
  },
  {
    path: 'institution.fireSaleDiscount',
    value: 0.1,
    unit: 'fraction',
    asOf: T0,
    sourceId: 'cgfs-36',
    tag: 'CAL',
    note: '비유동 자산 5~15% (가이드 행동 비용표)',
  },
  {
    path: 'institution.taxRate',
    value: 0,
    unit: 'fraction',
    asOf: T0,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.custom.minimumCash',
    value: 0,
    unit: '$B',
    asOf: T0,
    sourceId: 'lehman-8k-2008-09-10',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.custom.neubergerValue',
    value: 7,
    unit: '$B',
    asOf: '2008-09-09',
    sourceId: 'press-nb-carlyle-2008-09',
    tag: 'VERIFY',
    note: '칼라일 제안 ≈$7B(파산 전); 중순 입찰 ≈$5B; 최종 $2.15B(8-K 9/29, 1차)',
  },
  {
    path: 'institution.custom.repoRollRate',
    value: 100,
    unit: '%',
    asOf: T0,
    sourceId: 'nyfed-sr506',
    tag: 'CAL',
  },
  {
    path: 'institution.custom.repoBookStart',
    value: 185,
    unit: '$B',
    asOf: Q2,
    sourceId: 'lehman-10q-2q08',
    tag: 'STYLIZED',
  },
  {
    path: 'institution.custom.clearingBankCalls',
    value: 0,
    unit: '$B',
    asOf: T0,
    sourceId: 'valukas-report-2010',
  },
  {
    path: 'institution.custom.spinCoSize',
    value: 30,
    unit: '$B',
    asOf: Q3,
    sourceId: 'lehman-8k-2008-09-10',
    note: 'REI Global $25~30B',
  },
  // ───────────── 시장 ─────────────
  {
    path: 'market.policyRateBp',
    value: 200,
    unit: 'bp',
    asOf: '2008-04-30',
    sourceId: 'fed-history-credit-programs',
    note: 'FF 목표 2.00%',
  },
  {
    path: 'market.govt2yBp',
    value: 225,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'VERIFY',
  },
  {
    path: 'market.govt10yBp',
    value: 360,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'VERIFY',
  },
  {
    path: 'market.govt30yBp',
    value: 420,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'VERIFY',
  },
  {
    path: 'market.creditSpreadIgBp',
    value: 300,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'VERIFY',
  },
  {
    path: 'market.creditSpreadHyBp',
    value: 850,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'VERIFY',
  },
  {
    path: 'market.fundingStressBp',
    value: 115,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'VERIFY',
    note: 'TED ≈1.1~1.2%; 10/10 4.58% 정점(도시에 검증)',
  },
  {
    path: 'market.custom.tedBp',
    value: 115,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'VERIFY',
  },
  {
    path: 'market.equityIndex',
    value: 100,
    unit: 'index',
    asOf: '2008-09-08',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'STYLIZED',
  },
  {
    path: 'market.volIndex',
    value: 25,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'VERIFY',
  },
  {
    path: 'market.fxUsdLocal',
    value: 1,
    unit: 'fx',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'STYLIZED',
  },
  {
    path: 'market.ownStock',
    value: 100,
    unit: 'index',
    asOf: '2008-09-08',
    sourceId: 'press-kdb-2008-09-09',
    note: '9/8 종가 = 100; 9/9 −45%, 9/10 −7%, 9/11 −42%, 9/12 −14% [press]',
  },
  {
    path: 'market.ownCdsBp',
    value: 475,
    unit: 'bp',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'VERIFY',
  },
  // ───────────── 신뢰 ─────────────
  {
    path: 'confidence.index',
    value: 58,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
    note: 'S1 우려 중간: 6월 이후 지속 압박, 9/9 −45%',
  },
  {
    path: 'confidence.depositors',
    value: 55,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
  },
  {
    path: 'confidence.counterparties',
    value: 52,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
  },
  {
    path: 'confidence.regulators',
    value: 50,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
  },
  {
    path: 'confidence.investors',
    value: 45,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'CAL',
  },
  {
    path: 'confidence.media',
    value: 45,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'press-kdb-2008-09-09',
    tag: 'CAL',
  },
  {
    path: 'confidence.board',
    value: 70,
    unit: 'index',
    asOf: '2008-09-09',
    sourceId: 'fcic-report-2011',
    tag: 'CAL',
  },
  // ───────────── 외생 이벤트 크기 (턴 효과) ─────────────
  {
    path: 'event.t2.clearingBankCall',
    value: 5,
    unit: '$B',
    asOf: '2008-09-11',
    sourceId: 'valukas-report-2010',
    note: 'JPM 추가 담보 요구 $5B (9/9 요구 → 9/11 이행)',
  },
  {
    path: 'event.t3.clearingBankCall2',
    value: 5,
    unit: '$B',
    asOf: '2008-09-12',
    sourceId: 'valukas-report-2010',
    tag: 'VERIFY',
    note: 'JPM 2차 추가 담보 요구 $5B (9/11 요구 → 9/12 현금 이행) — Examiner 보고서 인용, 페이지 미확인',
  },
  {
    path: 'event.t0.pdcfPrepositionCapacity',
    value: 20,
    unit: '$B',
    asOf: '2008-09-09',
    sourceId: 'ball-nber-w22410',
    tag: 'CAL',
    note: '브로커딜러가 2주 내 PDCF 앞으로 이동·테스트 가능한 투자등급 미담보 인벤토리 [CAL] (Ball: 적격 담보 ≥$131B)',
  },
  {
    path: 'event.t5.pdcfExpansionCapacity',
    value: 12,
    unit: '$B',
    asOf: '2008-09-14T21:00:00-04:00',
    sourceId: 'fed-pr-2008-09-14',
    tag: 'CAL',
    note: '9/14 담보 확대(트라이파티 적격 전체)로 늘어나는 BD 여력 12(사전 목록 준비 시 20); 9/15 LBI PDCF $28B 차입(Fed History) 자릿수',
  },
  {
    path: 'anchor.bear.liquidityPool',
    value: 18.1,
    unit: '$B',
    asOf: '2008-03-10',
    sourceId: 'sec-cox-basel-2008-03-20',
    tag: 'VERIFY',
    note: '도시에 [미확인] 태그 유지. SEC Cox 서한: 3/10 $18.1B → 3/11 $11.5B → 3/12 $12.4B → 3/13 급감(≈$2B는 2차) — 도시에 갱신 시 해소 가능',
  },
  {
    path: 'anchor.lehman.usablePoolFriday',
    value: 2,
    unit: '$B',
    asOf: '2008-09-12',
    sourceId: 'valukas-report-2010',
    tag: 'VERIFY',
    note: '9/12(금) 즉시 현금화 가능 자산 <$2B (Examiner). 역사 경로 체크포인트: 9/12 누적 유출 ≥35(기대 38), 풀 ≈2',
  },
  {
    path: 'anchor.lehman.chapter11Assets',
    value: 639,
    unit: '$B',
    asOf: '2008-09-15',
    sourceId: 'lehman-10q-2q08',
    tag: 'VERIFY',
    note: '도시에 [2차] 태그 유지. 파산 신청서의 $639B는 5/31 10-Q 총자산',
  },
]
