/**
 * FactLedger — initialState의 모든 숫자 리프를 출처에 연결한다 (docs/authoring-guide.md 저자 체크리스트 1).
 * tag: VERIFY (1차 출처 미확인 — note에 해소 문서 명시) · STYLIZED (선언된 단순화) · CAL (보정 가정, calibration.md)
 * 단위: 조원(KRW 1e12) 외 명시. 시점: T0 = 2023-12-28 09:00 KST.
 */
export interface FactRow {
  path: string
  value: number
  unit: string
  asOf: string
  knownAt?: string
  sourceId: string
  tag?: 'VERIFY' | 'STYLIZED' | 'CAL'
  note?: string
}

const CRPA = 'crpa-2023'
const BRIEF = 'fsc-taeyoung-2023-12-28'
const REG = 'bank-supervision-reg'
const ECOS = 'ecos-817Y002'
const FSR23 = 'bok-fsr-2023-12'

/**
 * 한서은행(가상)의 대차대조표는 **합성**이다. 총자산 98.30 = 부채 88.90 + 자본 9.40이 맞도록
 * 구성했고, 출처가 있는 것은 제도 파라미터(적립률·완충자본·정족수)와 외생 시계열(금리·환율·지수)이다.
 * 합성 기관의 항목에는 STYLIZED 또는 CAL 태그가 붙는다.
 */
export const PF_FACTS: FactRow[] = [
  // ───────── 자산 ─────────
  {
    path: 'institution.cash',
    value: 5.8,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note: '현금·한국은행 지준예치금·예치금. 총자산의 5.9%로 국내 은행 평균 범위 안에서 양식화',
  },
  {
    path: 'institution.securities.afs.marketValue',
    value: 13.6,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note: '국고채·통안채(RP·자금조정대출 적격담보)',
  },
  {
    path: 'institution.securities.afs.bookValue',
    value: 14.3,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: ECOS,
    tag: 'CAL',
    note: '미실현손실 4.9% — 2021~2023년 금리 상승분(국고 3년 1.855% → 3.154%)을 듀레이션 3.1년에 적용한 근사',
  },
  {
    path: 'institution.securities.afs.modDuration',
    value: 3.1,
    unit: 'y',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.securities.afs.pledgedShare',
    value: 0.1,
    unit: 'fraction',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note: '일부는 이미 RP·결제담보로 예치',
  },
  {
    path: 'institution.securities.htm.marketValue',
    value: 6.9,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note: '은행채·공사채·AA 회사채',
  },
  {
    path: 'institution.securities.htm.bookValue',
    value: 7.3,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: ECOS,
    tag: 'CAL',
    note: '미실현손실 5.5% (듀레이션 4.2년)',
  },
  {
    path: 'institution.securities.htm.modDuration',
    value: 4.2,
    unit: 'y',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.securities.htm.pledgedShare',
    value: 0,
    unit: 'fraction',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.loans.retail',
    value: 20.4,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.loans.sme',
    value: 23.2,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.loans.corporate',
    value: 22.4,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note: '대현건설그룹 직접여신 1.28 + PF 사업장대출 4.60(본PF 3.30 + 브릿지 1.30) + 기타 16.52',
  },
  {
    path: 'institution.loans.fi',
    value: 1.1,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.loans.nonPerforming',
    value: 0.48,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note: '고정이하여신 — 총여신 67.5조 대비 0.71%',
  },
  {
    path: 'institution.loans.avgDuration',
    value: 2.9,
    unit: 'y',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.otherAssets',
    value: 4.42,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'CAL',
    note: '유형·무형자산 및 기타자산 — 자산 = 부채 + 자본을 맞추는 잔차',
  },

  // ───────── 예금 세그먼트 ─────────
  {
    path: 'institution.deposits.0.balance', // d1
    value: 34.0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note:
      '보호예금(개인·5천만원 이하). 이 시나리오에는 예금 인출 역학이 없고 LCR 산출에만 쓰인다. ' +
      '경로는 엔진의 점 표기(배열 인덱스)를 쓴다 — `[d1]` 같은 표기는 해석되지 않아 검증에서 빠진다',
  },
  {
    path: 'institution.deposits.1.balance', // d2
    value: 19.0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.deposits.2.balance', // d3
    value: 13.0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.deposits.3.balance', // d4
    value: 5.0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },

  // ───────── 부채·자본 ─────────
  {
    path: 'institution.wholesale.unsecuredShort',
    value: 4.0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note: '은행채(1년 이하)·CD',
  },
  {
    path: 'institution.wholesale.unsecuredLong',
    value: 6.6,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.wholesale.repoL1',
    value: 1.1,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.wholesale.repoL2A',
    value: 0.4,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.wholesale.repoOther',
    value: 0.2,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.wholesale.cbFacilityCapacity',
    value: 3.2,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'CAL',
    note: '한국은행 자금조정대출·RP 적격담보 여력 — 미담보 국고채·통안채 시가의 근사',
  },
  {
    path: 'institution.committed.creditToCorporates',
    value: 4.6,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note: '부외 신용공여 = PF 채무보증·매입확약 1.00 + 일반 한도성 여신 3.60',
  },
  {
    path: 'institution.committed.liquidityToFIs',
    value: 0.4,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.otherLiabilities',
    value: 5.6,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'CAL',
    note: '사채·충당부채·기타부채 — 자산 = 부채 + 자본을 맞추는 잔차',
  },
  {
    path: 'institution.capital.cet1',
    value: 7.6,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: 'fsc-ccyb-2023-05-24',
    tag: 'STYLIZED',
    note: 'CET1 7.60 / RWA 71.00 = 10.70%. 규제 최저는 4.5 + 자본보전완충 2.5 = 7.0%이며 2024-05-01부터 경기대응완충 1.0이 더해져 8.0%가 된다 — 시나리오 구간에서 완충 여력이 2.7%p에서 2.7%p − 1.0%p로 줄어드는 것이 핵심 긴장이다',
  },
  {
    path: 'institution.capital.at1',
    value: 0.8,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.capital.tier2',
    value: 1.0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note: '총자본 9.40 / 71.00 = 13.24%',
  },
  {
    path: 'institution.rwa',
    value: 71.0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note: '총자산 대비 72.2% — 기업여신 비중이 높은 은행의 범위',
  },
  {
    path: 'institution.leverageExposure',
    value: 112.0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note: '총자산 98.30 + 부외 신용환산 — 레버리지비율 (7.60 + 0.80) / 112.00 = 7.50%',
  },
  {
    path: 'institution.fireSaleDiscount',
    value: 0.01,
    unit: 'fraction',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'CAL',
    note: '국고채 블록 매도 할인 — 이 시나리오에서는 증권 매각을 쓰지 않는다',
  },
  {
    path: 'institution.taxRate',
    value: 0.22,
    unit: 'fraction',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'STYLIZED',
    note: '법인세 실효세율. 충당금의 세후 자본 영향 = 적립액 × (1 − 0.22)',
  },

  // ───────── 부동산 PF 포트폴리오 ─────────
  {
    path: 'institution.custom.pfExposure',
    value: 5.6,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: BRIEF,
    tag: 'STYLIZED',
    note: '본PF 3.30 + 브릿지론 1.30 + 채무보증 1.00. 사업장 수 60곳(브릿지 18 · 본PF 42)은 금융위 2023-12-28 보도자료의 실제 구성(브릿지론 18 / 본PF 42, 비주거 17 + 주거 25)을 그대로 따랐다',
  },
  {
    path: 'institution.custom.pfMain',
    value: 3.3,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: BRIEF,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.custom.pfBridge',
    value: 1.3,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: BRIEF,
    tag: 'STYLIZED',
  },
  {
    path: 'institution.custom.pfGuarantee',
    value: 1.0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: BRIEF,
    tag: 'STYLIZED',
    note: '부외 채무보증·매입확약',
  },
  {
    path: 'institution.custom.pfDelinquencyPct',
    value: 0.62,
    unit: '%',
    asOf: '2023-12-28',
    sourceId: 'fsc-pf-status-2024-03-22',
    tag: 'CAL',
    note: "은행권 평균 부동산PF 연체율은 '23.12말 0.35%다. 한서은행은 PF 집중도가 높은 합성 기관이므로 그 1.8배 수준으로 두었다",
  },
  {
    path: 'institution.custom.sitesTotal',
    value: 60,
    unit: 'count',
    asOf: '2023-09-30',
    knownAt: '2023-12-28',
    sourceId: BRIEF,
    note: '금융위 보도자료 도표: 태영PF사업장 60개 = 브릿지론 18 + 본PF 42. 실사 후(2024.4.30) 브릿지 20 / 본PF 40으로 재분류되었고 시나리오 T4가 그 재분류를 재현한다',
  },
  {
    path: 'institution.custom.groupSecured',
    value: 0.86,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: BRIEF,
    tag: 'STYLIZED',
    note: '그룹 직접여신 중 담보부',
  },
  {
    path: 'institution.custom.groupUnsecured',
    value: 0.42,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: BRIEF,
    tag: 'STYLIZED',
    note: '그룹 직접여신 중 무담보(운전자금·한도대출). 기업개선계획에서 출자전환 대상이 되는 몫',
  },

  // ───────── 신고 금융채권 구성 (동의율 산식의 분모) ─────────
  {
    path: 'institution.custom.claimBank',
    value: 7.63,
    unit: '조원',
    asOf: '2024-01-03',
    knownAt: '2024-01-04',
    sourceId: CRPA,
    tag: 'STYLIZED',
    note: '신고 금융채권 18.60조 중 은행권 41.0%. 실제 사례는 채권자 512곳·신고채권 21.7조였다(언론 일치, 1차 미확인 — sources.ts kdb-council-2024-01-11 참조). 합성 그룹은 468곳·18.60조로 양식화했다',
  },
  {
    path: 'institution.custom.claimNbfi',
    value: 5.3,
    unit: '조원',
    asOf: '2024-01-03',
    knownAt: '2024-01-04',
    sourceId: CRPA,
    tag: 'STYLIZED',
    note: '제2금융권(저축은행·캐피탈·상호금융) 28.5%',
  },
  {
    path: 'institution.custom.claimSecurities',
    value: 3.26,
    unit: '조원',
    asOf: '2024-01-03',
    knownAt: '2024-01-04',
    sourceId: CRPA,
    tag: 'STYLIZED',
    note: '증권사 매입확약·신용공여 17.5%. 이 중 1.40조는 사업장 미확정분으로, 산입 범위 결정(T1)의 대상이다',
  },
  {
    path: 'institution.custom.claimInsurance',
    value: 1.67,
    unit: '조원',
    asOf: '2024-01-03',
    knownAt: '2024-01-04',
    sourceId: CRPA,
    tag: 'STYLIZED',
    note: '보험·연기금·공제회 9.0%',
  },
  {
    path: 'institution.custom.claimOther',
    value: 0.74,
    unit: '조원',
    asOf: '2024-01-03',
    knownAt: '2024-01-04',
    sourceId: CRPA,
    tag: 'STYLIZED',
    note: '건설공제조합·기타 4.0%',
  },
  {
    path: 'institution.custom.claimContingent',
    value: 2.7,
    unit: '조원',
    asOf: '2024-01-03',
    knownAt: '2024-01-04',
    sourceId: CRPA,
    tag: 'CAL',
    note: '미확정 우발채무 — 산입 시 증권사 60% / 기타 40%로 배분. 산입 여부가 분모를 18.60 → 21.30조로 바꾼다',
  },

  // ───────── 진행 상태 (모두 0에서 시작) ─────────
  {
    path: 'institution.custom.consentPct',
    value: 0,
    unit: '%',
    asOf: '2023-12-28',
    sourceId: CRPA,
    tag: 'CAL',
    note: '동의율 = 100 × Σ(그룹 채권액 × 동의비율) / Σ(그룹 채권액) + 협의회 당일 확정 부동표. 요건은 총 금융채권액의 4분의 3(제11조제4항·제24조제2항)',
  },
  {
    path: 'institution.custom.securedConsentPct',
    value: 0,
    unit: '%',
    asOf: '2023-12-28',
    sourceId: CRPA,
    tag: 'CAL',
    note: '담보채권 기준 동의율. 채무조정이 포함된 기업개선계획은 담보채권 총액의 4분의 3 이상 보유자 찬성이 별도로 필요하다(제17조제2항). 그룹별 담보부 비중은 은행 0.72 / 제2금융 0.30 / 증권 0.12 / 보험 0.55 / 기타 0.18 [CAL]',
  },
  {
    path: 'institution.custom.provisionsCum',
    value: 0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'CAL',
    note: '누적 대손충당금 적립액(세전). 최저적립률은 정상 0.85 / 요주의 7 / 고정 20 / 회수의문 50 / 추정손실 100%',
  },
  {
    path: 'institution.custom.pfCdSharePct',
    value: 0,
    unit: '%',
    asOf: '2023-12-28',
    sourceId: 'fsc-pf-policy-2024-05-13',
    tag: 'CAL',
    note: '유의·부실우려(C·D) 사업장 비중. 사업성 평가 기준은 2024-05-13에 발표되므로 T6 이전에는 0이다. 업권 전체는 2024.8.29 발표에서 21.0조 / 216.5조 = 9.7%였다',
  },
  {
    path: 'institution.custom.newMoney',
    value: 0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: CRPA,
    tag: 'CAL',
    note: '신규 신용공여 누계. 기촉법 제18조제2항에 따라 법정담보권 다음 순위로 우선 변제된다',
  },
  {
    path: 'institution.custom.selfRescuePledged',
    value: 0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: 'kdb-plan-2024-04-30',
    tag: 'CAL',
    note: '자구안 약정액(장부 기준)',
  },
  {
    path: 'institution.custom.selfRescueDelivered',
    value: 0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: 'kdb-plan-2024-04-30',
    tag: 'CAL',
    note: '실제 도착액. 약정과 도착의 차이가 이 시나리오의 자구안 시차 교훈이다',
  },

  // ───────── 시장 (외생, 실제 기록) ─────────
  {
    path: 'market.policyRateBp',
    value: 350,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: 'bok-base-rate',
    note: '한국은행 기준금리 3.50% (2023-01-13 인상 후 시나리오 전 구간 동결)',
  },
  {
    path: 'market.govt2yBp',
    value: 326.2,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: ECOS,
    note: '국고채 2년 3.262%',
  },
  {
    path: 'market.govt10yBp',
    value: 318.3,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: ECOS,
    note: '국고채 10년 3.183%',
  },
  {
    path: 'market.govt30yBp',
    value: 308.8,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: ECOS,
    note: '국고채 30년 3.088%',
  },
  {
    path: 'market.creditSpreadIgBp',
    value: 74.4,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: ECOS,
    tag: 'CAL',
    note: '회사채 AA- 3년 3.898% − 국고 3년 3.154%',
  },
  {
    path: 'market.creditSpreadHyBp',
    value: 718.8,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: ECOS,
    tag: 'CAL',
    note: '회사채 BBB- 3년 10.342% − 국고 3년 3.154%',
  },
  {
    path: 'market.fundingStressBp',
    value: 49,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: ECOS,
    tag: 'CAL',
    note: 'CP(91일) 4.32% − CD(91일) 3.83%',
  },
  {
    path: 'market.equityIndex',
    value: 2655,
    unit: 'index',
    asOf: '2023-12-28',
    sourceId: 'ecos-802Y001',
    note: '코스피 종가 2,655.28',
  },
  {
    path: 'market.volIndex',
    value: 16,
    unit: 'index',
    asOf: '2023-12-28',
    sourceId: 'ecos-802Y001',
    tag: 'STYLIZED',
    note: 'VKOSPI 근사 — 이 시나리오에서 변동성 지표는 표시용이며 계산에 쓰지 않는다',
  },
  {
    path: 'market.fxUsdLocal',
    value: 1288,
    unit: 'KRW/USD',
    asOf: '2023-12-28',
    sourceId: 'ecos-731Y003',
    note: '원/달러 종가(15:30) 1,288.0',
  },
  {
    path: 'market.ownStock',
    value: 100,
    unit: 'index',
    asOf: '2023-12-28',
    sourceId: 'ecos-802Y001',
    tag: 'STYLIZED',
    note: '합성 지주 주가 지수화(100 = T0). 이 시나리오에서 자사 주가는 계산에 쓰지 않는다',
  },
  {
    path: 'market.custom.govt3y',
    value: 315.4,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: ECOS,
    note: '국고채 3년 3.154%',
  },
  {
    path: 'market.custom.corpAA3y',
    value: 389.8,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: ECOS,
    note: '회사채 AA- 3년 3.898%',
  },
  {
    path: 'market.custom.corpBBB3y',
    value: 1034.2,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: ECOS,
    note: '회사채 BBB- 3년 10.342%',
  },
  {
    path: 'market.custom.cd91',
    value: 383,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: ECOS,
    note: 'CD(91일) 3.83%',
  },
  {
    path: 'market.custom.cp91',
    value: 432,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: ECOS,
    note: 'CP(91일) 4.32%',
  },
  {
    path: 'market.custom.constructionPfSpreadBp',
    value: 420,
    unit: 'bp',
    asOf: '2023-12-28',
    sourceId: 'kofia-abs-stats',
    tag: 'CAL',
    note: '건설사 보증 PF 유동화증권(A2) 가산금리. 공표 일별 계열이 없어 회사채 BBB- 스프레드(718.8bp)와 AA- 스프레드(74.4bp) 사이에서 보정한 값이며, 턴별 경로도 두 계열의 축소폭에 비례시켰다 — calibration.md §7',
  },
  {
    path: 'market.custom.pfSecuritiesDelinqPct',
    value: 13.9,
    unit: '%',
    asOf: '2023-09-30',
    knownAt: '2023-12-28',
    sourceId: FSR23,
    note: "한국은행 금융안정보고서 2023.12 p.38 — 증권회사 부동산PF 연체율 13.9%('23.9말, 전분기 17.3%). T5에 금융위 공표치 13.73%('23.12말)로 갱신된다",
  },
  {
    path: 'market.custom.pfSavingsDelinqPct',
    value: 5.6,
    unit: '%',
    asOf: '2023-09-30',
    knownAt: '2023-12-28',
    sourceId: FSR23,
    note: "같은 문단의 저축은행 5.6%('23.9말). T5에 6.94%('23.12말)로 갱신된다",
  },
  {
    path: 'market.custom.pfSectorLoanTn',
    value: 0,
    unit: '조원',
    asOf: '2023-12-28',
    sourceId: 'fsc-pf-status-2024-03-22',
    tag: 'CAL',
    note: 'T0 시점 미공표 자리표시자. 2024-03-22 금융위·금감원 공표치 135.6조가 T5 진입효과로 채워진다 — 공표 전에 값을 보여 주지 않기 위한 0',
  },
  {
    path: 'market.custom.pfSectorDelinqPct',
    value: 0,
    unit: '%',
    asOf: '2023-12-28',
    sourceId: 'fsc-pf-status-2024-03-22',
    tag: 'CAL',
    note: "T0 시점 미공표 자리표시자. 2024-03-22 공표치 2.70%('23.12말)가 T5에 채워진다",
  },

  // ───────── 신뢰지수 ─────────
  {
    path: 'confidence.index',
    value: 58,
    unit: 'index',
    asOf: '2023-12-28',
    sourceId: FSR23,
    tag: 'CAL',
    note: 'S1(우려) 구간. 한국은행 금융안정보고서 2023.12가 같은 날 "취약요인이 두드러진 부동산PF"라고 평가한 상태에 대응',
  },
  {
    path: 'confidence.counterparties',
    value: 55,
    unit: 'index',
    asOf: '2023-12-28',
    sourceId: FSR23,
    tag: 'CAL',
    note: '채권단·대주단',
  },
  {
    path: 'confidence.regulators',
    value: 54,
    unit: 'index',
    asOf: '2023-12-28',
    sourceId: BRIEF,
    tag: 'CAL',
    note: '금융위·금감원 합동 점검 대상',
  },
  {
    path: 'confidence.depositors',
    value: 68,
    unit: 'index',
    asOf: '2023-12-28',
    sourceId: FSR23,
    tag: 'CAL',
  },
  {
    path: 'confidence.investors',
    value: 52,
    unit: 'index',
    asOf: '2023-12-28',
    sourceId: FSR23,
    tag: 'CAL',
  },
  {
    path: 'confidence.media',
    value: 48,
    unit: 'index',
    asOf: '2023-12-28',
    sourceId: 'press-taeyoung-2023-12-28',
    tag: 'CAL',
  },
  {
    path: 'confidence.board',
    value: 62,
    unit: 'index',
    asOf: '2023-12-28',
    sourceId: REG,
    tag: 'CAL',
  },
]

/** 릴리스 게이트 보조: VERIFY 태그가 붙은 항목 목록. */
export const PF_VERIFY_ITEMS = PF_FACTS.filter((f) => f.tag === 'VERIFY')
