/**
 * 규정 빠른 참조 — 위기 대응 중에 "그 숫자가 몇이었지"를 3초 안에 확인하는 표.
 *
 * 모든 행은 `src/content/frameworks/`의 프레임워크 문서에서 **옮겨 적은 것**이며,
 * 기억에 의존해 다시 쓰지 않는다. `tests/integrity/regulationRefs.test.ts`가
 * ① `frameworkId`·`sourceRef`·`termId`·`cardRef` 해석 가능 여부와
 * ② `threshold`의 첫 숫자가 해당 프레임워크 본문에 실제로 존재하는지를 검사한다(드리프트 가드).
 *
 * `verify: true`는 "프레임워크 문서에는 있으나 1차 출처 원문이 아직 서지에 없거나
 * 플랫폼 보정값인 행"이다. UI는 이 행에 '확인 필요' 표시를 붙인다.
 */
export type RegulationGroup =
  '유동성' | '자본' | '증권·보험·상호금융' | '담보·마진' | '정리·백스톱' | '외환'

export type RegulationSector =
  'bank' | 'securities' | 'insurance' | 'savings' | 'mutual' | 'pension' | 'central_bank'

export interface RegulationRef {
  id: string
  group: RegulationGroup
  region: 'global' | 'korea'
  sectors: RegulationSector[]
  /** 규정 이름(무엇을 규율하는가). */
  rule: string
  /** 수치. 첫 숫자는 프레임워크 본문에 그대로 존재해야 한다. */
  threshold: string
  /** 실무 해석 한 줄. */
  note?: string
  /** 기준 시점. */
  asOf?: string
  /** `src/content/frameworks/<id>.md` */
  frameworkId: string
  /** 그 문서의 `## ` 절 제목. */
  section?: string
  /** `src/content/sources.ts`의 id. */
  sourceRef: string
  /** `src/content/glossary.ts`의 id. */
  termId?: string
  /** 관련 지식카드 id. */
  cardRef?: string
  /** 1차 출처 원문 미확인 또는 플랫폼 보정값. */
  verify?: boolean
}

const RULES = '핵심 규칙과 수치'

export const REGULATION_REFS: RegulationRef[] = [
  // ─────────────────────────── 유동성 ───────────────────────────
  {
    id: 'lcr-min',
    group: '유동성',
    region: 'global',
    sectors: ['bank'],
    rule: 'LCR 최소 기준 (Basel III)',
    threshold: '100%',
    note: '30일 스트레스 순현금유출을 HQLA로 전부 덮어야 한다. 유입은 총유출의 75%까지만 인정.',
    frameworkId: 'basel3-liquidity',
    section: RULES,
    sourceRef: 'bcbs-238',
    termId: 'lcr',
    cardRef: 'lcr-basics',
  },
  {
    id: 'lcr-korea',
    group: '유동성',
    region: 'korea',
    sectors: ['bank'],
    rule: '원화 LCR / 외화 LCR',
    threshold: '100% / 80%',
    note: '원화는 2020.4 85%까지 완화됐다가 2025.1.1 100% 복귀. 국내 세칙은 안정 소매·중소기업 유출률 5%.',
    asOf: '2025.1.1',
    frameworkId: 'korea-crisis-toolkit',
    section: RULES,
    sourceRef: 'fsc-83490',
    termId: 'lcr',
    cardRef: 'lcr-basics',
  },
  {
    id: 'nsfr',
    group: '유동성',
    region: 'global',
    sectors: ['bank'],
    rule: 'NSFR (순안정자금조달비율)',
    threshold: '100% 상시',
    note: '1년 기준 구조 지표라 급성 런을 막지 못한다. 6개월 미만 금융기관 조달(ASF 0%) 의존도를 따로 본다.',
    frameworkId: 'basel3-liquidity',
    section: RULES,
    sourceRef: 'bcbs-d295',
    termId: 'nsfr',
  },
  {
    id: 'hqla-haircut',
    group: '유동성',
    region: 'global',
    sectors: ['bank', 'securities'],
    rule: 'HQLA 등급별 헤어컷·상한',
    threshold: '15% (Level 2A) · 2B RMBS 25% · 2B 회사채·주식 50% · L2 합계 ≤ 40%, 2B ≤ 15%',
    note: 'Level 1은 헤어컷 0%·상한 없음. 규제 인정액과 당일 담보화 가능액을 이중 관리한다.',
    frameworkId: 'basel3-liquidity',
    section: RULES,
    sourceRef: 'basel-lcr30',
    termId: 'hqla',
    cardRef: 'hqla-and-haircuts',
  },
  {
    id: 'runoff-retail',
    group: '유동성',
    region: 'global',
    sectors: ['bank'],
    rule: '30일 유출률 — 안정 소매예금',
    threshold: '5% (추가 요건·관할 승인 시 3%)',
    note: '비안정 소매는 10% 이상. 2023년 런은 이 30일 허용치를 하루 이틀에 소진했다.',
    frameworkId: 'basel3-liquidity',
    section: RULES,
    sourceRef: 'basel-lcr40',
    termId: 'run-off-rate',
    cardRef: 'uninsured-deposits-and-run-speed',
  },
  {
    id: 'runoff-retail-korea',
    group: '유동성',
    region: 'korea',
    sectors: ['bank'],
    rule: '30일 유출률 — 국내 안정 소매·중소기업',
    threshold: '5% (BCBS 기본률)',
    note: '계산기 한국 프리셋(`KR_LCR_PARAMS`)이 이 값을 쓴다.',
    frameworkId: 'basel3-liquidity',
    section: RULES,
    sourceRef: 'fsc-83490',
    termId: 'run-off-rate',
  },
  {
    id: 'runoff-operational',
    group: '유동성',
    region: 'global',
    sectors: ['bank'],
    rule: '30일 유출률 — 운영성 예금',
    threshold: '25% (보험분 5%)',
    note: '결제·커스터디·청산 목적의 예금. 운영성 인정 요건을 못 갖추면 법인 유출률로 떨어진다.',
    frameworkId: 'basel3-liquidity',
    section: RULES,
    sourceRef: 'basel-lcr40',
    termId: 'run-off-rate',
  },
  {
    id: 'runoff-corporate',
    group: '유동성',
    region: 'global',
    sectors: ['bank'],
    rule: '30일 유출률 — 비금융기업·국가·공공기관',
    threshold: '40% (전액 보험 시 20%)',
    frameworkId: 'basel3-liquidity',
    section: RULES,
    sourceRef: 'basel-lcr40',
    termId: 'run-off-rate',
  },
  {
    id: 'runoff-financial',
    group: '유동성',
    region: 'global',
    sectors: ['bank', 'securities'],
    rule: '30일 유출률 — 기타 법인(은행·증권·보험)',
    threshold: '100%',
    note: '금융기관 조달은 30일 안에 전액 나간다고 가정한다 — 규제상 최악이 현실의 하루치다.',
    frameworkId: 'basel3-liquidity',
    section: RULES,
    sourceRef: 'basel-lcr40',
    termId: 'run-off-rate',
  },

  // ─────────────────────────── 자본 ───────────────────────────
  {
    id: 'capital-minimums',
    group: '자본',
    region: 'global',
    sectors: ['bank'],
    rule: 'CET1 / Tier 1 / 총자본 최소',
    threshold: '4.5% / 6% / 8%',
    note: 'CET1 4.5%에 자본보전완충 2.5%를 더한 7.0%가 실질 하한이다.',
    frameworkId: 'capital-framework',
    section: RULES,
    sourceRef: 'bcbs-189',
    termId: 'cet1',
    cardRef: 'economic-vs-regulatory-capital',
  },
  {
    id: 'capital-ccb',
    group: '자본',
    region: 'global',
    sectors: ['bank'],
    rule: '자본보전완충자본(CCB) / 경기대응완충자본(CCyB)',
    threshold: '2.5% / 0~2.5%',
    note: 'CCB를 잠식하면 배당·자사주·성과급이 단계적으로 제한되고, 그 제한 자체가 공개 신호가 된다.',
    frameworkId: 'capital-framework',
    section: RULES,
    sourceRef: 'bcbs-189',
    termId: 'ccb',
  },
  {
    id: 'leverage-ratio',
    group: '자본',
    region: 'global',
    sectors: ['bank'],
    rule: '레버리지비율 (Tier 1 ÷ 총익스포저)',
    threshold: '3%',
    note: '위험가중과 무관한 백스톱. 위험가중치가 낮은 국채·MBS로 자산을 키우면 여기서 먼저 걸린다.',
    frameworkId: 'capital-framework',
    section: RULES,
    sourceRef: 'bcbs-189',
    termId: 'leverage-ratio',
  },
  {
    id: 'korea-dsib',
    group: '자본',
    region: 'korea',
    sectors: ['bank'],
    rule: '한국 D-SIB CET1 / 총자본, CCyB',
    threshold: '9.0% / 12.5%, CCyB 1%',
    note: '5대 지주 + 5대 은행 10개사. CCyB 1%는 2024.5.1부터.',
    asOf: '2026.9',
    frameworkId: 'capital-framework',
    section: RULES,
    sourceRef: 'bcbs-189',
    termId: 'ccyb',
    verify: true,
  },
  {
    id: 'irrbb-outlier',
    group: '자본',
    region: 'global',
    sectors: ['bank'],
    rule: 'IRRBB 이상치(outlier) 기준',
    threshold: '15% — ΔEVE 손실 > Tier 1의 15%',
    note: 'EVE 6개·NII 2개 시나리오. d578(2024.7)로 2026.1.1부터 충격값이 재보정돼 현행 값 확인이 필요하다.',
    frameworkId: 'irrbb-and-securities-accounting',
    section: RULES,
    sourceRef: 'bcbs-d368',
    termId: 'irrbb',
    verify: true,
  },
  {
    id: 'htm-tainting',
    group: '자본',
    region: 'global',
    sectors: ['bank'],
    rule: 'HTM 테인팅 (미국 회계기준)',
    threshold: 'ASC 320-10-35-8 — 잔여 HTM 전액 AFS 재분류',
    note: '유동성 확보 목적의 매각은 예외가 아니다. 매각 전에 "재분류 후 자본"을 감사인과 미리 계산한다.',
    frameworkId: 'irrbb-and-securities-accounting',
    section: RULES,
    sourceRef: 'fasb-asc-320',
    termId: 'htm-tainting',
    cardRef: 'htm-tainting',
  },

  // ─────────────────────────── 증권·보험·상호금융 ───────────────────────────
  {
    id: 'ncr-pca',
    group: '증권·보험·상호금융',
    region: 'korea',
    sectors: ['securities'],
    rule: '증권사 NCR 적기시정조치 문턱',
    threshold: '100% 권고 / 50% 요구 / 0% 명령',
    note: 'NCR = (영업용순자본 − 총위험액) ÷ 필요유지자기자본.',
    frameworkId: 'korea-crisis-toolkit',
    section: RULES,
    sourceRef: 'fsc-86917',
    termId: 'ncr',
    cardRef: 'pf-abcp-commitment-ncr',
  },
  {
    id: 'kr-securities-liquidity',
    group: '증권·보험·상호금융',
    region: 'korea',
    sectors: ['securities'],
    rule: '증권사 유동성비율 (1·3개월)',
    threshold: '100%',
    note: '2026.5 발표 개편안은 2027.1.1부터 49개사 전체로 확대하고 유동자산 헤어컷(AA 7%·A 이하 10%·주식 15%·합성 ETF 30%)과 우발채무 유동부채 편입을 추진한다. 최종 규정·시행 여부는 별도 확인한다.',
    asOf: '2027.1.1 개편',
    frameworkId: 'korea-crisis-toolkit',
    section: RULES,
    sourceRef: 'fsc-86917',
    termId: 'liquidity-ratio-kr',
    cardRef: 'pf-abcp-commitment-ncr',
  },
  {
    id: 'k-ics',
    group: '증권·보험·상호금융',
    region: 'korea',
    sectors: ['insurance'],
    rule: '보험 K-ICS (신지급여력비율)',
    threshold: '법정 100% · 권고 130% · 기본자본 K-ICS 50%',
    note: '기본자본 K-ICS 50%는 2027.1.1 시행(경과 9년) — 자본의 質을 보는 지표다.',
    asOf: '2025 / 2027',
    frameworkId: 'korea-crisis-toolkit',
    section: RULES,
    sourceRef: 'fsc-86032',
    termId: 'k-ics',
  },
  {
    id: 'savings-bank-bis',
    group: '증권·보험·상호금융',
    region: 'korea',
    sectors: ['savings'],
    rule: '저축은행 BIS 비율 / 부동산 한도',
    threshold: '7% (자산 1조 이상 8%) · 건설 30% · 부동산 30% · PF 20% · 합산 50%',
    note: '2011년 부산저축은행은 자본 완전잠식 상태에서 영업정지됐다.',
    frameworkId: 'korea-crisis-toolkit',
    section: RULES,
    sourceRef: 'fsc-71188',
    termId: 'prompt-corrective-action',
    verify: true,
  },
  {
    id: 'mutual-credit',
    group: '증권·보험·상호금융',
    region: 'korea',
    sectors: ['mutual'],
    rule: '상호금융 유동성비율 / 순자본비율 / PF 한도',
    threshold: '100% (자산 1천억 이상) · 순자본 최소 4% · PF 총대출 20%',
    note: '유동성비율은 2025.12.29 완전 적용, 순자본 4%는 2028~31 단계, PF 20%는 2027.4.1.',
    asOf: '2025.12.29~',
    frameworkId: 'korea-crisis-toolkit',
    section: RULES,
    sourceRef: 'fsc-87126',
    cardRef: 'mutual-credit-deposit-protection',
  },

  // ─────────────────────────── 담보·마진 ───────────────────────────
  {
    id: 'ldi-buffer',
    group: '담보·마진',
    region: 'global',
    sectors: ['pension'],
    rule: 'LDI 최소 회복력 버퍼 (영란은행 FPC 권고)',
    threshold: '250bp',
    note: 'TPR 가이드는 250bp 시장 스트레스 버퍼에 운영 버퍼를 더하고 담보 보충 5일을 가정한다. 업계는 사후 300~400bp를 유지했다.',
    asOf: '2023.3.29',
    frameworkId: 'margin-and-collateral-mechanics',
    section: RULES,
    sourceRef: 'boe-ldi-staff-paper-2023',
    termId: 'collateral-buffer',
    cardRef: 'ldi-leverage-buffer-250bp',
  },
  {
    id: 'basel-haircuts',
    group: '담보·마진',
    region: 'global',
    sectors: ['bank', 'securities'],
    rule: 'Basel 표준 담보 헤어컷 — 국채 AAA~AA',
    threshold: '0.5 / 2 / 4% (≤1년 / 1~5년 / >5년)',
    note: '주요지수 주식·금 20%, 기타 상장주식 30%, FX 불일치 8%. CRE22.49 원문 파싱 실패로 텍스트 기준값이다.',
    frameworkId: 'margin-and-collateral-mechanics',
    section: RULES,
    sourceRef: 'cgfs-36',
    termId: 'haircut',
    cardRef: 'hqla-and-haircuts',
    verify: true,
  },
  {
    id: 'market-haircuts',
    group: '담보·마진',
    region: 'global',
    sectors: ['bank', 'securities'],
    rule: '시장 관행 헤어컷 — IG 회사채 / 주식',
    threshold: '5~10% / 15~25%',
    note: '미국 트라이파티 레포는 약 2%, 비청산 양자 국채 레포는 다수 0%. 스트레스에서는 +5~10%p로 재계산한다.',
    frameworkId: 'margin-and-collateral-mechanics',
    section: RULES,
    sourceRef: 'cgfs-36',
    termId: 'repo',
    cardRef: 'tri-party-repo-run',
  },
  {
    id: 'kr-liquid-haircut-2027',
    group: '담보·마진',
    region: 'korea',
    sectors: ['securities'],
    rule: '증권사 유동자산 헤어컷 (2027.1.1)',
    threshold: 'AAA 0% · AA 7% · A 이하 10% · 주식 15% · 합성 ETF 30%',
    asOf: '2027.1.1',
    frameworkId: 'margin-and-collateral-mechanics',
    section: RULES,
    sourceRef: 'fsc-86917',
    termId: 'haircut',
  },

  // ─────────────────────────── 정리·백스톱 ───────────────────────────
  {
    id: 'discount-window',
    group: '정리·백스톱',
    region: 'global',
    sectors: ['bank'],
    rule: '재할인창구 1차 신용 / 2차 신용',
    threshold: '+50bp (등급 강등 시 2차 신용 전환)',
    note: '미예치 담보는 1영업일 이상 걸리고 FHLB 리엔 해제가 선행돼야 한다. 비시스템 상황의 창구 사용에는 낙인(ΔCI −3)이 붙는다 — 플랫폼 보정값.',
    frameworkId: 'contingency-funding-plan',
    section: RULES,
    sourceRef: 'fed-sr-10-6',
    termId: 'discount-window',
    cardRef: 'discount-window-fhlb-btfp',
    verify: true,
  },
  {
    id: 'btfp',
    group: '정리·백스톱',
    region: 'global',
    sectors: ['bank'],
    rule: 'BTFP 조건 (2023.3.12 창설)',
    threshold: '액면(par) 평가 · 1년 OIS+10bp 고정 · 최장 1년 · 수수료 없음',
    note: '시가가 액면을 크게 밑돌아도 액면 100%로 차입할 수 있었다. 다만 임시 시설은 발표 전에 계획에 넣을 수 없다.',
    asOf: '2023.3.12',
    frameworkId: 'resolution-and-backstops',
    section: RULES,
    sourceRef: 'fed-btfp-term-sheet-2023',
    termId: 'btfp',
    cardRef: 'discount-window-fhlb-btfp',
  },
  {
    id: 'fdic-tools',
    group: '정리·백스톱',
    region: 'global',
    sectors: ['bank'],
    rule: 'FDIC 정리 도구 — 최소비용 원칙과 시스템리스크 예외',
    threshold: 'P&A 4유형 · 브릿지뱅크 · DINB · SRE',
    note: '금요일 폐쇄부터 월요일 개장까지 약 60시간. 인수자 게이트를 못 넘으면 P&A가 아니라 DINB·청산이다.',
    frameworkId: 'resolution-and-backstops',
    section: RULES,
    sourceRef: 'fdic-pr-16-2023',
    termId: 'systemic-risk-exception',
    cardRef: 'fdic-resolution-weekend',
  },
  {
    id: 'swiss-ela-plb',
    group: '정리·백스톱',
    region: 'global',
    sectors: ['bank'],
    rule: '스위스 ELA·ELA+·PLB (2023.3)',
    threshold: '총 CHF 168B (ELA 38 + LSFF 10 + ELA+ 50 + PLB 70)',
    note: 'UBS 인수 CHF 3B, AT1 CHF 16.5B 전액 상각. 연방보증 CHF 100B(SNB) + 9B(UBS).',
    asOf: '2023.3',
    frameworkId: 'resolution-and-backstops',
    section: RULES,
    sourceRef: 'finma-cs-report-2023',
    termId: 'plb',
  },
  {
    id: 'bok-act-65',
    group: '정리·백스톱',
    region: 'korea',
    sectors: ['bank', 'securities'],
    rule: '한국은행법 제65조 긴급여신',
    threshold: '금통위 4명 이상 찬성 (정부 의견 청취)',
    note: '제80조 영리기업 여신도 4명 이상. 비은행은 한은 RP 대상기관 여부에 따라 증금·산은·은행권 RP로 우회해야 한다.',
    frameworkId: 'korea-crisis-toolkit',
    section: RULES,
    sourceRef: 'bok-act',
    cardRef: 'korea-crisis-toolkit',
  },
  {
    id: 'bond-fund',
    group: '정리·백스톱',
    region: 'korea',
    sectors: ['bank', 'securities'],
    rule: '채권시장안정펀드 (채안펀드)',
    threshold: '20조원 (2022.10 대책의 채안펀드 규모)',
    note: '캐피탈콜 방식으로 조성한다. 2022.10의 50조원+α는 채안펀드·정책금융·보증 등을 합친 전체 대책 규모이며 펀드 자체 규모가 아니다.',
    asOf: '2022.10',
    frameworkId: 'korea-crisis-toolkit',
    section: RULES,
    sourceRef: 'fsc-2022-10-23',
    termId: 'bond-stabilization-fund',
    cardRef: 'korea-crisis-toolkit',
  },
  {
    id: 'deposit-insurance-kr',
    group: '정리·백스톱',
    region: 'korea',
    sectors: ['bank', 'savings', 'mutual'],
    rule: '예금자보호 한도 (한국)',
    threshold: '1억원 (1인당 금융회사별)',
    note: 'DC/IRP·연금저축·사고보험금은 각각 별도 1억원. 농협·수협·신협·새마을금고·산림조합은 예보가 아닌 중앙회 기금이 보호한다.',
    asOf: '2025.9.1',
    frameworkId: 'korea-crisis-toolkit',
    section: RULES,
    sourceRef: 'korea-kr-deposit-limit-2025',
    termId: 'deposit-insurance-limit',
    cardRef: 'mutual-credit-deposit-protection',
  },
  {
    id: 'kdic-premium',
    group: '정리·백스톱',
    region: 'korea',
    sectors: ['bank', 'securities', 'insurance', 'savings'],
    rule: '예금보험료율',
    threshold: '은행 0.08% · 금투·보험 0.15% · 저축은행 0.40% (상한 0.5%)',
    note: '상한 0.5%는 2027.12.31까지. 정리 방식 선택 시 기금 분담 구조와 함께 본다.',
    frameworkId: 'korea-crisis-toolkit',
    section: RULES,
    sourceRef: 'korea-kr-deposit-limit-2025',
    verify: true,
  },

  // ─────────────────────────── 외환 ───────────────────────────
  {
    id: 'fx-forward-position',
    group: '외환',
    region: 'korea',
    sectors: ['bank'],
    rule: '선물환포지션 한도',
    threshold: '국내은행 75% / 외은지점 375%',
    note: '외환 거시건전성 3종 중 하나. 외화 LCR 80%, 외환건전성부담금은 2026.1.6부터 면제.',
    asOf: '2024.12.20',
    frameworkId: 'korea-crisis-toolkit',
    section: RULES,
    sourceRef: 'fsc-83490',
    verify: true,
  },
  {
    id: 'guidotti',
    group: '외환',
    region: 'global',
    sectors: ['central_bank'],
    rule: 'Guidotti(그린스펀-기도티) 비율',
    threshold: '100% 이상',
    note: '가용보유액 ÷ 잔존만기 1년 이하 외채. 헤드라인 보유액이 아니라 가용보유액으로 계산한다.',
    frameworkId: 'fx-crisis-toolkit',
    section: RULES,
    sourceRef: 'audit-fx-crisis-1998',
    termId: 'usable-fx-reserves',
    cardRef: 'korea-crisis-toolkit',
    verify: true,
  },
  {
    id: 'import-cover',
    group: '외환',
    region: 'global',
    sectors: ['central_bank'],
    rule: '수입 커버 / IMF ARA 비율',
    threshold: '3개월 이상 / ARA 100~150% 적정',
    note: 'ARA 2015 가중치(변동환율: 단기외채 30 + 기타부채 15 + 광의통화 5 + 수출 5%)는 엔진 구현값이다.',
    frameworkId: 'fx-crisis-toolkit',
    section: RULES,
    sourceRef: 'audit-fx-crisis-1998',
    termId: 'short-term-external-debt',
    verify: true,
  },
]

const byId = new Map(REGULATION_REFS.map((r) => [r.id, r]))

export function getRegulationRef(id: string): RegulationRef | undefined {
  return byId.get(id)
}

export const REGULATION_GROUPS: RegulationGroup[] = [
  '유동성',
  '자본',
  '증권·보험·상호금융',
  '담보·마진',
  '정리·백스톱',
  '외환',
]

export const SECTOR_LABELS: Record<RegulationSector, string> = {
  bank: '은행',
  securities: '증권',
  insurance: '보험',
  savings: '저축은행',
  mutual: '상호금융',
  pension: '연기금',
  central_bank: '중앙은행',
}

/** 첫 숫자 토큰(드리프트 가드와 UI 강조가 함께 쓴다). */
export function firstNumericToken(threshold: string): string | undefined {
  return /\d+(?:[.,]\d+)?/.exec(threshold)?.[0]
}
