import type { Source } from './types'

/**
 * 공유 서지(shared bibliography). 지식카드·용어집·시나리오가 `[출처: <id>]`로 참조한다.
 * 근거: docs/research/*.md 도시에. URL은 공식 사이트에서 확인한 것만 기재하고, 미확인 URL은 비워 둔다.
 * 날짜는 문서 발행일(YYYY-MM-DD; 월까지만 확인된 경우 YYYY-MM).
 */
export const SOURCES: Source[] = [
  {
    id: 'fdic-fdia-section38',
    title: 'Federal Deposit Insurance Act, Section 38 — Prompt Corrective Action',
    date: '현행본 확인 2026-09-14',
    publisher: 'FDIC',
    url: 'https://www.fdic.gov/federal-deposit-insurance-act/section-38-prompt-corrective-action',
    kind: 'regulatory',
    note: '중대한 자본부족 후 원칙적으로 90일 이내 관재·관리인 지정 또는 법정 대체조치. 게임의 자동 종료 규칙과 구분한다.',
  },
  {
    id: 'fed-pca-20843',
    title: 'Regulation H, Section 208.43 — Capital Measures and Capital-Category Definitions',
    date: '현행본 확인 2026-09-14',
    publisher: 'Federal Reserve',
    url: 'https://www.federalreserve.gov/frrs/regulations/section-20843-capital-measures-and-capital-category-definitions.htm',
    kind: 'regulatory',
    note: 'Critically undercapitalized는 규제상 tangible equity / total assets 2% 이하. CET1 기반 경제적 TCE나 게임 레버리지 비율과 동일하지 않다.',
  },
  // ───────────────────────── 2023 미국 은행 위기 (svb-2023) ─────────────────────────
  {
    id: 'fed-svb-review-2023',
    title:
      "Review of the Federal Reserve's Supervision and Regulation of Silicon Valley Bank (Barr 리뷰)",
    publisher: 'Board of Governors of the Federal Reserve System',
    date: '2023-04-28',
    url: 'https://www.federalreserve.gov/publications/files/svb-review-20230428.pdf',
    pages: 'p.72, 78 (ILST 위반·가정 완화)',
    kind: 'regulatory',
    note: 'SVB 경영 실패·감독 미흡·2019 tailoring 평가, ILST 30일 부족 반복, AOCI 옵트아웃, HTM 취급 재평가',
  },
  {
    id: 'svb-8k-2023',
    title: 'SVB Financial Group, Form 8-K (AFS 매각·증자 발표)',
    publisher: 'SVB Financial Group / U.S. SEC EDGAR',
    date: '2023-03-08',
    kind: 'primary',
    note: 'AFS ~$21B 매각, 세후 손실 ~$1.8B, $2.25B 증자(보통주 1.25 + 전환우선주 0.5 + GA 0.5)',
  },
  {
    id: 'dfpi-svb-order-2023',
    title: 'Order Taking Possession of Property and Business of Silicon Valley Bank',
    publisher: 'California Department of Financial Protection and Innovation (DFPI)',
    date: '2023-03-10',
    url: 'https://dfpi.ca.gov/wp-content/uploads/sites/337/2023/03/DFPI-Orders-Silicon-Valley-Bank-03102023.pdf',
    kind: 'primary',
    note: '3/9 예금 인출 $42B, 마감 시 현금잔고 약 −$958M, 유동성 부족·지급불능을 이유로 폐쇄 및 FDIC 관재인 지정',
  },
  {
    id: 'fdic-pr-16-2023',
    title:
      'FDIC Creates a Deposit Insurance National Bank of Santa Clara to Protect Insured Depositors of Silicon Valley Bank (PR-16-2023)',
    publisher: 'Federal Deposit Insurance Corporation (FDIC)',
    date: '2023-03-10',
    url: 'https://www.fdic.gov/news/press-releases/2023/pr23016.html',
    kind: 'regulatory',
    note: 'DINB 설립, 부보예금자 보호 절차, 관재 개시',
  },
  {
    id: 'fed-btfp-term-sheet-2023',
    title: 'Bank Term Funding Program — Term Sheet',
    publisher: 'Board of Governors of the Federal Reserve System',
    date: '2023-03-12',
    url: 'https://www.federalreserve.gov/newsevents/pressreleases/files/monetary20230312a1.pdf',
    kind: 'primary',
    note: '액면(par) 담보 평가, 1년 OIS+10bp 고정금리, 최장 1년, 수수료 없음, 조기상환 가능, 3/12 보유 증권 대상, ESF $25B 백스톱',
  },
  {
    id: 'fdic-oig-signature-2023',
    title: 'Material Loss Review of Signature Bank of New York (EVAL-24-02)',
    publisher: 'FDIC Office of Inspector General',
    date: '2023-10-23',
    url: 'https://www.fdicoig.gov/sites/default/files/reports/2023-10/EVAL-24-02.pdf',
    kind: 'regulatory',
    note: '유동성·비상자금조달 메커니즘 불충분; CFP 발동에도 일일 현금흐름 보고·담보 테스트 부재; PCA 이행 평가',
  },
  {
    id: 'fdic-frc-supervision-2023',
    title: "FDIC's Supervision of First Republic Bank",
    publisher: 'Federal Deposit Insurance Corporation (FDIC)',
    date: '2023-09-08',
    kind: 'regulatory',
    note: '퍼스트리퍼블릭 감독 사후평가; 등급 강등이 최종대부자(재할인창구) 접근을 차단한 경위. URL 미확인',
  },
  {
    id: 'bcbs-d555',
    title: 'Report on the 2023 banking turmoil',
    publisher: 'Basel Committee on Banking Supervision (BCBS)',
    date: '2023-10-05',
    url: 'https://www.bis.org/bcbs/publ/d555.pdf',
    kind: 'regulatory',
    note: 'SVB·시그니처·FRC 실패와 CS 구제의 원인·대응·초기 교훈; 금리·유동성·집중 리스크 관리 실패',
  },
  {
    id: 'fsb-depositor-behaviour-2024',
    title:
      'Depositor Behaviour and Interest Rate and Liquidity Risks in the Financial System: Lessons from the March 2023 banking turmoil',
    publisher: 'Financial Stability Board (FSB)',
    date: '2024-10-23',
    url: 'https://www.fsb.org/2024/10/depositor-behaviour-and-interest-rate-and-liquidity-risks-in-the-financial-system-lessons-from-the-march-2023-banking-turmoil/',
    kind: 'regulatory',
    note: '런 속도: 상위 3개 런 일 20~30%, 중위 7%/일(과거 1%/일), SVB 계획분 포함 >80%; fast-fail 시나리오, 소셜미디어 모니터링',
  },
  {
    id: 'fed-sr-10-6',
    title:
      'SR 10-6: Interagency Policy Statement on Funding and Liquidity Risk Management (2023.8 개정)',
    publisher: 'Board of Governors of the Federal Reserve System',
    date: '2010-03-17',
    url: 'https://www.federalreserve.gov/boarddocs/srletters/2010/sr1006.htm',
    kind: 'regulatory',
    note: '미국 유동성 리스크 관리·CFP 감독 기준; 2023.8.1 개정으로 CFP 부록 첨부',
  },
  {
    id: 'interagency-cfp-addendum-2023',
    title:
      'Addendum to the Interagency Policy Statement on Funding and Liquidity Risk Management: Importance of Contingency Funding Plans',
    publisher: 'Federal Reserve · FDIC · OCC · NCUA',
    date: '2023-07-28',
    url: 'https://www.federalreserve.gov/newsevents/pressreleases/files/bcreg20230728a1.pdf',
    kind: 'regulatory',
    note: 'CFP 주기적 검토·테스트, 재할인창구 운영 준비(담보 사전 예치·주기적 테스트 거래)를 CFP에 포함',
  },
  {
    id: 'fasb-asc-320',
    title: 'ASC 320-10-35-8, Investments — Debt Securities (HTM 매각·재분류, tainting)',
    publisher: 'Financial Accounting Standards Board (FASB)',
    date: '2009-07-01',
    kind: 'primary',
    note: 'HTM 매각·재분류 시 잔여 HTM 포트폴리오 전체의 AFS 재분류(tainting); 예외 사유. 자행 런은 예외 가능, 타행 런은 불가(Deloitte 해석)',
  },

  // ───────────────────────── 2023 크레디트스위스 ─────────────────────────
  {
    id: 'finma-cs-report-2023',
    title: 'Lessons Learned from the CS Crisis',
    publisher: 'Swiss Financial Market Supervisory Authority (FINMA)',
    date: '2023-12-19',
    url: 'https://www.finma.ch/en/~/media/finma/dokumente/dokumentencenter/myfinma/finma-publikationen/cs-bericht/20231219-finma-bericht-cs.pdf',
    kind: 'regulatory',
    note: 'CS 일별 유출(3/15~17 CHF 13.2/17.1/10.1B), ELA·ELA+·PLB, FINMA 5개 선택지, AT1 CHF 16.5B 상각, UBS 인수',
  },

  // ───────────────────────── Basel 규제 조문 ─────────────────────────
  {
    id: 'bcbs-238',
    title: 'Basel III: The Liquidity Coverage Ratio and liquidity risk monitoring tools',
    publisher: 'Basel Committee on Banking Supervision (BCBS)',
    date: '2013-01',
    url: 'https://www.bis.org/publ/bcbs238.pdf',
    kind: 'regulatory',
    note: 'LCR 정의(HQLA/30일 순현금유출 ≥100%), HQLA 등급·헤어컷·상한, 유출률',
  },
  {
    id: 'basel-lcr30',
    title: 'Basel Framework LCR30 — High-quality liquid assets',
    publisher: 'Bank for International Settlements (Basel Framework)',
    date: '2019-12',
    url: 'https://www.bis.org/basel_framework/chapter/LCR/30.htm',
    kind: 'regulatory',
    note: 'HQLA L1 0% / 2A 15% / 2B RMBS 25% / 2B 회사채·주식 50% 헤어컷, L2 ≤40%·2B ≤15% 상한',
  },
  {
    id: 'basel-lcr40',
    title: 'Basel Framework LCR40 — Cash inflows and outflows',
    publisher: 'Bank for International Settlements (Basel Framework)',
    date: '2019-12',
    url: 'https://www.bis.org/basel_framework/chapter/LCR/40.htm',
    kind: 'regulatory',
    note: '30일 유출률: 안정 소매 기본 5%(추가 요건·관할 승인 시 3%), 비안정 소매 10%+, 운영성 25%, 비금융기업·국가·PSE 40%, 기타 법인 100%, 담보조달 0~100%',
  },
  {
    id: 'bcbs-d295',
    title: 'Basel III: the net stable funding ratio',
    publisher: 'Basel Committee on Banking Supervision (BCBS)',
    date: '2014-10',
    url: 'https://www.bis.org/bcbs/publ/d295.pdf',
    kind: 'regulatory',
    note: 'NSFR ≥100% 상시, 1년 기준(가용안정자금/필요안정자금)',
  },
  {
    id: 'bcbs-189',
    title: 'Basel III: A global regulatory framework for more resilient banks and banking systems',
    publisher: 'Basel Committee on Banking Supervision (BCBS)',
    date: '2010-12',
    url: 'https://www.bis.org/publ/bcbs189.pdf',
    kind: 'regulatory',
    note: 'CET1 4.5% / T1 6% / 총자본 8%, 자본보전완충자본 2.5%, 경기대응완충자본 0~2.5%, 레버리지비율(2011.6 개정판)',
  },
  {
    id: 'bcbs-d368',
    title: 'Interest rate risk in the banking book (IRRBB)',
    publisher: 'Basel Committee on Banking Supervision (BCBS)',
    date: '2016-04',
    url: 'https://www.bis.org/bcbs/publ/d368.pdf',
    kind: 'regulatory',
    note: 'EVE 6개 금리 시나리오, NII 2개 시나리오, 이상치 기준 ΔEVE > Tier1의 15%; d578(2024.7)로 2026.1.1부터 충격값 재보정',
  },
  {
    id: 'bcbs-144',
    title: 'Principles for Sound Liquidity Risk Management and Supervision',
    publisher: 'Basel Committee on Banking Supervision (BCBS)',
    date: '2008-09',
    url: 'https://www.bis.org/publ/bcbs144.pdf',
    pages: 'Principle 11, ¶110~117 (CFP)',
    kind: 'regulatory',
    note: '비상자금조달계획(CFP)의 구성요소: 책임·발동·에스컬레이션, 조치 목록(금액·리드타임), 스트레스테스트 연계, 커뮤니케이션, 중앙은행 창구·담보',
  },
  {
    id: 'cgfs-36',
    title: 'The role of margin requirements and haircuts in procyclicality (CGFS Papers No 36)',
    publisher: 'Committee on the Global Financial System (BIS)',
    date: '2010-03',
    url: 'https://www.bis.org/publ/cgfs36.pdf',
    kind: 'regulatory',
    note: '시장 관행 헤어컷 참고값: IG 회사채 5~10%, 주식 15~25%',
  },

  // ───────────────────────── 2022 영국 LDI ─────────────────────────
  {
    id: 'boe-qb-2023-gilt',
    title: 'Financial stability buy/sell tools: a gilt market case study (Quarterly Bulletin 2023)',
    publisher: 'Bank of England',
    date: '2023-11-20',
    url: 'https://www.bankofengland.co.uk/quarterly-bulletin/2023/2023/financial-stability-buy-sell-tools-a-gilt-market-case-study',
    kind: 'regulatory',
    note: '2022.9.28~10.14 임시 길트 매입(최대 £65bn, 실집행 £19.3bn), 설계 원칙, 파이어세일 역학',
  },
  {
    id: 'boe-ldi-staff-paper-2023',
    title: 'Bank staff paper: LDI minimum resilience — recommendation and explainer',
    publisher: 'Bank of England (Financial Policy Committee)',
    date: '2023-03-29',
    url: 'https://www.bankofengland.co.uk/financial-policy-summary-and-record/2023/bank-staff-paper-ldi-minimum-resilience',
    kind: 'regulatory',
    note: 'LDI 펀드 최소 회복력 기준 250bp; 30년 길트 일일 35bp 초과 상승 2회(2000년 이후 최대 29bp)',
  },
  {
    id: 'tpr-ldi-guidance-2023',
    title: 'Using leveraged liability-driven investment (LDI 가이드)',
    publisher: 'The Pensions Regulator (TPR)',
    date: '2023-04-24',
    url: 'https://www.thepensionsregulator.gov.uk/en/document-library/scheme-management-detailed-guidance/funding-and-investment-detailed-guidance/liability-driven-investment',
    kind: 'regulatory',
    note: '시장 스트레스 버퍼 250bp + 운영 버퍼, 담보 보충 5일 가정',
  },
  {
    id: 'boe-breeden-2022',
    title:
      'Risks from leverage: how did a small corner of the pensions industry threaten financial stability? (Sarah Breeden 연설)',
    publisher: 'Bank of England',
    date: '2022-11-07',
    kind: 'regulatory',
    note: '13일간 LDI 펀드 담보 조달 >£40bn, 길트 매도 >£30bn. URL 미확인',
  },
  {
    id: 'imf-wp-2023-210',
    title:
      "Putting Out the NBFIRE: Lessons from the UK's Liability-Driven Investment (LDI) Crisis (WP/23/210)",
    publisher: 'International Monetary Fund',
    date: '2023-09-29',
    url: 'https://www.imf.org/en/publications/wp/issues/2023/09/29/putting-out-the-nbfire-lessons-from-the-uk-s-liability-driven-investment-ldi-crisis-539683',
    kind: 'academic',
    note: '마진콜 추정 ≈£70bn, 길트 매도 추정 ≈£37bn, 30년 길트 9/23~27 +140bp(IMF 기준)',
  },

  // ───────────────────────── 2008 GFC · 1998 LTCM · 2021 아케고스 ─────────────────────────
  {
    id: 'fcic-report-2011',
    title: 'The Financial Crisis Inquiry Report',
    publisher: 'Financial Crisis Inquiry Commission (FCIC)',
    date: '2011-01',
    url: 'https://www.govinfo.gov/content/pkg/GPO-FCIC/pdf/GPO-FCIC.pdf',
    pages: 'ch.15, ch.18',
    kind: 'primary',
    note: '베어스턴스·리먼 실패 메커니즘: 트라이파티 레포 일중 신용과 청산은행 담보 요구, 레포 롤오버 거부',
  },
  {
    id: 'fed-history-ltcm',
    title: 'Near Failure of Long-Term Capital Management',
    publisher: 'Federal Reserve History (Federal Reserve Bank of Richmond)',
    date: '2013-11',
    url: 'https://www.federalreservehistory.org/essays/ltcm-near-failure',
    kind: 'regulatory',
    note: '1998.9.23 FRBNY 소집, 14개사 $3.6B 출자(지분 90%), 연준 자금 미투입',
  },
  {
    id: 'pwg-hedge-funds-1999',
    title: 'Hedge Funds, Leverage, and the Lessons of Long-Term Capital Management',
    publisher: "President's Working Group on Financial Markets",
    date: '1999-04-28',
    url: 'https://home.treasury.gov/system/files/236/hedgfund.pdf',
    kind: 'regulatory',
    note: 'LTCM 자산 >$125B(레버리지 >25:1), 명목 파생 ≈$1.4T, 카운터파티 >75; 과도한 레버리지의 시스템 리스크',
  },
  {
    id: 'sec-pr-2022-70',
    title:
      'SEC Charges Archegos and its Founder with Massive Market Manipulation Scheme (Press Release 2022-70)',
    publisher: 'U.S. Securities and Exchange Commission',
    date: '2022-04-27',
    url: 'https://www.sec.gov/news/press-release/2022-70',
    kind: 'regulatory',
    note: '아케고스 TRS 기반 집중 포지션·복수 PB 은폐 기소',
  },
  {
    id: 'paul-weiss-cs-archegos-2021',
    title:
      'Credit Suisse Group Special Committee of the Board of Directors — Report on Archegos Capital Management',
    publisher: 'Paul, Weiss, Rifkind, Wharton & Garrison LLP',
    date: '2021-07-29',
    url: 'https://www.paulweiss.com/practices/litigation/internal-investigations/news/credit-suisse-publishes-independent-review-of-archegos-losses?id=40637',
    kind: 'primary',
    note: 'CS 스왑 마진 ~20%→7.5%(2019)→<6%(2020.9), PE 한도 $20m 10배 초과, $530m 미대응; 경영·통제의 근본적 실패; 23명 징계·$70m 환수',
  },

  // ───────────────────────── 2020.3 dash for cash ─────────────────────────
  {
    id: 'fsb-holistic-review-2020',
    title: 'Holistic Review of the March Market Turmoil',
    publisher: 'Financial Stability Board (FSB)',
    date: '2020-11-17',
    url: 'https://www.fsb.org/2020/11/holistic-review-of-the-march-market-turmoil/',
    kind: 'regulatory',
    note: '2020.3 펀드 유출, MMF 런, 베이시스 트레이드 청산, CCP 증거금 급증',
  },
  {
    id: 'sec-mmf-reforms-2023',
    title: 'Money Market Fund Reforms (Final Rule, Release No. 33-11211)',
    publisher: 'U.S. Securities and Exchange Commission',
    date: '2023-07-12',
    kind: 'regulatory',
    note: '게이트 폐지, DLA 10→25%·WLA 30→50%, 기관 프라임 일일 순환매 >5% 시 의무 유동성 수수료. URL 미확인',
  },

  // ───────────────────────── 스트레스테스트 ─────────────────────────
  {
    id: 'fed-stress-scenarios-2026',
    title: '2026 Stress Test Scenarios (Severely Adverse)',
    publisher: 'Board of Governors of the Federal Reserve System',
    date: '2026-02-04',
    url: 'https://www.federalreserve.gov/publications/2026-stress-test-scenarios.htm',
    kind: 'regulatory',
    note: '실질 GDP −4.6%, 실업률 10%, 주택 −30%, CRE −39%, 주가 −58%, VIX 72, 10y −1.8pp(디플레형)',
  },
  {
    id: 'eba-stress-test-2025',
    title: '2025 EU-wide Stress Test — Results',
    publisher: 'European Banking Authority (EBA)',
    date: '2025-08-01',
    url: 'https://www.eba.europa.eu/publications-and-media/publications/2025-eu-wide-stress-test-results',
    kind: 'regulatory',
    note: '실질 GDP −6.3% 누적(2024→27), 실업률 +5.8~6.1pp, 주가 −50%(1년차), 인플레 5.0/3.5/1.9%',
  },

  // ───────────────────────── 한국: 금융위원회 보도자료 ─────────────────────────
  {
    id: 'fsc-2022-10-23',
    title: '비상거시경제금융회의 개최 결과 — 50조원+α 유동성 공급 프로그램',
    publisher: '기획재정부·관계기관 합동',
    date: '2022-10-23',
    url: 'https://www.korea.kr/briefing/pressReleaseView.do?newsId=156532094',
    kind: 'regulatory',
    note: '전체 대책과 채안펀드 20조원 규모를 구분. 펀드 미투자 여유재원 1.6조원 우선 가동.',
  },
  {
    id: 'fsc-78804',
    title:
      '[보도참고] 금융시장 점검·소통회의 개최 — 유동성 지원조치 현황 공유 및 금융업권의 대응노력 논의',
    publisher: '금융위원회',
    date: '2022-10-28',
    url: 'https://www.fsc.go.kr/no010101/78804',
    kind: 'regulatory',
    note: '2022.10.23 「50조원+α」 시장안정대책(채안펀드·산은 CP·증금 RP·한은 RP 6조) 집행 현황 점검',
  },
  {
    id: 'fsc-80034',
    title: '[보도자료] 부동산 PF 관련 증권사發 불안요인 선제적으로 차단한다',
    publisher: '금융위원회',
    date: '2023-05-24',
    url: 'https://www.fsc.go.kr/no010101/80034',
    kind: 'regulatory',
    note: '증권사 보증 PF 유동화증권의 대출 전환 4.9조',
  },
  {
    id: 'fsc-80363',
    title: '[부처합동] 새마을금고는 안전하며 정부는 이를 충분히 뒷받침할 계획',
    publisher: '금융위원회 (범정부 실무지원단: 행안부·금융위·예보 등)',
    date: '2023-07-10',
    url: 'https://www.fsc.go.kr/no010101/80363',
    kind: 'regulatory',
    note: '부실 우려 금고는 우량금고로 P&A → 5천만원 초과 예금도 전액 보장, 필요시 정부 차입',
  },
  {
    id: 'fsc-80662',
    title: "[부처합동] 새마을금고 '23년 상반기 영업실적(잠정) 발표",
    publisher: '금융위원회 · 행정안전부',
    date: '2023-08-31',
    url: 'https://www.fsc.go.kr/no010101/80662',
    kind: 'regulatory',
    note: '총자산 290.7조, 총수신 259.4조, 연체율 5.41%, 순자본비율 8.29%, 상반기 순손실 1,236억',
  },
  {
    id: 'fsc-69869',
    title:
      '(부산)부산상호저축은행 및 (대전)대전상호저축은행에 대한 부실금융기관 결정 및 영업정지 조치 부과',
    publisher: '금융위원회',
    date: '2011-02-17',
    url: 'https://www.fsc.go.kr/no010101/69869',
    kind: 'regulatory',
    note: '2011.2.17 부산·대전 영업정지(부산 자본 완전잠식)',
  },
  {
    id: 'fsc-69871',
    title: '부산저축은행·대전저축은행의 영업정지와 관련한 정부 입장',
    publisher: '금융위원회',
    date: '2011-02-17',
    url: 'https://www.fsc.go.kr/no010101/69871',
    kind: 'regulatory',
    note: '"과도한 예금인출 없는 한 상반기 추가 정지 없을 것" 조건부 발언; 유동성 백스톱 6조(중앙회 3조 + 크레딧라인 2조 + 증권금융 1조)',
  },
  {
    id: 'fsc-71188',
    title: '저축은행 구조조정 성과 평가 및 향후 정책 방향',
    publisher: '금융위원회',
    date: '2014-07-03',
    url: 'https://www.fsc.go.kr/no010101/71188',
    kind: 'regulatory',
    note: '105개(2010말)→87개(2014.5), BIS 5.6%(2011.6)→11.2%(2013.12), 정리 30개, 특별계정 27.2조',
  },
  {
    id: 'fsc-82312',
    title: '[보도자료] 금융규제 유연화 조치 점검회의 개최',
    publisher: '금융위원회',
    date: '2024-05-21',
    url: 'https://www.fsc.go.kr/no010101/82312',
    kind: 'regulatory',
    note: '은행 원화 LCR 정상화 경로(2020.4 85% → 2022.7 90% → 2022.10 92.5% → 2024 97.5%)',
  },
  {
    id: 'fsc-83490',
    title: '[보도자료] 금융규제 유연화 조치 점검회의 개최',
    publisher: '금융위원회',
    date: '2024-11-29',
    url: 'https://www.fsc.go.kr/no010101/83490',
    kind: 'regulatory',
    note: '은행 원화 LCR 2025.1.1 100% 복귀',
  },
  {
    id: 'fsc-86032',
    title: '보험회사 기본자본 K-ICS비율 제도 시행을 통한 자본구조의 質 개선',
    publisher: '금융위원회',
    date: '2026-01-13',
    url: 'https://www.fsc.go.kr/no010101/86032',
    kind: 'regulatory',
    note: '기본자본 K-ICS 50%, 2027.1.1 시행, 경과 9년',
  },
  {
    id: 'fsc-86917',
    title: '증권사 유동성 관리 강화를 위한 「금융투자업규정」 및 「시행세칙」 개정 추진',
    publisher: '금융위원회',
    date: '2026-05-18',
    url: 'https://www.fsc.go.kr/no010101/86917',
    kind: 'regulatory',
    note: '2027.1.1 유동성비율 개편: 49개사 전체, 유동자산 헤어컷(AAA 0%·AA 7%·A 이하 10%·주식 15%·합성 ETF 30%), 우발채무 유동부채 포함',
  },
  {
    id: 'fsc-87126',
    title: '「상호금융업감독규정」 개정안 금융위 의결',
    publisher: '금융위원회',
    date: '2026-06-17',
    url: 'https://www.fsc.go.kr/no010101/87126',
    kind: 'regulatory',
    note: '상호금융 PF 총대출 20%(2027.4.1), 부동산·건설·PF 합산 50%, 순자본비율 최소 4%(2028~31 단계)',
  },
  {
    id: 'fsc-dls-plan-2020',
    title: '파생결합증권시장 건전화 방안 (파생결합증권시장을 보다 건전하게 발전시키겠습니다)',
    publisher: '금융위원회',
    date: '2020-07-30',
    url: 'https://www.korea.kr/briefing/pressReleaseView.do?newsId=156403711',
    kind: 'regulatory',
    note: '자체헤지 증권사 외화유동자산 10~20% 보유, 레버리지비율 가중치 상향, 유동성비율 조기상환 시점 기준',
  },

  // ───────────────────────── 한국: 법령·정책·연구 ─────────────────────────
  {
    id: 'bok-act',
    title:
      '한국은행법 (제65조 금융기관에 대한 긴급여신 · 제68조 공개시장운영 · 제80조 영리기업 여신)',
    publisher: '대한민국 법률 (위키문헌 수록본)',
    date: '2026-09',
    url: 'https://ko.wikisource.org/wiki/한국은행법',
    kind: 'primary',
    note: '65조: 유동성 악화 금융기관에 임시 적격담보로 긴급여신(금통위 4명 이상 찬성, 정부 의견 청취); 80조: 비은행 영리기업 여신(4명 이상)',
  },
  {
    id: 'korea-kr-deposit-limit-2025',
    title: '오는 9월 1일부터 예금보호 한도 5000만 원→1억 원으로 상향',
    publisher: '대한민국 정책브리핑(korea.kr) · 금융위원회',
    date: '2025-05-15',
    url: 'https://www.korea.kr/news/policyNewsView.do?newsId=148943235',
    kind: 'regulatory',
    note: '2025.9.1 시행, 24년 만 상향; 은행·저축은행·상호금융 적용',
  },
  {
    id: 'mg-joint-briefing-2023',
    title: '새마을금고 건전성 관련 관계부처 합동 브리핑(행안부·기재부·금융위·금감원·한은)',
    publisher: '행정안전부 외 범정부 대응단',
    date: '2023-07-06',
    kind: 'regulatory',
    note: '예수금 259.6조(6/29), 연체액 12.16조, 상환준비금 13.36조, 현금성자산 77.3조, 예금자보호준비금 2.6조; 합병 시에도 5천만원 초과 원리금 지급',
  },
  {
    id: 'bok-omo-2022-10-27',
    title: '한국은행 공개시장운영 조치(RP 매입 6조원, 적격담보증권 확대, 담보비율 인상 유예)',
    publisher: '한국은행',
    date: '2022-10-27',
    kind: 'regulatory',
    note: 'RP 6조(~2023.1.31), 적격담보에 은행채·공공기관채 포함(11/1~3개월), 최대 36.5조 효과',
  },
  {
    id: 'audit-savings-bank-2011',
    title: '서민금융 지원시스템 운영 및 감독실태 (감사결과)',
    publisher: '감사원',
    date: '2011-03-17',
    kind: 'regulatory',
    note: '저축은행 PF 부실·감독 실태; 2010년 138일 검사 미적발',
  },
  {
    id: 'audit-fx-crisis-1998',
    title: '외환위기 특별감사 결과',
    publisher: '감사원',
    date: '1998-04-10',
    kind: 'regulatory',
    note: '한국은행 23차례 보고에도 대응 지연',
  },
  {
    id: 'kcmi-lee-2022-18',
    title: '이슈보고서 22-18 (이효섭): 비은행 부동산 PF 익스포저 리스크',
    publisher: '자본시장연구원',
    date: '2022-09-05',
    kind: 'academic',
    note: '비은행 PF 78.1조, A3- CP 6.0% 경고. URL 미확인',
  },
  {
    id: 'kcmi-23-10',
    title: '이슈보고서 23-10: 국내 증권업 부동산PF 위험요인과 대응방안 (장근혁·이석훈·이효섭)',
    publisher: '자본시장연구원',
    date: '2023-05',
    url: 'https://www.kcmi.re.kr/report/report_view?report_no=1747',
    kind: 'academic',
    note: '증권사 PF 채무보증 구조와 위험요인',
  },
  {
    id: 'kdi-focus-hwang-2025',
    title: 'KDI FOCUS: 부동산 PF 자본확충의 효과와 제도개선 방안 (황순주)',
    publisher: '한국개발연구원(KDI)',
    date: '2025-09-22',
    url: 'https://www.kdi.re.kr/research/focusView?pub_no=18876',
    kind: 'academic',
    note: '시행사 자기자본 3%→20% 시 총사업비 7.2% 절감',
  },

  // ───────────────────────── 시뮬레이션 훈련 실무 ─────────────────────────
  {
    id: 'worldbank-cse-handbook-2023',
    title: 'The World Bank Crisis Simulation Exercise Handbook',
    publisher: 'World Bank',
    date: '2023',
    url: 'https://documents.worldbank.org/en/publication/documents-reports/documentdetail/099125002162330340',
    kind: 'regulatory',
    note: '계획-구축-실행-보고 사이클, 인젝트, 시간 압축, 구조화된 디브리핑; 설계 원칙 6가지의 근거',
  },
  {
    id: 'bis-fsi-paper-21',
    title:
      'Cross-border crisis simulation exercise in sub-Saharan Africa (FSI Occasional Paper No 21)',
    publisher: 'BIS Financial Stability Institute',
    date: '2023-12',
    url: 'https://www.bis.org/fsi/fsipapers21.htm',
    kind: 'regulatory',
    note: '8개국 국경간 CSE: ELA 타이밍 결정이 당국별로 상이, 8곳 중 4곳 국가별 해법 선택',
  },
  {
    id: 'sffed-chair-the-fed',
    title: 'Chair the Fed (교육용 통화정책 시뮬레이션) 및 학습효과 연구(Duzhak·Hoff·Lopus, 2021)',
    publisher: 'Federal Reserve Bank of San Francisco / SAGE (Journal of Economics Education)',
    date: '2021',
    url: 'https://journals.sagepub.com/doi/abs/10.1177/0569434520971193',
    kind: 'academic',
    note: '16분기 운영, 월 8만 회+ 플레이(2019), 완주 중 ~20% 재임명; 전통 수업 대비 사후 테스트 점수 상승',
  },
]

export const SOURCE_IDS: ReadonlySet<string> = new Set(SOURCES.map((s) => s.id))
