import type { ScenarioSummary } from '../engine/types'

/** Catalog entries for scenarios scheduled in M2/M3 (not yet playable). */
export const PLANNED_SCENARIOS: ScenarioSummary[] = [
  {
    id: 'covid-2020-fund',
    version: 0,
    title: '현금 확보 쇄도',
    subtitle: '2020년 3월 회사채 펀드 환매 위기',
    era: '2020-03',
    year: 2020,
    region: 'global',
    role: 'asset_manager_pm',
    roleTitle: '회사채 펀드 포트폴리오매니저(PM)',
    institutionType: 'asset_manager',
    institutionName: '하버라이트 크레딧펀드(Harborlight Credit Fund)',
    difficulty: 'standard',
    durationTurns: 8,
    turnUnit: 'day',
    estMinutes: 35,
    competencies: { liquidity: 3, marketRisk: 3, communication: 1 },
    tags: ['환매', '스윙프라이싱', 'ETF', 'SMCCF'],
    status: 'planned',
  },
  {
    id: 'els-margin-2020',
    version: 0,
    title: '마진콜 5조',
    subtitle: '2020년 3월 증권사 ELS 헤지 위기',
    era: '2020-03',
    year: 2020,
    region: 'korea',
    role: 'securities_treasurer',
    roleTitle: '대형 증권사 자금부장',
    institutionType: 'securities',
    institutionName: '대한투자증권(가상)',
    difficulty: 'standard',
    durationTurns: 8,
    turnUnit: 'day',
    estMinutes: 35,
    competencies: { liquidity: 3, marketRisk: 2, compliance: 1, policy: 1 },
    tags: ['ELS', '마진콜', '통화스와프', 'CP'],
    status: 'planned',
  },
  {
    id: 'archegos-2021',
    version: 0,
    title: '죄수의 딜레마',
    subtitle: '2021년 3월 아케고스 청산',
    era: '2021-03',
    year: 2021,
    region: 'global',
    role: 'pb_risk_head',
    roleTitle: '프라임브로커 리스크 헤드',
    institutionType: 'prime_broker',
    institutionName: '알파인은행 프라임서비스(Alpine Bank Prime)',
    difficulty: 'advanced',
    durationTurns: 7,
    turnUnit: 'day',
    estMinutes: 35,
    competencies: { marketRisk: 3, compliance: 2, solvency: 2, communication: 1 },
    tags: ['TRS', '마진', '집중도', '블록 매각'],
    status: 'planned',
  },
  {
    id: 'korea-imf-1997',
    version: 0,
    title: '가용외환보유액 39억달러',
    subtitle: '1997년 외환위기',
    era: '1997-11',
    year: 1997,
    region: 'korea',
    role: 'central_bank_official',
    roleTitle: '재경원·한은 정책담당',
    institutionType: 'central_bank',
    institutionName: '대한민국 외환당국',
    difficulty: 'advanced',
    durationTurns: 10,
    turnUnit: 'week',
    estMinutes: 50,
    competencies: { policy: 3, liquidity: 2, communication: 2, compliance: 1 },
    tags: ['환율', 'IMF', '종금사', '외채 롤오버'],
    status: 'planned',
  },
  {
    id: 'credit-suisse-2023',
    version: 0,
    title: '취리히의 주말',
    subtitle: '2023년 3월 크레디트스위스 정리',
    era: '2023-03',
    year: 2023,
    region: 'global',
    role: 'regulator_official',
    roleTitle: 'FINMA·SNB 정책담당',
    institutionType: 'central_bank',
    institutionName: '스위스 금융당국',
    difficulty: 'advanced',
    durationTurns: 6,
    turnUnit: 'day',
    estMinutes: 30,
    competencies: { policy: 3, compliance: 2, communication: 2, solvency: 1 },
    tags: ['AT1', 'ELA', '합병', '베일인'],
    status: 'planned',
  },
  {
    id: 'savings-bank-2011',
    version: 0,
    title: '영업정지 명령',
    subtitle: '2011년 저축은행 구조조정',
    era: '2011-02',
    year: 2011,
    region: 'korea',
    role: 'regulator_official',
    roleTitle: '금융위·금감원 정책담당',
    institutionType: 'central_bank',
    institutionName: '금융당국',
    difficulty: 'standard',
    durationTurns: 8,
    turnUnit: 'day',
    estMinutes: 35,
    competencies: { policy: 3, communication: 2, compliance: 2, liquidity: 1 },
    tags: ['영업정지', 'P&A', '예보', '후순위채'],
    status: 'planned',
  },
  {
    id: 'ltcm-1998',
    version: 0,
    title: '컨소시엄',
    subtitle: '1998년 LTCM 구제',
    era: '1998-09',
    year: 1998,
    region: 'global',
    role: 'pb_risk_head',
    roleTitle: '프라임브로커 리스크 헤드',
    institutionType: 'prime_broker',
    institutionName: '월가 대형 증권사(가상)',
    difficulty: 'advanced',
    durationTurns: 6,
    turnUnit: 'day',
    estMinutes: 30,
    competencies: { marketRisk: 3, policy: 2, compliance: 1 },
    tags: ['레버리지', '스왑 스프레드', '연준 조율'],
    status: 'planned',
  },
  {
    id: 'taeyoung-pf-2024',
    version: 0,
    title: '워크아웃 동의율 75%',
    subtitle: '2024년 부동산 PF 구조조정',
    era: '2023-12',
    year: 2024,
    region: 'korea',
    role: 'bank_credit_officer',
    roleTitle: '주채권은행 여신담당',
    institutionType: 'bank',
    institutionName: '주채권은행(가상)',
    difficulty: 'standard',
    durationTurns: 8,
    turnUnit: 'week',
    estMinutes: 35,
    competencies: { solvency: 3, compliance: 2, policy: 2, communication: 1 },
    tags: ['워크아웃', '출자전환', '사업성 평가'],
    status: 'planned',
  },
]
