/**
 * FactLedger — initialState의 모든 숫자 리프를 출처에 연결한다 (docs/authoring-guide.md 저자 체크리스트 1).
 * tag: VERIFY (1차 출처 미확인, 해소 문서를 note에 명시) · STYLIZED (선언된 단순화) · CAL (보정 가정, calibration.md)
 * 단위: 십억 스위스프랑(CHF 1e9) 외 명시.
 *
 * `institution.*` 경로는 `CentralBankState`를 2023년 취리히 사건에 맞게 재해석해서 쓴다. 재해석 규약은
 * initialState.ts 상단 주석과 calibration.md §2에 있다 — 원장은 **재해석된 의미**를 기준으로 적는다.
 */
export interface FactRow {
  path: string
  value: number
  unit: string
  asOf: string
  knownAt?: string
  sourceId: string
  tag?: 'VERIFY' | 'STYLIZED' | 'CAL'
  note?: string
}

const FINMA = 'finma-cs-report-2023'
const Q4 = 'cs-4q22-earnings'
const PRESS_SHARE = 'press-cs-share-2023-03'
const ORD136 = 'plb-eo-2023-136'

export const CS_FACTS: FactRow[] = [
  // ───────── 당국의 공여 여력 ─────────
  {
    path: 'institution.reserves.gross',
    value: 50,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: FINMA,
    note: '통상법상 SNB가 동원할 수 있는 유동성 지원 한도. FINMA 보고서는 3월 19일 시점의 총 공여 가능액을 "ELA and EFF: CHF 50 billion; ELA+: CHF 100 billion [of which CHF 50 billion for CS]; PLB: CHF 100 billion"으로 적는다. 긴급명령 이전의 50이 이 값이다',
  },
  {
    path: 'institution.reserves.usable',
    value: 50,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'CAL',
    note: '그중 CS의 적격담보로 실제 뒷받침되는 즉시 공여 여력. 3월 16일에 ELA 380억 + LSFF 100억 = 480억이 실제로 나간 것이 이 값의 하한 앵커다(calibration.md §3)',
  },
  {
    path: 'institution.reserves.forwardCommitments',
    value: 0,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: ORD136,
    note: '연방정부 보증 노출. 3월 14일에는 0이며, 3월 19일 재정대표단(FinDel)이 PLB 이행보증 1,000억 + 손실보전 보증 90억 = 1,090억 프랑의 긴급 약정 신용을 승인한다',
  },

  // ───────── 크레디트스위스의 규모 ─────────
  {
    path: 'institution.external.shortTermDebt',
    value: 233,
    unit: 'CHF_B',
    asOf: '2022-12-31',
    sourceId: 'cs-ar-2022',
    note: 'CS **그룹** 고객예금 잔액 **CHF 233,235백만**(2021년 392,819). 원문 확인(2026-09): Annual Report 2022 = Form 20-F(FY2022)의 "Capitalization and indebtedness" 표와 주석 25 Deposits("Total deposits 245,140 … of which customer deposits 233,235"). **주의**: 같은 표의 Bank(Credit Suisse AG) 값은 234,554로 다르다 — 이 시나리오는 그룹 기준을 쓴다',
  },
  {
    path: 'institution.external.totalDebt',
    value: 486,
    unit: 'CHF_B',
    asOf: '2022-12-31',
    sourceId: 'cs-ar-2022',
    note: 'CS 그룹 총부채 **CHF 486,027백만**. 원문 확인(2026-09) — 20-F의 "Condensed consolidated balance sheets" 표가 `Total assets 531,358 / Total liabilities 486,027`을 직접 싣는다(자기자본 45,129 + 비지배지분 202 = 총자본 45,331; 531,358 − 45,331 = 486,027로 검산된다). 종전의 역산 표기와 자기자본 [VERIFY]를 함께 해소하고 CAL 태그를 뗐다',
  },
  {
    path: 'institution.external.monthlyImports',
    value: 91,
    unit: 'CHF_B',
    asOf: '2022-10',
    sourceId: FINMA,
    note: 'CS의 30일 스트레스 순유출(LCR 분모). FINMA 보고서: 2022년 10월 실제 유출 약 920억 프랑이 "corresponded roughly to the deposit outflows modelled by the LCR (CHF 91 billion)". 이 시나리오에서 `importCoverMonths` 지표는 "공여 여력 / LCR 스트레스 순유출" 배수로 읽는다',
  },
  {
    path: 'institution.external.broadMoneyUsd',
    value: 1294,
    unit: 'CHF_B',
    asOf: '2022-12-31',
    sourceId: Q4,
    tag: 'CAL',
    note: 'CS 그룹 운용자산(AuM) 약 1.3조 프랑. 지표 계산에는 IMF ARA 산식에만 쓰이며 KPI로 노출하지 않는다',
  },
  {
    path: 'institution.external.annualExportsUsd',
    value: 781,
    unit: 'CHF_B',
    asOf: '2022',
    sourceId: 'bfs-gdp-2022',
    note: '스위스 명목 GDP **CHF 781,460백만**(2022). 원문 확인(2026-09): 연방통계청(BFS) 표 T 04.02.01.02 「Bruttoinlandprodukt nach Verwendungsarten」의 `B.1*b` 행, **1995~2022년판(2023-08-24 공표)**. **빈티지를 명시해서 쓴다** — 같은 계열이 이후 개정되어 1995~2023년판은 791,087, 벤치마크 개정 후 1995~2025년판(2026-08-25)은 819,704백만이다. 이 시나리오는 2023년 3월에 알 수 있었던 숫자를 쓰므로 781을 유지한다. 지표 계산에는 IMF ARA 산식에만 쓰인다',
  },

  // ───────── 통화·정책 ─────────
  {
    path: 'institution.fx.spot',
    value: 0.91,
    unit: 'USD/CHF',
    asOf: '2023-03-13',
    sourceId: 'fred-dexszus',
    note: '미달러/스위스프랑 **0.9118**(연준 H.10 뉴욕 정오 매입환율, FRED DEXSZUS 직접 조회). 종전 값 0.92를 정정했다 — 표시 전용이며 게임 계산에 쓰이지 않는다. SNB devkum 2023-03 월평균 0.92552·월말 0.91625와 정합',
  },
  {
    path: 'institution.fx.interventionToday',
    value: 0,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'STYLIZED',
    note: '이 시나리오는 외환시장 개입을 다루지 않는다(0 고정)',
  },
  {
    path: 'institution.policy.rateBp',
    value: 100,
    unit: 'bp',
    asOf: '2023-03-13',
    sourceId: 'snb-mpa-2022-2023',
    note: 'SNB 정책금리 1.00%. 원문 확인 결과 **1.00%는 2022-12-15 결정(12-16 적용)** 이며, 2022-09-22 결정은 0.50%였다 — 종전 note의 "2022-09-22 이후"를 정정했다. 다음 인상(1.50%)은 3월 23일 결정·24일 적용으로 시나리오 창 밖이다',
  },

  // ───────── 은행 시스템 상태 ─────────
  {
    path: 'institution.bankingSystem.npls',
    value: 0,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'STYLIZED',
    note: '이 위기는 자산 건전성이 아니라 신뢰·유동성 위기다. FINMA 2023-03-19: "There was a risk of the bank becoming illiquid, even if it remained solvent." 부실여신은 모형화하지 않는다',
  },
  {
    path: 'institution.bankingSystem.capitalShortfall',
    value: 0,
    unit: 'CHF_B',
    asOf: '2023-03-15',
    sourceId: 'finma-snb-statement-2023-03-15',
    note: '3월 15일 FINMA·SNB 공동성명은 CS가 시스템적 중요 은행에 부과된 특별 자본·유동성 요건을 충족한다고 확인했다 — 자본 부족액은 0이다',
  },
  {
    path: 'institution.bankingSystem.liquiditySupport',
    value: 0,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: FINMA,
    note: 'SNB 지원 누계. 3월 14일에는 0, 3월 16일 480억, 3월 17일 680억, 3월 말 1,680억이 된다',
  },
  {
    path: 'institution.bankingSystem.failedBanks',
    value: 0,
    unit: 'count',
    asOf: '2023-03-14',
    sourceId: FINMA,
    note: '정리·파산 절차에 들어간 스위스 시스템적 중요 은행 수',
  },
  {
    path: 'institution.bankingSystem.distressedBanks',
    value: 1,
    unit: 'count',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'CAL',
    note: '크레디트스위스 1개. FINMA는 2022년 10월 위기대응 단계에서 CS에 대해 "Red Phase"를 선언했고 그 상태가 이어지고 있었다',
  },
  {
    path: 'institution.sovereign.debtToGdpPct',
    value: 24.5,
    unit: '%',
    asOf: '2022',
    sourceId: 'efv-schuldenquote',
    note: '**정정 27.5 → 24.5.** 스위스 일반정부 마스트리흐트 기준 총부채/GDP. 연방재무행정청(EFV) 재정통계 데이터셋 `kennz_int`의 지표 `schuldenquote`를 직접 조회한 결과 **2022년 = 24.55%**(2021년 25.65 · 2023년 24.31)이고 **27.51%는 2016년 값**이다 — 연도가 어긋난 인용이었다. 빈티지 주의: 같은 데이터셋의 2025-08 스냅숏은 2022년을 25.9%로 실었고 GDP 개정에 따라 소급 변동한다. 마스트리흐트 총부채 수준 자체는 2022년 CHF 197,039백만이며, IMF 정의의 `fremdkapitalquote`(2022년 39.15%)와 혼동하지 않는다. 재정 여력이 충분하다는 점이 국유화·보증 선택지를 실재하게 만든다',
  },
  {
    path: 'institution.sovereign.spreadBp',
    value: 15,
    unit: 'bp',
    asOf: '2023-03-13',
    sourceId: FINMA,
    tag: 'STYLIZED',
    note: '스위스 연방정부 5년 CDS 프록시. 게임에서는 연방 보증 노출에 비례해 벌어진다(fx.ts sync: 15 + 0.05 × 보증노출) — 납세자가 떠안은 위험을 눈에 보이게 하기 위한 장치이며 관측값이 아니다',
  },
  {
    path: 'institution.imf.committed',
    value: 0,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'STYLIZED',
    note: '국제통화기금 프로그램은 이 시나리오와 무관하다(0 고정)',
  },
  {
    path: 'institution.imf.disbursed',
    value: 0,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'STYLIZED',
    note: '위와 같음',
  },

  // ───────── 크레디트스위스 상태 (custom) ─────────
  {
    path: 'institution.custom.csLiquidity',
    value: 38,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'CAL',
    note: '**이 시나리오에서 가장 중요한 보정값이다.** CS가 그날 결제에 실제로 쓸 수 있었던 유동성(현금·중앙은행 예치·즉시 현금화 가능 담보)의 일별 계열은 공표된 적이 없다. 38은 두 개의 문서화된 앵커에서 역산했다: ① 3월 16일 480억 프랑을 공여받고도 17일에 다시 200억이 필요했다 ② "Without this further support, CS would have become immediately insolvent by midday on Friday, 17 March 2023." 역사 경로가 이 두 조건을 모두 만족하도록 초기값과 담보·한도 소요를 맞추었다(calibration.md §3)',
  },
  {
    path: 'institution.custom.csDeposits',
    value: 233,
    unit: 'CHF_B',
    asOf: '2022-12-31',
    sourceId: 'cs-ar-2022',
    note: '`institution.external.shortTermDebt`의 표시 사본 — 같은 출처(CHF 233,235백만)',
  },
  {
    path: 'institution.custom.csCdsBp',
    value: 450,
    unit: 'bp',
    asOf: '2023-03-13',
    sourceId: FINMA,
    tag: 'VERIFY',
    note: 'CS 5년 선순위 CDS. 3월 15일에 1,000bp를 넘었다는 것은 FINMA 보고서 본문(“CDS spreads rose above the 1000 basis-point mark”)과 SNB 『Financial Stability Report 2023』 인쇄본 p.23·p.25(“its CDS premia peaked at more than 1,000 basis points on 15 March”, 각주 “Premia for credit protection (five-year senior)”)로 이중 확인되지만, **3월 13일 수준 450bp는 여전히 미확인**이며 FINMA 보고서 그림 "CS Group: share price and CDS spreads"(세로축 200~1,200bp) 눈금에서 읽은 값이다 — 해소 문서(택일): ① FINMA 그 그림의 원자료 ② SNB FSR 2023 차트 33의 원계열(차트 하단 "Source(s): Bloomberg") ③ S&P Global Market Intelligence 또는 ICE의 CSG 5Y 선순위 CDS 2023-03-13 일별 종가',
  },
  {
    path: 'institution.custom.csCet1Pct',
    value: 14.1,
    unit: '%',
    asOf: '2022-12-31',
    sourceId: Q4,
    note: '원문 확인. 4Q22 말 CET1 비율 14.1%. **자본은 문제가 아니었다는 사실의 숫자**이며, 그래서 이 사건은 자본 위기가 아니라 유동성·신뢰 위기로 분류된다',
  },
  {
    path: 'institution.custom.csAt1Nominal',
    value: 16,
    unit: 'CHF_B',
    asOf: '2023-03-19',
    sourceId: 'finma-pr-2023-03-19',
    note: '원문 확인. FINMA 2023-03-19 보도자료: "a complete write-down of the nominal value of all AT1 debt of Credit Suisse in the amount of around CHF 16 billion". FINMA 2023.12 보고서는 같은 금액을 "CHF 16.5 billion (nominal value)"으로 적는다 — 게임은 보도자료의 16을 쓰고 체크포인트 허용오차(±5%)로 두 값을 모두 감싼다',
  },
  {
    path: 'institution.custom.dailyOutflow',
    value: 1.6,
    unit: 'CHF_B',
    asOf: '2023-03-13',
    sourceId: FINMA,
    note: '원문 확인. 3월 13일 고객자금 유출 16억 프랑',
  },
  {
    path: 'institution.custom.cumulativeOutflow',
    value: 1.6,
    unit: 'CHF_B',
    asOf: '2023-03-13',
    sourceId: FINMA,
    note: '3월 13일부터의 누계. 게임은 3월 13일을 기점으로 센다',
  },
  {
    path: 'institution.custom.supportDrawn',
    value: 0,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: FINMA,
    note: '`institution.bankingSystem.liquiditySupport`의 표시 사본',
  },
  {
    path: 'institution.custom.federalGuarantee',
    value: 0,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: ORD136,
    note: '`institution.reserves.forwardCommitments`의 표시 사본',
  },
  {
    path: 'institution.custom.at1WrittenOff',
    value: 0,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: 'finma-pr-2023-03-19',
    note: '3월 14일에는 0. 3월 19일에 160억이 된다',
  },
  {
    path: 'institution.custom.shareholderConsideration',
    value: 0,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: 'ubs-cs-merger-2023-03-19',
    note: '3월 14일에는 0. 3월 19일에 30억(주당 0.76프랑)이 된다',
  },
  {
    path: 'institution.custom.mondayCashRequirement',
    value: 0,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: FINMA,
    note: '주말 턴에서 1,000억으로 설정된다. FINMA 보고서: 3월 19일 아침 CS 재무부가 "문제 없이 다음 주를 시작하기 위해 필요한 현금"을 여러 통화로 약 1,000억 프랑으로 추정했다',
  },

  // ───────── 시장 (외생) ─────────
  {
    path: 'market.policyRateBp',
    value: 100,
    unit: 'bp',
    asOf: '2023-03-13',
    sourceId: 'snb-mpa-2022-2023',
    note: '`institution.policy.rateBp`의 표시 사본 — 같은 출처',
  },
  {
    path: 'market.govt2yBp',
    value: 403,
    unit: 'bp',
    asOf: '2023-03-13',
    sourceId: 'fred-dgs',
    note: '직접 조회 확인. 미 국채 2년 4.03%. 같은 주 3/15 3.93 · 3/17 3.81 · 3/20 3.92',
  },
  {
    path: 'market.govt10yBp',
    value: 355,
    unit: 'bp',
    asOf: '2023-03-13',
    sourceId: 'fred-dgs',
    note: '직접 조회 확인. 미 국채 10년 3.55%',
  },
  {
    path: 'market.govt30yBp',
    value: 370,
    unit: 'bp',
    asOf: '2023-03-13',
    sourceId: 'fred-dgs',
    note: '직접 조회 확인. 미 국채 30년 3.70%',
  },
  {
    path: 'market.creditSpreadIgBp',
    value: 214,
    unit: 'bp',
    asOf: '2023-03-13',
    sourceId: 'fred-dbaa',
    tag: 'CAL',
    note: '투자등급 신용스프레드 프록시 = Baa 5.69% − 10년 국채 3.55% = 214bp. **개념적으로 맞는 계열은 유럽 투자등급 OAS(ICE BofA 또는 iTraxx Europe Main)이지만 익명 접근이 막혀 있다**(docs/research/data-sources-global.md §2) — 해소 문서: 무료 FRED API 키로 `api.stlouisfed.org/fred/series/observations?series_id=BAMLEMCBPIOAS` 또는 ICE BofA Euro Corporate Index OAS 전 기간 조회. 게임의 일별 궤적(3/14 211 · 3/15 222 · 3/16 216 · 3/17 221 · 3/20 219)은 전부 Baa−10년으로 계산한 실측값이다',
  },
  {
    path: 'market.creditSpreadHyBp',
    value: 500,
    unit: 'bp',
    asOf: '2023-03-13',
    sourceId: 'fred-dbaa',
    tag: 'STYLIZED',
    note: '하이일드 스프레드. 표시 전용이며 게임 계산에 쓰이지 않는다',
  },
  {
    path: 'market.fundingStressBp',
    value: 45,
    unit: 'bp',
    asOf: '2023-03-13',
    sourceId: 'fred-dgs',
    tag: 'STYLIZED',
    note: '달러 조달 스트레스 프록시. 표시 전용',
  },
  {
    path: 'market.equityIndex',
    value: 100,
    unit: 'index',
    asOf: '2023-03-13',
    sourceId: PRESS_SHARE,
    tag: 'STYLIZED',
    note: '유럽 은행 주가지수를 2023-03-13 종가 = 100으로 정규화한 양식화 계열. 일별 변동률의 1차 출처를 확보하지 못해 수준이 아니라 방향과 대략의 크기만 쓴다 — 해소 문서: STOXX 「STOXX Europe 600 Banks (SX7P)」 일별 지수 이력, 또는 ECB 『Financial Stability Review』 2023년 5월호의 은행 주가 도표 원자료',
  },
  {
    path: 'market.volIndex',
    value: 26.52,
    unit: 'index',
    asOf: '2023-03-13',
    sourceId: 'fred-dgs',
    note: '직접 조회 확인. VIX 종가 26.52. 같은 주 3/15 26.14 · 3/17 25.51 · 3/20 24.15',
  },
  {
    path: 'market.fxUsdLocal',
    value: 0.91,
    unit: 'USD/CHF',
    asOf: '2023-03-13',
    sourceId: 'fred-dexszus',
    note: '`institution.fx.spot`의 표시 사본 — 같은 출처(0.9118 → 0.91)',
  },
  {
    path: 'market.ownStock',
    value: 100,
    unit: 'index',
    asOf: '2023-03-13',
    sourceId: PRESS_SHARE,
    tag: 'CAL',
    note: 'CS 주가를 2023-03-13 종가 = 100으로 정규화. 게임의 궤적은 보도된 일별 변동률(3/15 −24% · 3/16 +18.8% · 3/17 −8%대 · 3/20 −55%대)을 곱해 만든다. **정합성 점검**: 이 궤적은 3/17 종가를 지수 82.7로 놓는데, 보도된 3/17 종가 1.86프랑을 대입하면 3/13 종가가 약 2.25프랑이 되어 당시 수준과 맞고, 3/19 인수 대가 0.76프랑은 지수 33.8에 해당해 3/20 종가 −55%대와도 맞는다',
  },
  {
    path: 'market.ownCdsBp',
    value: 450,
    unit: 'bp',
    asOf: '2023-03-13',
    sourceId: FINMA,
    tag: 'VERIFY',
    note: '`institution.custom.csCdsBp`의 표시 사본 — 같은 해소 문서',
  },

  // ───────── 신뢰지수 ─────────
  {
    path: 'confidence.index',
    value: 42,
    unit: 'index',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'CAL',
    note: 'S2(공개 런, 30~49). 2022년 4분기에 예금 1,380억 프랑이 빠진 은행이고, 같은 주에 미국에서 두 은행이 문을 닫았으며, 오늘 아침 연차보고서가 내부통제 중대 결함을 공시했다',
  },
  {
    path: 'confidence.depositors',
    value: 40,
    unit: 'index',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'CAL',
  },
  {
    path: 'confidence.counterparties',
    value: 38,
    unit: 'index',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'CAL',
    note: 'FINMA 보고서는 3월 중순 거래상대방과 금융시장인프라가 담보를 더 요구하고 한도를 줄였으며 일부는 거래를 끊었다고 적는다 — 이 지수가 그 상태를 담는다',
  },
  {
    path: 'confidence.regulators',
    value: 55,
    unit: 'index',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'CAL',
    note: '해외 감독·정리 당국(연준·영국 PRA·ECB·SRB)과의 관계. FINMA는 위기관리그룹(CMG)을 통해 계속 조율하고 있었다',
  },
  {
    path: 'confidence.investors',
    value: 35,
    unit: 'index',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'CAL',
  },
  {
    path: 'confidence.media',
    value: 35,
    unit: 'index',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'CAL',
  },
  {
    path: 'confidence.board',
    value: 50,
    unit: 'index',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'CAL',
    note: '연방평의회·의회. 긴급명령과 재정대표단 승인이 필요해지는 상대다',
  },

  // ───────── 초기 플래그·카운터 ─────────
  {
    path: 'regulatorLevel',
    value: 1,
    unit: 'index',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'CAL',
    note: 'R1 강화 감시. FINMA는 2022년 10월 이후 CS를 집중 감시하고 있었고 정리 준비를 이어 가고 있었다',
  },
  {
    path: 'counters.drainMultiplier',
    value: 1,
    unit: 'x',
    asOf: '2023-03-14',
    sourceId: FINMA,
    tag: 'CAL',
    note: '역사 경로에서 항상 1.0. 각 턴의 유출 총액이 곧 FINMA 보고서의 실측값이므로, 역사와 다른 선택만 이 계수를 움직인다',
  },
  {
    path: 'counters.cumulativeOutflow',
    value: 1.6,
    unit: 'CHF_B',
    asOf: '2023-03-13',
    sourceId: FINMA,
    note: '`institution.custom.cumulativeOutflow`와 같은 값의 카운터 사본(점수 계산용)',
  },
  {
    path: 'counters.lossGuaranteeBn',
    value: 9,
    unit: 'CHF_B',
    asOf: '2023-03-19',
    sourceId: ORD136,
    note: '주말 협상 대화의 숫자 약속 카운터. **역사 기준값으로 초기화해 둔다** — 대화를 건너뛰어도(마감 스윕으로 기본 옵션이 확정되어도) 역사적 결과가 그대로 재현되게 하기 위해서다. 긴급명령 제14a조 제2항: "Die Garantie zur Verlustabsicherung beträgt höchstens 9 Milliarden Schweizer Franken"',
  },

  // ───────── 앵커 (T0 값이 아닌 관측치) ─────────
  {
    path: 'anchor.outflow.2023-03-14',
    value: 2.7,
    unit: 'CHF_B',
    asOf: '2023-03-14',
    sourceId: FINMA,
    note: '원문 확인',
  },
  {
    path: 'anchor.outflow.2023-03-15',
    value: 13.2,
    unit: 'CHF_B',
    asOf: '2023-03-15',
    sourceId: FINMA,
    note: '원문 확인. 최대주주의 추가 출자 거부 발언이 전해진 날',
  },
  {
    path: 'anchor.outflow.2023-03-16',
    value: 17.1,
    unit: 'CHF_B',
    asOf: '2023-03-16',
    sourceId: FINMA,
    note: '원문 확인. **480억 프랑을 공여한 바로 그날의 유출액이다.** 지원이 유출을 멈추지 못한다는 이 시나리오의 중심 사실',
  },
  {
    path: 'anchor.outflow.2023-03-17',
    value: 10.1,
    unit: 'CHF_B',
    asOf: '2023-03-17',
    sourceId: FINMA,
    note: '원문 확인',
  },
  {
    path: 'anchor.at1Price.2023-03-15',
    value: 23,
    unit: '%',
    asOf: '2023-03-15',
    sourceId: FINMA,
    note: '원문 확인. "certain AT1 instruments were trading at just 23% of their nominal value" — 시장은 상각 나흘 전에 이미 가격을 매기고 있었다',
  },
  {
    path: 'anchor.cds.2023-03-15',
    value: 1000,
    unit: 'bp',
    asOf: '2023-03-15',
    sourceId: FINMA,
    note: '원문 확인. "CDS spreads rose above the 1000 basis-point mark (=10%)"',
  },
  {
    path: 'anchor.support.2023-03-16',
    value: 48,
    unit: 'CHF_B',
    asOf: '2023-03-16',
    sourceId: FINMA,
    note: '원문 확인. ELA 380억 + LSFF 100억. CS는 같은 날 "최대 약 500억 프랑"을 이용할 뜻을 공표했다',
  },
  {
    path: 'anchor.support.2023-03-17',
    value: 20,
    unit: 'CHF_B',
    asOf: '2023-03-17',
    sourceId: FINMA,
    note: '원문 확인. ELA+ 200억. "Without this further support, CS would have become immediately insolvent by midday on Friday, 17 March 2023"',
  },
  {
    path: 'anchor.support.total',
    value: 168,
    unit: 'CHF_B',
    asOf: '2023-03-31',
    sourceId: FINMA,
    note: '원문 확인. 3월 말까지 SNB 지원 누계 1,680억 프랑(ELA 38 + LSFF 10 + ELA+ 20 + ELA+ 30 + PLB 70). PLB는 5월 31일까지, ELA+는 8월 말까지 전액 상환되었고 ELA 380억만 남았다',
  },
  {
    path: 'anchor.resolutionCapital',
    value: 73,
    unit: 'CHF_B',
    asOf: '2023-03-19',
    sourceId: FINMA,
    note: '원문 확인. FINMA 명령에 의한 정리를 택했을 경우의 자본조치 규모 — "These measures would have increased CS Group\'s capital by around CHF 73 billion." 주식 전액 상각 + AT1 전액 상각 + 베일인 채권의 주식 전환',
  },
  {
    path: 'anchor.rwa.2022-12-31',
    value: 250,
    unit: 'CHF_B',
    asOf: '2022-12-31',
    sourceId: 'cs-ar-2022',
    note: 'CS 그룹 위험가중자산 **CHF 250,540백만(BIS 바젤III 기준)**. 원문 확인(2026-09): 20-F "Balance sheet statistics" 및 "Eligible capital and risk-weighted assets – Group" 표. 같은 표의 스위스 기준 RWA는 규제조정 +423을 더한 250,963이고 Bank 단독은 BIS 249,536이다 — 게임은 그룹·BIS 기준 250을 쓴다. AT1 상각의 CET1 효과(상각액/RWA)를 계산하는 분모다',
  },
  {
    path: 'anchor.deposits.4q22Decline',
    value: 138,
    unit: 'CHF_B',
    asOf: '2022-12-31',
    sourceId: Q4,
    note: '원문 확인. 4Q22 고객예금 1,380억 프랑 감소. FINMA 보고서도 같은 수치를 적으며, 정기예금의 51%가 한 분기에 빠져나갔고 투자은행 부문은 예금의 81%를 잃었다고 부연한다',
  },

  // ───────── 체크포인트 ─────────
  {
    path: 'checkpoint.t1.csCdsBp',
    value: 1010,
    unit: 'bp',
    asOf: '2023-03-15',
    sourceId: FINMA,
    tag: 'CAL',
    note: '3월 15일 종가 기준 1,000bp 초과를 재현한다. 허용오차 ±15%',
  },
  {
    path: 'checkpoint.t1.dailyOutflow',
    value: 13.2,
    unit: 'CHF_B',
    asOf: '2023-03-15',
    sourceId: FINMA,
    note: '틱 5개로 쪼갠 슬라이스의 합이 정확히 13.2가 되어야 한다(분산 0)',
  },
  {
    path: 'checkpoint.t2.dailyOutflow',
    value: 17.1,
    unit: 'CHF_B',
    asOf: '2023-03-16',
    sourceId: FINMA,
    note: '480억 공여 당일의 유출액',
  },
  {
    path: 'checkpoint.t2.supportDrawn',
    value: 48,
    unit: 'CHF_B',
    asOf: '2023-03-16',
    sourceId: FINMA,
    note: 'ELA 38 + LSFF 10',
  },
  {
    path: 'checkpoint.t3.supportDrawn',
    value: 68,
    unit: 'CHF_B',
    asOf: '2023-03-17',
    sourceId: FINMA,
    note: '48 + ELA+ 20',
  },
  {
    path: 'checkpoint.t4.at1WrittenOff',
    value: 16,
    unit: 'CHF_B',
    asOf: '2023-03-19',
    sourceId: 'finma-pr-2023-03-19',
    note: '허용오차 ±5%로 FINMA 보도자료의 16과 2023.12 보고서의 16.5를 모두 감싼다',
  },
  {
    path: 'checkpoint.t4.shareholderConsideration',
    value: 3,
    unit: 'CHF_B',
    asOf: '2023-03-19',
    sourceId: 'ubs-cs-merger-2023-03-19',
    note: '주당 0.76프랑, CS 22.48주당 UBS 1주',
  },
  {
    path: 'checkpoint.t5.supportDrawn',
    value: 168,
    unit: 'CHF_B',
    asOf: '2023-03-20',
    sourceId: FINMA,
    note: '3월 20일 ELA+ 300억 + PLB 700억이 더해져 누계 1,680억',
  },
  {
    path: 'checkpoint.t5.federalGuarantee',
    value: 109,
    unit: 'CHF_B',
    asOf: '2023-03-19',
    sourceId: FINMA,
    note: '원문 확인. 재정대표단(FinDel)이 3월 19일 임시회의에서 승인한 긴급 약정 신용 총액 1,090억 프랑 = PLB 이행보증 1,000억 + 손실보전 보증 90억. 이 승인이 연방의회 의결을 대신했다',
  },
]
