import type { Source } from '../../engine/types'

/** S1–S24: bibliography for the SVB 2023 scenario. Ids are referenced by options, lessons and quiz. */
export const SVB_SOURCES: Source[] = [
  {
    id: 'svb-10k-2022',
    title: 'SVB Financial Group, Form 10-K for fiscal year 2022',
    publisher: 'SEC EDGAR',
    date: '2023-02-24',
    kind: 'primary',
    url: 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000719739&type=10-K',
    note: '대차대조표, HTM/AFS, 미실현손실, 헤지, 듀레이션',
  },
  {
    id: 'svb-8k-2023-03-08',
    title:
      'SVB Financial Group, Form 8-K Ex. 99.1 — Strategic Actions / Q1 2023 Mid-Quarter Update',
    publisher: 'SEC EDGAR',
    date: '2023-03-08',
    kind: 'primary',
    url: 'https://www.sec.gov/Archives/edgar/data/719739/000119312523064680/d430920dex991.htm',
    note: 'AFS $21B 매각, 세후 손실 $1.8B, $2.25B 증자 구조',
  },
  {
    id: 'fed-svb-review-2023',
    title:
      "Review of the Federal Reserve's Supervision and Regulation of Silicon Valley Bank (Barr review)",
    publisher: 'Federal Reserve Board',
    date: '2023-04-28',
    kind: 'regulatory',
    url: 'https://www.federalreserve.gov/publications/files/svb-review-20230428.pdf',
    note: '3/9 $42B 유출, 3/10 $100B 대기, ILST 가정 변경, 담보 이동 실패, 무보험 94%',
  },
  {
    id: 'fed-oig-svb-mlr-2023',
    title: 'Material Loss Review of Silicon Valley Bank',
    publisher: 'Federal Reserve OIG',
    date: '2023-09',
    kind: 'regulatory',
    url: 'https://oig.federalreserve.gov/reports/board-material-loss-review-silicon-valley-bank-sep2023.pdf',
  },
  {
    id: 'gao-23-106736',
    title:
      'Preliminary Review of Agency Actions Related to March 2023 Bank Failures (GAO-23-106736)',
    publisher: 'U.S. GAO',
    date: '2023-04',
    kind: 'regulatory',
    url: 'https://www.gao.gov/products/gao-23-106736',
    note: '금요일 정오 폐쇄의 전례 없음, 정리 절차',
  },
  {
    id: 'dfpi-order-2023-03-10',
    title: 'Order Taking Possession of Property and Business — Silicon Valley Bank',
    publisher: 'California DFPI',
    date: '2023-03-10',
    kind: 'regulatory',
    url: 'https://dfpi.ca.gov/wp-content/uploads/sites/337/2023/03/DFPI-Orders-Silicon-Valley-Bank-03102023.pdf',
    note: '3/9 $42B 인출, 마감 시 연준 계좌 −$958M, cash letter 미결제',
  },
  {
    id: 'dfpi-review-2023-05',
    title: "Review of DFPI's Oversight and Regulation of Silicon Valley Bank",
    publisher: 'California DFPI',
    date: '2023-05-08',
    kind: 'regulatory',
    url: 'https://dfpi.ca.gov/2023/05/08/dfpi-review-of-silicon-valley-bank/',
  },
  {
    id: 'fdic-pr-16-2023',
    title:
      'FDIC Creates a Deposit Insurance National Bank of Santa Clara to Protect Insured Depositors of Silicon Valley Bank (PR-16-2023)',
    publisher: 'FDIC',
    date: '2023-03-10',
    kind: 'regulatory',
    url: 'https://www.fdic.gov/news/press-releases/2023/pr23016.html',
    note: '총자산 $209.0B, 예금 $175.4B, DINB',
  },
  {
    id: 'fdic-pr-17-2023',
    title: 'Joint Statement by Treasury, Federal Reserve, and FDIC (PR-17-2023)',
    publisher: 'FDIC',
    date: '2023-03-12',
    kind: 'regulatory',
    url: 'https://www.fdic.gov/news/press-releases/2023/pr23017.html',
    note: '시스템리스크 예외, 전 예금 보호, 주주·일부 무담보채권자 미보호',
  },
  {
    id: 'fdic-pr-19-2023',
    title: 'FDIC Acts to Protect All Depositors of the former Silicon Valley Bank (PR-19-2023)',
    publisher: 'FDIC',
    date: '2023-03-13',
    kind: 'regulatory',
    url: 'https://www.fdic.gov/news/press-releases/2023/pr23019.html',
    note: '브릿지뱅크, CEO Tim Mayopoulos',
  },
  {
    id: 'fed-btfp-2023-03-12',
    title:
      'Federal Reserve Board announces it will make available additional funding — Bank Term Funding Program term sheet',
    publisher: 'Federal Reserve Board',
    date: '2023-03-12',
    kind: 'regulatory',
    url: 'https://www.federalreserve.gov/newsevents/pressreleases/monetary20230312a.htm',
    note: '액면 담보, 1년 OIS+10bp, 최장 1년, 수수료 없음, ESF $25B',
  },
  {
    id: 'bcbs-d555',
    title: 'Report on the 2023 banking turmoil',
    publisher: 'Basel Committee on Banking Supervision',
    date: '2023-10',
    kind: 'regulatory',
    url: 'https://www.bis.org/bcbs/publ/d555.htm',
  },
  {
    id: 'metrick-jep-2024',
    title: 'The Failure of Silicon Valley Bank and the Panic of 2023',
    publisher: 'Journal of Economic Perspectives 38(1) — Andrew Metrick',
    date: '2024',
    kind: 'academic',
    url: 'https://www.aeaweb.org/articles?id=10.1257/jep.38.1.73',
  },
  {
    id: 'nyfed-sr1104',
    title: 'Tracing Bank Runs in Real Time (Staff Report 1104) — Cipriani, Eisenbach, Kovner',
    publisher: 'Federal Reserve Bank of New York',
    date: '2024',
    kind: 'academic',
    url: 'https://www.newyorkfed.org/medialibrary/media/research/staff_reports/sr1104.pdf',
  },
  {
    id: 'nber-w31048',
    title: 'Monetary Tightening and U.S. Bank Fragility in 2023 — Jiang, Matvos, Piskorski, Seru',
    publisher: 'NBER Working Paper 31048',
    date: '2023',
    kind: 'academic',
    url: 'https://www.nber.org/papers/w31048',
  },
  {
    id: 'nber-w31138',
    title: 'Banking on Uninsured Deposits — Drechsler, Savov, Schnabl, Wang',
    publisher: 'NBER Working Paper 31138',
    date: '2023',
    kind: 'academic',
    url: 'https://www.nber.org/papers/w31138',
  },
  {
    id: 'fred-dgs2',
    title: '2-Year Treasury Constant Maturity Rate (DGS2)',
    publisher: 'FRED, Federal Reserve Bank of St. Louis',
    date: '2023',
    kind: 'data',
    url: 'https://fred.stlouisfed.org/series/DGS2',
  },
  {
    id: 'fdic-pr-34-2023',
    title: 'JPMorgan Chase Bank Assumes All the Deposits of First Republic Bank (PR-34-2023)',
    publisher: 'FDIC',
    date: '2023-05-01',
    kind: 'regulatory',
    url: 'https://www.fdic.gov/news/press-releases/2023/pr23034.html',
    note: 'FRC: $30B 컨소시엄 예금에도 5/1 폐쇄',
  },
  {
    id: 'treasury-jy1349',
    title: 'Joint Statement on First Republic Bank deposit placement by eleven banks',
    publisher: 'U.S. Treasury',
    date: '2023-03-16',
    kind: 'regulatory',
    url: 'https://home.treasury.gov/news/press-releases/jy1349',
  },
  {
    id: 'finma-cs-lessons-2023',
    title: 'Lessons learned from the CS crisis',
    publisher: 'FINMA',
    date: '2023-12-19',
    kind: 'regulatory',
    url: 'https://www.finma.ch/en/~/media/finma/dokumente/dokumentencenter/myfinma/finma-publikationen/cs-bericht/20231219-finma-bericht-cs.pdf',
    note: 'CS 2022.10 증자 성공 사례, 일별 유출',
  },
  {
    id: 'fdic-oig-signature-2023',
    title: 'Material Loss Review of Signature Bank of New York (EVAL-24-02)',
    publisher: 'FDIC OIG',
    date: '2023-10',
    kind: 'regulatory',
    url: 'https://www.fdicoig.gov/sites/default/files/reports/2023-10/EVAL-24-02.pdf',
    note: '$18.6B 수시간 내 유출, FHLB 리엔 후순위화, 주말 담보 실사 실패',
  },
  {
    id: 'fsb-depositor-2024',
    title:
      'Depositor Behaviour and Interest Rate and Liquidity Risks in the Financial System — Lessons from the March 2023 Banking Turmoil',
    publisher: 'Financial Stability Board',
    date: '2024-10-23',
    kind: 'regulatory',
    url: 'https://www.fsb.org/uploads/P231024.pdf',
    note: '런 속도: 상위 3개 런 일 20~30%, fast-fail 시나리오',
  },
  {
    id: 'deloitte-fra-23-2',
    title:
      'Financial Reporting Alert 23-2: Accounting and reporting considerations related to the SVB failure (HTM tainting, ASC 320)',
    publisher: 'Deloitte',
    date: '2023-03',
    kind: 'book',
    url: 'https://dart.deloitte.com/USDART/home/publications/deloitte/financial-reporting-alerts/2023/silicon-valley-bank-failure',
  },
  {
    id: 'interagency-cfp-2023-07-28',
    title:
      'Agencies update guidance on liquidity risks and contingency planning (discount-window readiness addendum)',
    publisher: 'Federal Reserve / FDIC / OCC / NCUA',
    date: '2023-07-28',
    kind: 'regulatory',
    url: 'https://www.federalreserve.gov/newsevents/pressreleases/bcreg20230728a.htm',
  },
  {
    id: 'barr-speech-2023-12-01',
    title: 'The Importance of Effective Liquidity Risk Management (Vice Chair Barr speech)',
    publisher: 'Federal Reserve Board',
    date: '2023-12-01',
    kind: 'regulatory',
    url: 'https://www.federalreserve.gov/newsevents/speech/barr20231201a.htm',
    note: '사전 예치 담보가 도주성 부채 대비 극히 일부',
  },
  {
    id: 'bcbs-144',
    title: 'Principles for Sound Liquidity Risk Management and Supervision',
    publisher: 'Basel Committee on Banking Supervision',
    date: '2008-09',
    kind: 'regulatory',
    url: 'https://www.bis.org/publ/bcbs144.pdf',
    note: '원칙 11 비상자금조달계획',
  },
  {
    id: 'bcbs-248',
    title: 'Monitoring tools for intraday liquidity management',
    publisher: 'Basel Committee on Banking Supervision',
    date: '2013-04',
    kind: 'regulatory',
    url: 'https://www.bis.org/publ/bcbs248.pdf',
    note: '일중 유동성 모니터링 도구(일중 최대 순유출, 시간대별 결제 처리) — T4 결제데스크 인터럽트',
  },
  {
    id: 'ssga-kre',
    title: 'SPDR S&P Regional Banking ETF (KRE) — 펀드 개요·구성종목',
    publisher: 'State Street Global Advisors',
    date: '2023',
    kind: 'data',
    url: 'https://www.ssga.com/us/en/intermediary/etfs/spdr-sp-regional-banking-etf-kre',
    note: '지수 구성과 섹터 정의의 근거. 일별 종가는 아래 시세 출처를 쓴다',
  },
  {
    id: 'pacwest-10q-2023q1',
    title: 'PacWest Bancorp, Form 10-Q for the quarterly period ended March 31, 2023',
    publisher: 'SEC EDGAR',
    date: '2023-05-11',
    kind: 'primary',
    url: 'https://www.sec.gov/Archives/edgar/data/1102112/000162828023017382/pacw-20230331.htm',
    note:
      '원문: "Most of the decrease in deposits was from uninsured deposits, which resulted in the ' +
      'percentage of insured deposits to total deposits to increase from 48% at December 31, 2022 to ' +
      '71% of total deposits at March 31, 2023." 1분기 예금 −57억 달러(−16.9%), 벤처뱅킹 113억 → 66억',
  },
  {
    id: 'pacwest-8k-2023-03-22',
    title: 'Pacific Western Bank — 3월 중간 업데이트 (Form 8-K Ex. 99.1, 2023-03-17 및 2023-03-22)',
    publisher: 'SEC EDGAR',
    date: '2023-03-22',
    kind: 'primary',
    url: 'https://www.sec.gov/Archives/edgar/data/1102112/000110465923035404/tm239469d2_ex99-1.htm',
    note:
      '3/17자 보도자료(3/20 제출, accession 0001104659-23-034107): "As of March 16, 2023, insured deposits ' +
      'exceed 62% of total deposits, including accounts eligible for pass-through insurance", 가용현금 ' +
      '108억 달러. 3/22자 보도자료: "as of March 20, 2023, FDIC-insured deposits exceeded 65% of total ' +
      'deposits", 가용현금 114억 vs 무보험예금 95억, FHLB 37억·재할인창구 105억·BTFP 21억 차입, ' +
      'ATLAS SP 14억 ABS 조달. **"48%→71%"는 이 3월 공시가 아니라 1분기 10-Q(3/31 기준)의 수치다.**',
  },
  {
    id: 'kre-close-2023-03-09',
    title: '2023-03-09 미국 은행주 일간 하락폭 — KRE −8.1%, KBWB −7.6%, KBE −7.3%, BKX −7.7%',
    publisher: '시세 이력(ETF 종가) 및 당일 시장 보도',
    date: '2023-03-09',
    kind: 'data',
    note:
      'KRE는 2021년 1월 이후 최저 종가. 널리 인용되는 −7.7%는 KBW 나스닥 은행지수(BKX)의 ' +
      '수치로, 2020년 6월 이후 최대 일간 낙폭이다 — 두 값을 혼동하지 않도록 병기한다',
  },
  {
    id: 'sivb-close-2023-03-09',
    title: 'SVB Financial Group(SIVB) 2023-03-09 종가 $106.04, 전일 대비 −60.41%',
    publisher: '시세 이력(나스닥 상장 종가)',
    date: '2023-03-09',
    kind: 'data',
    note: '20년래 최대 일간 낙폭. 3/10 개장 전 −60% 추가 하락 후 거래정지·폐쇄',
  },
]
